// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package gateway_target

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.CredentialProviderConfigurations) != len(b.ko.Spec.CredentialProviderConfigurations) {
		delta.Add("Spec.CredentialProviderConfigurations", a.ko.Spec.CredentialProviderConfigurations, b.ko.Spec.CredentialProviderConfigurations)
	} else if len(a.ko.Spec.CredentialProviderConfigurations) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.CredentialProviderConfigurations, b.ko.Spec.CredentialProviderConfigurations) {
			delta.Add("Spec.CredentialProviderConfigurations", a.ko.Spec.CredentialProviderConfigurations, b.ko.Spec.CredentialProviderConfigurations)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.GatewayIdentifier, b.ko.Spec.GatewayIdentifier) {
		delta.Add("Spec.GatewayIdentifier", a.ko.Spec.GatewayIdentifier, b.ko.Spec.GatewayIdentifier)
	} else if a.ko.Spec.GatewayIdentifier != nil && b.ko.Spec.GatewayIdentifier != nil {
		if *a.ko.Spec.GatewayIdentifier != *b.ko.Spec.GatewayIdentifier {
			delta.Add("Spec.GatewayIdentifier", a.ko.Spec.GatewayIdentifier, b.ko.Spec.GatewayIdentifier)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MetadataConfiguration, b.ko.Spec.MetadataConfiguration) {
		delta.Add("Spec.MetadataConfiguration", a.ko.Spec.MetadataConfiguration, b.ko.Spec.MetadataConfiguration)
	} else if a.ko.Spec.MetadataConfiguration != nil && b.ko.Spec.MetadataConfiguration != nil {
		if len(a.ko.Spec.MetadataConfiguration.AllowedQueryParameters) != len(b.ko.Spec.MetadataConfiguration.AllowedQueryParameters) {
			delta.Add("Spec.MetadataConfiguration.AllowedQueryParameters", a.ko.Spec.MetadataConfiguration.AllowedQueryParameters, b.ko.Spec.MetadataConfiguration.AllowedQueryParameters)
		} else if len(a.ko.Spec.MetadataConfiguration.AllowedQueryParameters) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.MetadataConfiguration.AllowedQueryParameters, b.ko.Spec.MetadataConfiguration.AllowedQueryParameters) {
				delta.Add("Spec.MetadataConfiguration.AllowedQueryParameters", a.ko.Spec.MetadataConfiguration.AllowedQueryParameters, b.ko.Spec.MetadataConfiguration.AllowedQueryParameters)
			}
		}
		if len(a.ko.Spec.MetadataConfiguration.AllowedRequestHeaders) != len(b.ko.Spec.MetadataConfiguration.AllowedRequestHeaders) {
			delta.Add("Spec.MetadataConfiguration.AllowedRequestHeaders", a.ko.Spec.MetadataConfiguration.AllowedRequestHeaders, b.ko.Spec.MetadataConfiguration.AllowedRequestHeaders)
		} else if len(a.ko.Spec.MetadataConfiguration.AllowedRequestHeaders) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.MetadataConfiguration.AllowedRequestHeaders, b.ko.Spec.MetadataConfiguration.AllowedRequestHeaders) {
				delta.Add("Spec.MetadataConfiguration.AllowedRequestHeaders", a.ko.Spec.MetadataConfiguration.AllowedRequestHeaders, b.ko.Spec.MetadataConfiguration.AllowedRequestHeaders)
			}
		}
		if len(a.ko.Spec.MetadataConfiguration.AllowedResponseHeaders) != len(b.ko.Spec.MetadataConfiguration.AllowedResponseHeaders) {
			delta.Add("Spec.MetadataConfiguration.AllowedResponseHeaders", a.ko.Spec.MetadataConfiguration.AllowedResponseHeaders, b.ko.Spec.MetadataConfiguration.AllowedResponseHeaders)
		} else if len(a.ko.Spec.MetadataConfiguration.AllowedResponseHeaders) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.MetadataConfiguration.AllowedResponseHeaders, b.ko.Spec.MetadataConfiguration.AllowedResponseHeaders) {
				delta.Add("Spec.MetadataConfiguration.AllowedResponseHeaders", a.ko.Spec.MetadataConfiguration.AllowedResponseHeaders, b.ko.Spec.MetadataConfiguration.AllowedResponseHeaders)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration, b.ko.Spec.TargetConfiguration) {
		delta.Add("Spec.TargetConfiguration", a.ko.Spec.TargetConfiguration, b.ko.Spec.TargetConfiguration)
	} else if a.ko.Spec.TargetConfiguration != nil && b.ko.Spec.TargetConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp, b.ko.Spec.TargetConfiguration.Mcp) {
			delta.Add("Spec.TargetConfiguration.Mcp", a.ko.Spec.TargetConfiguration.Mcp, b.ko.Spec.TargetConfiguration.Mcp)
		} else if a.ko.Spec.TargetConfiguration.Mcp != nil && b.ko.Spec.TargetConfiguration.Mcp != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.APIGateway, b.ko.Spec.TargetConfiguration.Mcp.APIGateway) {
				delta.Add("Spec.TargetConfiguration.Mcp.APIGateway", a.ko.Spec.TargetConfiguration.Mcp.APIGateway, b.ko.Spec.TargetConfiguration.Mcp.APIGateway)
			} else if a.ko.Spec.TargetConfiguration.Mcp.APIGateway != nil && b.ko.Spec.TargetConfiguration.Mcp.APIGateway != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration) {
					delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration)
				} else if a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration != nil && b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration != nil {
					if len(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters) != len(b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters) {
						delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters)
					} else if len(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters) > 0 {
						if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters) {
							delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolFilters)
						}
					}
					if len(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides) != len(b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides) {
						delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides)
					} else if len(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides) > 0 {
						if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides) {
							delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.APIGatewayToolConfiguration.ToolOverrides)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID) {
					delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID)
				} else if a.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID != nil && b.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID != nil {
					if *a.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID != *b.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID {
						delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.RestAPIID)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage) {
					delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.Stage", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage)
				} else if a.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage != nil && b.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage != nil {
					if *a.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage != *b.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage {
						delta.Add("Spec.TargetConfiguration.Mcp.APIGateway.Stage", a.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage, b.ko.Spec.TargetConfiguration.Mcp.APIGateway.Stage)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.Lambda, b.ko.Spec.TargetConfiguration.Mcp.Lambda) {
				delta.Add("Spec.TargetConfiguration.Mcp.Lambda", a.ko.Spec.TargetConfiguration.Mcp.Lambda, b.ko.Spec.TargetConfiguration.Mcp.Lambda)
			} else if a.ko.Spec.TargetConfiguration.Mcp.Lambda != nil && b.ko.Spec.TargetConfiguration.Mcp.Lambda != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN, b.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN) {
					delta.Add("Spec.TargetConfiguration.Mcp.Lambda.LambdaARN", a.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN, b.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN)
				} else if a.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN != nil && b.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN != nil {
					if *a.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN != *b.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN {
						delta.Add("Spec.TargetConfiguration.Mcp.Lambda.LambdaARN", a.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN, b.ko.Spec.TargetConfiguration.Mcp.Lambda.LambdaARN)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema) {
					delta.Add("Spec.TargetConfiguration.Mcp.Lambda.ToolSchema", a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema)
				} else if a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema != nil && b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema != nil {
					if len(a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload) != len(b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload) {
						delta.Add("Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload", a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload)
					} else if len(a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload) > 0 {
						if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload) {
							delta.Add("Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload", a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.InlinePayload)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3) {
						delta.Add("Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3", a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3)
					} else if a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3 != nil && b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3 != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID) {
							delta.Add("Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID", a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID)
						} else if a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID != nil && b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID != nil {
							if *a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID != *b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID {
								delta.Add("Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID", a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.BucketOwnerAccountID)
							}
						}
						if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI) {
							delta.Add("Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI", a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI)
						} else if a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI != nil && b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI != nil {
							if *a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI != *b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI {
								delta.Add("Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI", a.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.Lambda.ToolSchema.S3.URI)
							}
						}
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.McpServer, b.ko.Spec.TargetConfiguration.Mcp.McpServer) {
				delta.Add("Spec.TargetConfiguration.Mcp.McpServer", a.ko.Spec.TargetConfiguration.Mcp.McpServer, b.ko.Spec.TargetConfiguration.Mcp.McpServer)
			} else if a.ko.Spec.TargetConfiguration.Mcp.McpServer != nil && b.ko.Spec.TargetConfiguration.Mcp.McpServer != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint, b.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint) {
					delta.Add("Spec.TargetConfiguration.Mcp.McpServer.Endpoint", a.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint, b.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint)
				} else if a.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint != nil && b.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint != nil {
					if *a.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint != *b.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint {
						delta.Add("Spec.TargetConfiguration.Mcp.McpServer.Endpoint", a.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint, b.ko.Spec.TargetConfiguration.Mcp.McpServer.Endpoint)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema) {
				delta.Add("Spec.TargetConfiguration.Mcp.OpenAPISchema", a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema)
			} else if a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema != nil && b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload) {
					delta.Add("Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload", a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload)
				} else if a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload != nil && b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload != nil {
					if *a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload != *b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload {
						delta.Add("Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload", a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.InlinePayload)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3) {
					delta.Add("Spec.TargetConfiguration.Mcp.OpenAPISchema.S3", a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3)
				} else if a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3 != nil && b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3 != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID) {
						delta.Add("Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID", a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID)
					} else if a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID != nil && b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID != nil {
						if *a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID != *b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID {
							delta.Add("Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID", a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.BucketOwnerAccountID)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI) {
						delta.Add("Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI", a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI)
					} else if a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI != nil && b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI != nil {
						if *a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI != *b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI {
							delta.Add("Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI", a.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.OpenAPISchema.S3.URI)
						}
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.SmithyModel, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel) {
				delta.Add("Spec.TargetConfiguration.Mcp.SmithyModel", a.ko.Spec.TargetConfiguration.Mcp.SmithyModel, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel)
			} else if a.ko.Spec.TargetConfiguration.Mcp.SmithyModel != nil && b.ko.Spec.TargetConfiguration.Mcp.SmithyModel != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload) {
					delta.Add("Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload", a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload)
				} else if a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload != nil && b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload != nil {
					if *a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload != *b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload {
						delta.Add("Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload", a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.InlinePayload)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3) {
					delta.Add("Spec.TargetConfiguration.Mcp.SmithyModel.S3", a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3)
				} else if a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3 != nil && b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3 != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID) {
						delta.Add("Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID", a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID)
					} else if a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID != nil && b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID != nil {
						if *a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID != *b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID {
							delta.Add("Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID", a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.BucketOwnerAccountID)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI) {
						delta.Add("Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI", a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI)
					} else if a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI != nil && b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI != nil {
						if *a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI != *b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI {
							delta.Add("Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI", a.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI, b.ko.Spec.TargetConfiguration.Mcp.SmithyModel.S3.URI)
						}
					}
				}
			}
		}
	}

	return delta
}
