// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package gateway

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/bedrockagentcorecontrol-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Gateway{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetGatewayOutput
	resp, err = rm.sdkapi.GetGateway(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetGateway", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.AuthorizerConfiguration != nil {
		f0 := &svcapitypes.AuthorizerConfiguration{}
		switch resp.AuthorizerConfiguration.(type) {
		case *svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer:
			f0f0 := resp.AuthorizerConfiguration.(*svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer)
			if f0f0 != nil {
				f0f0f0 := &svcapitypes.CustomJWTAuthorizerConfiguration{}
				if f0f0.Value.AllowedAudience != nil {
					f0f0f0.AllowedAudience = aws.StringSlice(f0f0.Value.AllowedAudience)
				}
				if f0f0.Value.AllowedClients != nil {
					f0f0f0.AllowedClients = aws.StringSlice(f0f0.Value.AllowedClients)
				}
				if f0f0.Value.AllowedScopes != nil {
					f0f0f0.AllowedScopes = aws.StringSlice(f0f0.Value.AllowedScopes)
				}
				if f0f0.Value.CustomClaims != nil {
					f0f0f0f3 := []*svcapitypes.CustomClaimValidationType{}
					for _, f0f0f0f3iter := range f0f0.Value.CustomClaims {
						f0f0f0f3elem := &svcapitypes.CustomClaimValidationType{}
						if f0f0f0f3iter.AuthorizingClaimMatchValue != nil {
							f0f0f0f3elemf0 := &svcapitypes.AuthorizingClaimMatchValueType{}
							if f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator != "" {
								f0f0f0f3elemf0.ClaimMatchOperator = aws.String(string(f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator))
							}
							if f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue != nil {
								f0f0f0f3elemf0f1 := &svcapitypes.ClaimMatchValueType{}
								switch f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(type) {
								case *svcsdktypes.ClaimMatchValueTypeMemberMatchValueString:
									f0f0f0f3elemf0f1f0 := f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(*svcsdktypes.ClaimMatchValueTypeMemberMatchValueString)
									if f0f0f0f3elemf0f1f0 != nil {
										f0f0f0f3elemf0f1.MatchValueString = &f0f0f0f3elemf0f1f0.Value
									}
								case *svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList:
									f0f0f0f3elemf0f1f1 := f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(*svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList)
									if f0f0f0f3elemf0f1f1 != nil {
										f0f0f0f3elemf0f1.MatchValueStringList = aws.StringSlice(f0f0f0f3elemf0f1f1.Value)
									}
								}
								f0f0f0f3elemf0.ClaimMatchValue = f0f0f0f3elemf0f1
							}
							f0f0f0f3elem.AuthorizingClaimMatchValue = f0f0f0f3elemf0
						}
						if f0f0f0f3iter.InboundTokenClaimName != nil {
							f0f0f0f3elem.InboundTokenClaimName = f0f0f0f3iter.InboundTokenClaimName
						}
						if f0f0f0f3iter.InboundTokenClaimValueType != "" {
							f0f0f0f3elem.InboundTokenClaimValueType = aws.String(string(f0f0f0f3iter.InboundTokenClaimValueType))
						}
						f0f0f0f3 = append(f0f0f0f3, f0f0f0f3elem)
					}
					f0f0f0.CustomClaims = f0f0f0f3
				}
				if f0f0.Value.DiscoveryUrl != nil {
					f0f0f0.DiscoveryURL = f0f0.Value.DiscoveryUrl
				}
				f0.CustomJWTAuthorizer = f0f0f0
			}
		}
		ko.Spec.AuthorizerConfiguration = f0
	} else {
		ko.Spec.AuthorizerConfiguration = nil
	}
	if resp.AuthorizerType != "" {
		ko.Spec.AuthorizerType = aws.String(string(resp.AuthorizerType))
	} else {
		ko.Spec.AuthorizerType = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.ExceptionLevel != "" {
		ko.Spec.ExceptionLevel = aws.String(string(resp.ExceptionLevel))
	} else {
		ko.Spec.ExceptionLevel = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.GatewayArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.GatewayArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.GatewayId != nil {
		ko.Status.GatewayID = resp.GatewayId
	} else {
		ko.Status.GatewayID = nil
	}
	if resp.GatewayUrl != nil {
		ko.Status.GatewayURL = resp.GatewayUrl
	} else {
		ko.Status.GatewayURL = nil
	}
	if resp.InterceptorConfigurations != nil {
		f8 := []*svcapitypes.GatewayInterceptorConfiguration{}
		for _, f8iter := range resp.InterceptorConfigurations {
			f8elem := &svcapitypes.GatewayInterceptorConfiguration{}
			if f8iter.InputConfiguration != nil {
				f8elemf0 := &svcapitypes.InterceptorInputConfiguration{}
				if f8iter.InputConfiguration.PassRequestHeaders != nil {
					f8elemf0.PassRequestHeaders = f8iter.InputConfiguration.PassRequestHeaders
				}
				f8elem.InputConfiguration = f8elemf0
			}
			if f8iter.InterceptionPoints != nil {
				f8elemf1 := []*string{}
				for _, f8elemf1iter := range f8iter.InterceptionPoints {
					var f8elemf1elem *string
					f8elemf1elem = aws.String(string(f8elemf1iter))
					f8elemf1 = append(f8elemf1, f8elemf1elem)
				}
				f8elem.InterceptionPoints = f8elemf1
			}
			if f8iter.Interceptor != nil {
				f8elemf2 := &svcapitypes.InterceptorConfiguration{}
				switch f8iter.Interceptor.(type) {
				case *svcsdktypes.InterceptorConfigurationMemberLambda:
					f8elemf2f0 := f8iter.Interceptor.(*svcsdktypes.InterceptorConfigurationMemberLambda)
					if f8elemf2f0 != nil {
						f8elemf2f0f0 := &svcapitypes.LambdaInterceptorConfiguration{}
						if f8elemf2f0.Value.Arn != nil {
							f8elemf2f0f0.ARN = f8elemf2f0.Value.Arn
						}
						f8elemf2.Lambda = f8elemf2f0f0
					}
				}
				f8elem.Interceptor = f8elemf2
			}
			f8 = append(f8, f8elem)
		}
		ko.Spec.InterceptorConfigurations = f8
	} else {
		ko.Spec.InterceptorConfigurations = nil
	}
	if resp.KmsKeyArn != nil {
		ko.Spec.KMSKeyARN = resp.KmsKeyArn
	} else {
		ko.Spec.KMSKeyARN = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.PolicyEngineConfiguration != nil {
		f11 := &svcapitypes.GatewayPolicyEngineConfiguration{}
		if resp.PolicyEngineConfiguration.Arn != nil {
			f11.ARN = resp.PolicyEngineConfiguration.Arn
		}
		if resp.PolicyEngineConfiguration.Mode != "" {
			f11.Mode = aws.String(string(resp.PolicyEngineConfiguration.Mode))
		}
		ko.Spec.PolicyEngineConfiguration = f11
	} else {
		ko.Spec.PolicyEngineConfiguration = nil
	}
	if resp.ProtocolConfiguration != nil {
		f12 := &svcapitypes.GatewayProtocolConfiguration{}
		switch resp.ProtocolConfiguration.(type) {
		case *svcsdktypes.GatewayProtocolConfigurationMemberMcp:
			f12f0 := resp.ProtocolConfiguration.(*svcsdktypes.GatewayProtocolConfigurationMemberMcp)
			if f12f0 != nil {
				f12f0f0 := &svcapitypes.MCPGatewayConfiguration{}
				if f12f0.Value.Instructions != nil {
					f12f0f0.Instructions = f12f0.Value.Instructions
				}
				if f12f0.Value.SearchType != "" {
					f12f0f0.SearchType = aws.String(string(f12f0.Value.SearchType))
				}
				if f12f0.Value.SupportedVersions != nil {
					f12f0f0.SupportedVersions = aws.StringSlice(f12f0.Value.SupportedVersions)
				}
				f12.Mcp = f12f0f0
			}
		}
		ko.Spec.ProtocolConfiguration = f12
	} else {
		ko.Spec.ProtocolConfiguration = nil
	}
	if resp.ProtocolType != "" {
		ko.Spec.ProtocolType = aws.String(string(resp.ProtocolType))
	} else {
		ko.Spec.ProtocolType = nil
	}
	if resp.RoleArn != nil {
		ko.Spec.RoleARN = resp.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.StatusReasons != nil {
		ko.Status.StatusReasons = aws.StringSlice(resp.StatusReasons)
	} else {
		ko.Status.StatusReasons = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}
	if resp.WorkloadIdentityDetails != nil {
		f18 := &svcapitypes.WorkloadIdentityDetails{}
		if resp.WorkloadIdentityDetails.WorkloadIdentityArn != nil {
			f18.WorkloadIdentityARN = resp.WorkloadIdentityDetails.WorkloadIdentityArn
		}
		ko.Status.WorkloadIdentityDetails = f18
	} else {
		ko.Status.WorkloadIdentityDetails = nil
	}

	rm.setStatusDefaults(ko)
	tags, err := rm.getTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN))
	if err != nil {
		return nil, err
	}
	ko.Spec.Tags = tags

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.GatewayID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetGatewayInput, error) {
	res := &svcsdk.GetGatewayInput{}

	if r.ko.Status.GatewayID != nil {
		res.GatewayIdentifier = r.ko.Status.GatewayID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateGatewayOutput
	_ = resp
	resp, err = rm.sdkapi.CreateGateway(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateGateway", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AuthorizerConfiguration != nil {
		f0 := &svcapitypes.AuthorizerConfiguration{}
		switch resp.AuthorizerConfiguration.(type) {
		case *svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer:
			f0f0 := resp.AuthorizerConfiguration.(*svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer)
			if f0f0 != nil {
				f0f0f0 := &svcapitypes.CustomJWTAuthorizerConfiguration{}
				if f0f0.Value.AllowedAudience != nil {
					f0f0f0.AllowedAudience = aws.StringSlice(f0f0.Value.AllowedAudience)
				}
				if f0f0.Value.AllowedClients != nil {
					f0f0f0.AllowedClients = aws.StringSlice(f0f0.Value.AllowedClients)
				}
				if f0f0.Value.AllowedScopes != nil {
					f0f0f0.AllowedScopes = aws.StringSlice(f0f0.Value.AllowedScopes)
				}
				if f0f0.Value.CustomClaims != nil {
					f0f0f0f3 := []*svcapitypes.CustomClaimValidationType{}
					for _, f0f0f0f3iter := range f0f0.Value.CustomClaims {
						f0f0f0f3elem := &svcapitypes.CustomClaimValidationType{}
						if f0f0f0f3iter.AuthorizingClaimMatchValue != nil {
							f0f0f0f3elemf0 := &svcapitypes.AuthorizingClaimMatchValueType{}
							if f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator != "" {
								f0f0f0f3elemf0.ClaimMatchOperator = aws.String(string(f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator))
							}
							if f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue != nil {
								f0f0f0f3elemf0f1 := &svcapitypes.ClaimMatchValueType{}
								switch f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(type) {
								case *svcsdktypes.ClaimMatchValueTypeMemberMatchValueString:
									f0f0f0f3elemf0f1f0 := f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(*svcsdktypes.ClaimMatchValueTypeMemberMatchValueString)
									if f0f0f0f3elemf0f1f0 != nil {
										f0f0f0f3elemf0f1.MatchValueString = &f0f0f0f3elemf0f1f0.Value
									}
								case *svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList:
									f0f0f0f3elemf0f1f1 := f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(*svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList)
									if f0f0f0f3elemf0f1f1 != nil {
										f0f0f0f3elemf0f1.MatchValueStringList = aws.StringSlice(f0f0f0f3elemf0f1f1.Value)
									}
								}
								f0f0f0f3elemf0.ClaimMatchValue = f0f0f0f3elemf0f1
							}
							f0f0f0f3elem.AuthorizingClaimMatchValue = f0f0f0f3elemf0
						}
						if f0f0f0f3iter.InboundTokenClaimName != nil {
							f0f0f0f3elem.InboundTokenClaimName = f0f0f0f3iter.InboundTokenClaimName
						}
						if f0f0f0f3iter.InboundTokenClaimValueType != "" {
							f0f0f0f3elem.InboundTokenClaimValueType = aws.String(string(f0f0f0f3iter.InboundTokenClaimValueType))
						}
						f0f0f0f3 = append(f0f0f0f3, f0f0f0f3elem)
					}
					f0f0f0.CustomClaims = f0f0f0f3
				}
				if f0f0.Value.DiscoveryUrl != nil {
					f0f0f0.DiscoveryURL = f0f0.Value.DiscoveryUrl
				}
				f0.CustomJWTAuthorizer = f0f0f0
			}
		}
		ko.Spec.AuthorizerConfiguration = f0
	} else {
		ko.Spec.AuthorizerConfiguration = nil
	}
	if resp.AuthorizerType != "" {
		ko.Spec.AuthorizerType = aws.String(string(resp.AuthorizerType))
	} else {
		ko.Spec.AuthorizerType = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.ExceptionLevel != "" {
		ko.Spec.ExceptionLevel = aws.String(string(resp.ExceptionLevel))
	} else {
		ko.Spec.ExceptionLevel = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.GatewayArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.GatewayArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.GatewayId != nil {
		ko.Status.GatewayID = resp.GatewayId
	} else {
		ko.Status.GatewayID = nil
	}
	if resp.GatewayUrl != nil {
		ko.Status.GatewayURL = resp.GatewayUrl
	} else {
		ko.Status.GatewayURL = nil
	}
	if resp.InterceptorConfigurations != nil {
		f8 := []*svcapitypes.GatewayInterceptorConfiguration{}
		for _, f8iter := range resp.InterceptorConfigurations {
			f8elem := &svcapitypes.GatewayInterceptorConfiguration{}
			if f8iter.InputConfiguration != nil {
				f8elemf0 := &svcapitypes.InterceptorInputConfiguration{}
				if f8iter.InputConfiguration.PassRequestHeaders != nil {
					f8elemf0.PassRequestHeaders = f8iter.InputConfiguration.PassRequestHeaders
				}
				f8elem.InputConfiguration = f8elemf0
			}
			if f8iter.InterceptionPoints != nil {
				f8elemf1 := []*string{}
				for _, f8elemf1iter := range f8iter.InterceptionPoints {
					var f8elemf1elem *string
					f8elemf1elem = aws.String(string(f8elemf1iter))
					f8elemf1 = append(f8elemf1, f8elemf1elem)
				}
				f8elem.InterceptionPoints = f8elemf1
			}
			if f8iter.Interceptor != nil {
				f8elemf2 := &svcapitypes.InterceptorConfiguration{}
				switch f8iter.Interceptor.(type) {
				case *svcsdktypes.InterceptorConfigurationMemberLambda:
					f8elemf2f0 := f8iter.Interceptor.(*svcsdktypes.InterceptorConfigurationMemberLambda)
					if f8elemf2f0 != nil {
						f8elemf2f0f0 := &svcapitypes.LambdaInterceptorConfiguration{}
						if f8elemf2f0.Value.Arn != nil {
							f8elemf2f0f0.ARN = f8elemf2f0.Value.Arn
						}
						f8elemf2.Lambda = f8elemf2f0f0
					}
				}
				f8elem.Interceptor = f8elemf2
			}
			f8 = append(f8, f8elem)
		}
		ko.Spec.InterceptorConfigurations = f8
	} else {
		ko.Spec.InterceptorConfigurations = nil
	}
	if resp.KmsKeyArn != nil {
		ko.Spec.KMSKeyARN = resp.KmsKeyArn
	} else {
		ko.Spec.KMSKeyARN = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.PolicyEngineConfiguration != nil {
		f11 := &svcapitypes.GatewayPolicyEngineConfiguration{}
		if resp.PolicyEngineConfiguration.Arn != nil {
			f11.ARN = resp.PolicyEngineConfiguration.Arn
		}
		if resp.PolicyEngineConfiguration.Mode != "" {
			f11.Mode = aws.String(string(resp.PolicyEngineConfiguration.Mode))
		}
		ko.Spec.PolicyEngineConfiguration = f11
	} else {
		ko.Spec.PolicyEngineConfiguration = nil
	}
	if resp.ProtocolConfiguration != nil {
		f12 := &svcapitypes.GatewayProtocolConfiguration{}
		switch resp.ProtocolConfiguration.(type) {
		case *svcsdktypes.GatewayProtocolConfigurationMemberMcp:
			f12f0 := resp.ProtocolConfiguration.(*svcsdktypes.GatewayProtocolConfigurationMemberMcp)
			if f12f0 != nil {
				f12f0f0 := &svcapitypes.MCPGatewayConfiguration{}
				if f12f0.Value.Instructions != nil {
					f12f0f0.Instructions = f12f0.Value.Instructions
				}
				if f12f0.Value.SearchType != "" {
					f12f0f0.SearchType = aws.String(string(f12f0.Value.SearchType))
				}
				if f12f0.Value.SupportedVersions != nil {
					f12f0f0.SupportedVersions = aws.StringSlice(f12f0.Value.SupportedVersions)
				}
				f12.Mcp = f12f0f0
			}
		}
		ko.Spec.ProtocolConfiguration = f12
	} else {
		ko.Spec.ProtocolConfiguration = nil
	}
	if resp.ProtocolType != "" {
		ko.Spec.ProtocolType = aws.String(string(resp.ProtocolType))
	} else {
		ko.Spec.ProtocolType = nil
	}
	if resp.RoleArn != nil {
		ko.Spec.RoleARN = resp.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.StatusReasons != nil {
		ko.Status.StatusReasons = aws.StringSlice(resp.StatusReasons)
	} else {
		ko.Status.StatusReasons = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}
	if resp.WorkloadIdentityDetails != nil {
		f18 := &svcapitypes.WorkloadIdentityDetails{}
		if resp.WorkloadIdentityDetails.WorkloadIdentityArn != nil {
			f18.WorkloadIdentityARN = resp.WorkloadIdentityDetails.WorkloadIdentityArn
		}
		ko.Status.WorkloadIdentityDetails = f18
	} else {
		ko.Status.WorkloadIdentityDetails = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Spec.Tags != nil {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateGatewayInput, error) {
	res := &svcsdk.CreateGatewayInput{}

	if r.ko.Spec.AuthorizerConfiguration != nil {
		var f0 svcsdktypes.AuthorizerConfiguration
		isInterfaceSet := false
		if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CustomJWTAuthorizer"))
			}
			f0f0Parent := &svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer{}
			f0f0 := &svcsdktypes.CustomJWTAuthorizerConfiguration{}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedAudience != nil {
				f0f0.AllowedAudience = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedAudience)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedClients != nil {
				f0f0.AllowedClients = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedClients)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedScopes != nil {
				f0f0.AllowedScopes = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedScopes)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.CustomClaims != nil {
				f0f0f3 := []svcsdktypes.CustomClaimValidationType{}
				for _, f0f0f3iter := range r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.CustomClaims {
					f0f0f3elem := &svcsdktypes.CustomClaimValidationType{}
					if f0f0f3iter.AuthorizingClaimMatchValue != nil {
						f0f0f3elemf0 := &svcsdktypes.AuthorizingClaimMatchValueType{}
						if f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator != nil {
							f0f0f3elemf0.ClaimMatchOperator = svcsdktypes.ClaimMatchOperatorType(*f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator)
						}
						if f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue != nil {
							var f0f0f3elemf0f1 svcsdktypes.ClaimMatchValueType
							isInterfaceSet := false
							if f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueString != nil {
								if isInterfaceSet {
									return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MatchValueString"))
								}
								f0f0f3elemf0f1f0Parent := &svcsdktypes.ClaimMatchValueTypeMemberMatchValueString{}
								f0f0f3elemf0f1f0Parent.Value = *f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueString
								f0f0f3elemf0f1 = f0f0f3elemf0f1f0Parent
								isInterfaceSet = true
							}
							if f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueStringList != nil {
								if isInterfaceSet {
									return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MatchValueStringList"))
								}
								f0f0f3elemf0f1f1Parent := &svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList{}
								f0f0f3elemf0f1f1 := []string{}
								f0f0f3elemf0f1f1 = aws.ToStringSlice(f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueStringList)
								f0f0f3elemf0f1f1Parent.Value = f0f0f3elemf0f1f1
								f0f0f3elemf0f1 = f0f0f3elemf0f1f1Parent
								isInterfaceSet = true
							}
							f0f0f3elemf0.ClaimMatchValue = f0f0f3elemf0f1
						}
						f0f0f3elem.AuthorizingClaimMatchValue = f0f0f3elemf0
					}
					if f0f0f3iter.InboundTokenClaimName != nil {
						f0f0f3elem.InboundTokenClaimName = f0f0f3iter.InboundTokenClaimName
					}
					if f0f0f3iter.InboundTokenClaimValueType != nil {
						f0f0f3elem.InboundTokenClaimValueType = svcsdktypes.InboundTokenClaimValueType(*f0f0f3iter.InboundTokenClaimValueType)
					}
					f0f0f3 = append(f0f0f3, *f0f0f3elem)
				}
				f0f0.CustomClaims = f0f0f3
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.DiscoveryURL != nil {
				f0f0.DiscoveryUrl = r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.DiscoveryURL
			}
			f0f0Parent.Value = *f0f0
			f0 = f0f0Parent
			isInterfaceSet = true
		}
		res.AuthorizerConfiguration = f0
	}
	if r.ko.Spec.AuthorizerType != nil {
		res.AuthorizerType = svcsdktypes.AuthorizerType(*r.ko.Spec.AuthorizerType)
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.ExceptionLevel != nil {
		res.ExceptionLevel = svcsdktypes.ExceptionLevel(*r.ko.Spec.ExceptionLevel)
	}
	if r.ko.Spec.InterceptorConfigurations != nil {
		f4 := []svcsdktypes.GatewayInterceptorConfiguration{}
		for _, f4iter := range r.ko.Spec.InterceptorConfigurations {
			f4elem := &svcsdktypes.GatewayInterceptorConfiguration{}
			if f4iter.InputConfiguration != nil {
				f4elemf0 := &svcsdktypes.InterceptorInputConfiguration{}
				if f4iter.InputConfiguration.PassRequestHeaders != nil {
					f4elemf0.PassRequestHeaders = f4iter.InputConfiguration.PassRequestHeaders
				}
				f4elem.InputConfiguration = f4elemf0
			}
			if f4iter.InterceptionPoints != nil {
				f4elemf1 := []svcsdktypes.GatewayInterceptionPoint{}
				for _, f4elemf1iter := range f4iter.InterceptionPoints {
					var f4elemf1elem string
					f4elemf1elem = string(*f4elemf1iter)
					f4elemf1 = append(f4elemf1, svcsdktypes.GatewayInterceptionPoint(f4elemf1elem))
				}
				f4elem.InterceptionPoints = f4elemf1
			}
			if f4iter.Interceptor != nil {
				var f4elemf2 svcsdktypes.InterceptorConfiguration
				isInterfaceSet := false
				if f4iter.Interceptor.Lambda != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Lambda"))
					}
					f4elemf2f0Parent := &svcsdktypes.InterceptorConfigurationMemberLambda{}
					f4elemf2f0 := &svcsdktypes.LambdaInterceptorConfiguration{}
					if f4iter.Interceptor.Lambda.ARN != nil {
						f4elemf2f0.Arn = f4iter.Interceptor.Lambda.ARN
					}
					f4elemf2f0Parent.Value = *f4elemf2f0
					f4elemf2 = f4elemf2f0Parent
					isInterfaceSet = true
				}
				f4elem.Interceptor = f4elemf2
			}
			f4 = append(f4, *f4elem)
		}
		res.InterceptorConfigurations = f4
	}
	if r.ko.Spec.KMSKeyARN != nil {
		res.KmsKeyArn = r.ko.Spec.KMSKeyARN
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.PolicyEngineConfiguration != nil {
		f7 := &svcsdktypes.GatewayPolicyEngineConfiguration{}
		if r.ko.Spec.PolicyEngineConfiguration.ARN != nil {
			f7.Arn = r.ko.Spec.PolicyEngineConfiguration.ARN
		}
		if r.ko.Spec.PolicyEngineConfiguration.Mode != nil {
			f7.Mode = svcsdktypes.GatewayPolicyEngineMode(*r.ko.Spec.PolicyEngineConfiguration.Mode)
		}
		res.PolicyEngineConfiguration = f7
	}
	if r.ko.Spec.ProtocolConfiguration != nil {
		var f8 svcsdktypes.GatewayProtocolConfiguration
		isInterfaceSet := false
		if r.ko.Spec.ProtocolConfiguration.Mcp != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Mcp"))
			}
			f8f0Parent := &svcsdktypes.GatewayProtocolConfigurationMemberMcp{}
			f8f0 := &svcsdktypes.MCPGatewayConfiguration{}
			if r.ko.Spec.ProtocolConfiguration.Mcp.Instructions != nil {
				f8f0.Instructions = r.ko.Spec.ProtocolConfiguration.Mcp.Instructions
			}
			if r.ko.Spec.ProtocolConfiguration.Mcp.SearchType != nil {
				f8f0.SearchType = svcsdktypes.SearchType(*r.ko.Spec.ProtocolConfiguration.Mcp.SearchType)
			}
			if r.ko.Spec.ProtocolConfiguration.Mcp.SupportedVersions != nil {
				f8f0.SupportedVersions = aws.ToStringSlice(r.ko.Spec.ProtocolConfiguration.Mcp.SupportedVersions)
			}
			f8f0Parent.Value = *f8f0
			f8 = f8f0Parent
			isInterfaceSet = true
		}
		res.ProtocolConfiguration = f8
	}
	if r.ko.Spec.ProtocolType != nil {
		res.ProtocolType = svcsdktypes.GatewayProtocolType(*r.ko.Spec.ProtocolType)
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		err := rm.syncTags(
			ctx,
			desired,
			latest,
		)
		if err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}
	if !gatewaySettled(latest) {
		return latest, requeueNotReady
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateGatewayOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateGateway(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateGateway", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AuthorizerConfiguration != nil {
		f0 := &svcapitypes.AuthorizerConfiguration{}
		switch resp.AuthorizerConfiguration.(type) {
		case *svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer:
			f0f0 := resp.AuthorizerConfiguration.(*svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer)
			if f0f0 != nil {
				f0f0f0 := &svcapitypes.CustomJWTAuthorizerConfiguration{}
				if f0f0.Value.AllowedAudience != nil {
					f0f0f0.AllowedAudience = aws.StringSlice(f0f0.Value.AllowedAudience)
				}
				if f0f0.Value.AllowedClients != nil {
					f0f0f0.AllowedClients = aws.StringSlice(f0f0.Value.AllowedClients)
				}
				if f0f0.Value.AllowedScopes != nil {
					f0f0f0.AllowedScopes = aws.StringSlice(f0f0.Value.AllowedScopes)
				}
				if f0f0.Value.CustomClaims != nil {
					f0f0f0f3 := []*svcapitypes.CustomClaimValidationType{}
					for _, f0f0f0f3iter := range f0f0.Value.CustomClaims {
						f0f0f0f3elem := &svcapitypes.CustomClaimValidationType{}
						if f0f0f0f3iter.AuthorizingClaimMatchValue != nil {
							f0f0f0f3elemf0 := &svcapitypes.AuthorizingClaimMatchValueType{}
							if f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator != "" {
								f0f0f0f3elemf0.ClaimMatchOperator = aws.String(string(f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator))
							}
							if f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue != nil {
								f0f0f0f3elemf0f1 := &svcapitypes.ClaimMatchValueType{}
								switch f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(type) {
								case *svcsdktypes.ClaimMatchValueTypeMemberMatchValueString:
									f0f0f0f3elemf0f1f0 := f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(*svcsdktypes.ClaimMatchValueTypeMemberMatchValueString)
									if f0f0f0f3elemf0f1f0 != nil {
										f0f0f0f3elemf0f1.MatchValueString = &f0f0f0f3elemf0f1f0.Value
									}
								case *svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList:
									f0f0f0f3elemf0f1f1 := f0f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(*svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList)
									if f0f0f0f3elemf0f1f1 != nil {
										f0f0f0f3elemf0f1.MatchValueStringList = aws.StringSlice(f0f0f0f3elemf0f1f1.Value)
									}
								}
								f0f0f0f3elemf0.ClaimMatchValue = f0f0f0f3elemf0f1
							}
							f0f0f0f3elem.AuthorizingClaimMatchValue = f0f0f0f3elemf0
						}
						if f0f0f0f3iter.InboundTokenClaimName != nil {
							f0f0f0f3elem.InboundTokenClaimName = f0f0f0f3iter.InboundTokenClaimName
						}
						if f0f0f0f3iter.InboundTokenClaimValueType != "" {
							f0f0f0f3elem.InboundTokenClaimValueType = aws.String(string(f0f0f0f3iter.InboundTokenClaimValueType))
						}
						f0f0f0f3 = append(f0f0f0f3, f0f0f0f3elem)
					}
					f0f0f0.CustomClaims = f0f0f0f3
				}
				if f0f0.Value.DiscoveryUrl != nil {
					f0f0f0.DiscoveryURL = f0f0.Value.DiscoveryUrl
				}
				f0.CustomJWTAuthorizer = f0f0f0
			}
		}
		ko.Spec.AuthorizerConfiguration = f0
	} else {
		ko.Spec.AuthorizerConfiguration = nil
	}
	if resp.AuthorizerType != "" {
		ko.Spec.AuthorizerType = aws.String(string(resp.AuthorizerType))
	} else {
		ko.Spec.AuthorizerType = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.ExceptionLevel != "" {
		ko.Spec.ExceptionLevel = aws.String(string(resp.ExceptionLevel))
	} else {
		ko.Spec.ExceptionLevel = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.GatewayArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.GatewayArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.GatewayId != nil {
		ko.Status.GatewayID = resp.GatewayId
	} else {
		ko.Status.GatewayID = nil
	}
	if resp.GatewayUrl != nil {
		ko.Status.GatewayURL = resp.GatewayUrl
	} else {
		ko.Status.GatewayURL = nil
	}
	if resp.InterceptorConfigurations != nil {
		f8 := []*svcapitypes.GatewayInterceptorConfiguration{}
		for _, f8iter := range resp.InterceptorConfigurations {
			f8elem := &svcapitypes.GatewayInterceptorConfiguration{}
			if f8iter.InputConfiguration != nil {
				f8elemf0 := &svcapitypes.InterceptorInputConfiguration{}
				if f8iter.InputConfiguration.PassRequestHeaders != nil {
					f8elemf0.PassRequestHeaders = f8iter.InputConfiguration.PassRequestHeaders
				}
				f8elem.InputConfiguration = f8elemf0
			}
			if f8iter.InterceptionPoints != nil {
				f8elemf1 := []*string{}
				for _, f8elemf1iter := range f8iter.InterceptionPoints {
					var f8elemf1elem *string
					f8elemf1elem = aws.String(string(f8elemf1iter))
					f8elemf1 = append(f8elemf1, f8elemf1elem)
				}
				f8elem.InterceptionPoints = f8elemf1
			}
			if f8iter.Interceptor != nil {
				f8elemf2 := &svcapitypes.InterceptorConfiguration{}
				switch f8iter.Interceptor.(type) {
				case *svcsdktypes.InterceptorConfigurationMemberLambda:
					f8elemf2f0 := f8iter.Interceptor.(*svcsdktypes.InterceptorConfigurationMemberLambda)
					if f8elemf2f0 != nil {
						f8elemf2f0f0 := &svcapitypes.LambdaInterceptorConfiguration{}
						if f8elemf2f0.Value.Arn != nil {
							f8elemf2f0f0.ARN = f8elemf2f0.Value.Arn
						}
						f8elemf2.Lambda = f8elemf2f0f0
					}
				}
				f8elem.Interceptor = f8elemf2
			}
			f8 = append(f8, f8elem)
		}
		ko.Spec.InterceptorConfigurations = f8
	} else {
		ko.Spec.InterceptorConfigurations = nil
	}
	if resp.KmsKeyArn != nil {
		ko.Spec.KMSKeyARN = resp.KmsKeyArn
	} else {
		ko.Spec.KMSKeyARN = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.PolicyEngineConfiguration != nil {
		f11 := &svcapitypes.GatewayPolicyEngineConfiguration{}
		if resp.PolicyEngineConfiguration.Arn != nil {
			f11.ARN = resp.PolicyEngineConfiguration.Arn
		}
		if resp.PolicyEngineConfiguration.Mode != "" {
			f11.Mode = aws.String(string(resp.PolicyEngineConfiguration.Mode))
		}
		ko.Spec.PolicyEngineConfiguration = f11
	} else {
		ko.Spec.PolicyEngineConfiguration = nil
	}
	if resp.ProtocolConfiguration != nil {
		f12 := &svcapitypes.GatewayProtocolConfiguration{}
		switch resp.ProtocolConfiguration.(type) {
		case *svcsdktypes.GatewayProtocolConfigurationMemberMcp:
			f12f0 := resp.ProtocolConfiguration.(*svcsdktypes.GatewayProtocolConfigurationMemberMcp)
			if f12f0 != nil {
				f12f0f0 := &svcapitypes.MCPGatewayConfiguration{}
				if f12f0.Value.Instructions != nil {
					f12f0f0.Instructions = f12f0.Value.Instructions
				}
				if f12f0.Value.SearchType != "" {
					f12f0f0.SearchType = aws.String(string(f12f0.Value.SearchType))
				}
				if f12f0.Value.SupportedVersions != nil {
					f12f0f0.SupportedVersions = aws.StringSlice(f12f0.Value.SupportedVersions)
				}
				f12.Mcp = f12f0f0
			}
		}
		ko.Spec.ProtocolConfiguration = f12
	} else {
		ko.Spec.ProtocolConfiguration = nil
	}
	if resp.ProtocolType != "" {
		ko.Spec.ProtocolType = aws.String(string(resp.ProtocolType))
	} else {
		ko.Spec.ProtocolType = nil
	}
	if resp.RoleArn != nil {
		ko.Spec.RoleARN = resp.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.StatusReasons != nil {
		ko.Status.StatusReasons = aws.StringSlice(resp.StatusReasons)
	} else {
		ko.Status.StatusReasons = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}
	if resp.WorkloadIdentityDetails != nil {
		f18 := &svcapitypes.WorkloadIdentityDetails{}
		if resp.WorkloadIdentityDetails.WorkloadIdentityArn != nil {
			f18.WorkloadIdentityARN = resp.WorkloadIdentityDetails.WorkloadIdentityArn
		}
		ko.Status.WorkloadIdentityDetails = f18
	} else {
		ko.Status.WorkloadIdentityDetails = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateGatewayInput, error) {
	res := &svcsdk.UpdateGatewayInput{}

	if r.ko.Spec.AuthorizerConfiguration != nil {
		var f0 svcsdktypes.AuthorizerConfiguration
		isInterfaceSet := false
		if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CustomJWTAuthorizer"))
			}
			f0f0Parent := &svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer{}
			f0f0 := &svcsdktypes.CustomJWTAuthorizerConfiguration{}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedAudience != nil {
				f0f0.AllowedAudience = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedAudience)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedClients != nil {
				f0f0.AllowedClients = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedClients)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedScopes != nil {
				f0f0.AllowedScopes = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedScopes)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.CustomClaims != nil {
				f0f0f3 := []svcsdktypes.CustomClaimValidationType{}
				for _, f0f0f3iter := range r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.CustomClaims {
					f0f0f3elem := &svcsdktypes.CustomClaimValidationType{}
					if f0f0f3iter.AuthorizingClaimMatchValue != nil {
						f0f0f3elemf0 := &svcsdktypes.AuthorizingClaimMatchValueType{}
						if f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator != nil {
							f0f0f3elemf0.ClaimMatchOperator = svcsdktypes.ClaimMatchOperatorType(*f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator)
						}
						if f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue != nil {
							var f0f0f3elemf0f1 svcsdktypes.ClaimMatchValueType
							isInterfaceSet := false
							if f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueString != nil {
								if isInterfaceSet {
									return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MatchValueString"))
								}
								f0f0f3elemf0f1f0Parent := &svcsdktypes.ClaimMatchValueTypeMemberMatchValueString{}
								f0f0f3elemf0f1f0Parent.Value = *f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueString
								f0f0f3elemf0f1 = f0f0f3elemf0f1f0Parent
								isInterfaceSet = true
							}
							if f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueStringList != nil {
								if isInterfaceSet {
									return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MatchValueStringList"))
								}
								f0f0f3elemf0f1f1Parent := &svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList{}
								f0f0f3elemf0f1f1 := []string{}
								f0f0f3elemf0f1f1 = aws.ToStringSlice(f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueStringList)
								f0f0f3elemf0f1f1Parent.Value = f0f0f3elemf0f1f1
								f0f0f3elemf0f1 = f0f0f3elemf0f1f1Parent
								isInterfaceSet = true
							}
							f0f0f3elemf0.ClaimMatchValue = f0f0f3elemf0f1
						}
						f0f0f3elem.AuthorizingClaimMatchValue = f0f0f3elemf0
					}
					if f0f0f3iter.InboundTokenClaimName != nil {
						f0f0f3elem.InboundTokenClaimName = f0f0f3iter.InboundTokenClaimName
					}
					if f0f0f3iter.InboundTokenClaimValueType != nil {
						f0f0f3elem.InboundTokenClaimValueType = svcsdktypes.InboundTokenClaimValueType(*f0f0f3iter.InboundTokenClaimValueType)
					}
					f0f0f3 = append(f0f0f3, *f0f0f3elem)
				}
				f0f0.CustomClaims = f0f0f3
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.DiscoveryURL != nil {
				f0f0.DiscoveryUrl = r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.DiscoveryURL
			}
			f0f0Parent.Value = *f0f0
			f0 = f0f0Parent
			isInterfaceSet = true
		}
		res.AuthorizerConfiguration = f0
	}
	if r.ko.Spec.AuthorizerType != nil {
		res.AuthorizerType = svcsdktypes.AuthorizerType(*r.ko.Spec.AuthorizerType)
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.ExceptionLevel != nil {
		res.ExceptionLevel = svcsdktypes.ExceptionLevel(*r.ko.Spec.ExceptionLevel)
	}
	if r.ko.Status.GatewayID != nil {
		res.GatewayIdentifier = r.ko.Status.GatewayID
	}
	if r.ko.Spec.InterceptorConfigurations != nil {
		f5 := []svcsdktypes.GatewayInterceptorConfiguration{}
		for _, f5iter := range r.ko.Spec.InterceptorConfigurations {
			f5elem := &svcsdktypes.GatewayInterceptorConfiguration{}
			if f5iter.InputConfiguration != nil {
				f5elemf0 := &svcsdktypes.InterceptorInputConfiguration{}
				if f5iter.InputConfiguration.PassRequestHeaders != nil {
					f5elemf0.PassRequestHeaders = f5iter.InputConfiguration.PassRequestHeaders
				}
				f5elem.InputConfiguration = f5elemf0
			}
			if f5iter.InterceptionPoints != nil {
				f5elemf1 := []svcsdktypes.GatewayInterceptionPoint{}
				for _, f5elemf1iter := range f5iter.InterceptionPoints {
					var f5elemf1elem string
					f5elemf1elem = string(*f5elemf1iter)
					f5elemf1 = append(f5elemf1, svcsdktypes.GatewayInterceptionPoint(f5elemf1elem))
				}
				f5elem.InterceptionPoints = f5elemf1
			}
			if f5iter.Interceptor != nil {
				var f5elemf2 svcsdktypes.InterceptorConfiguration
				isInterfaceSet := false
				if f5iter.Interceptor.Lambda != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Lambda"))
					}
					f5elemf2f0Parent := &svcsdktypes.InterceptorConfigurationMemberLambda{}
					f5elemf2f0 := &svcsdktypes.LambdaInterceptorConfiguration{}
					if f5iter.Interceptor.Lambda.ARN != nil {
						f5elemf2f0.Arn = f5iter.Interceptor.Lambda.ARN
					}
					f5elemf2f0Parent.Value = *f5elemf2f0
					f5elemf2 = f5elemf2f0Parent
					isInterfaceSet = true
				}
				f5elem.Interceptor = f5elemf2
			}
			f5 = append(f5, *f5elem)
		}
		res.InterceptorConfigurations = f5
	}
	if r.ko.Spec.KMSKeyARN != nil {
		res.KmsKeyArn = r.ko.Spec.KMSKeyARN
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.PolicyEngineConfiguration != nil {
		f8 := &svcsdktypes.GatewayPolicyEngineConfiguration{}
		if r.ko.Spec.PolicyEngineConfiguration.ARN != nil {
			f8.Arn = r.ko.Spec.PolicyEngineConfiguration.ARN
		}
		if r.ko.Spec.PolicyEngineConfiguration.Mode != nil {
			f8.Mode = svcsdktypes.GatewayPolicyEngineMode(*r.ko.Spec.PolicyEngineConfiguration.Mode)
		}
		res.PolicyEngineConfiguration = f8
	}
	if r.ko.Spec.ProtocolConfiguration != nil {
		var f9 svcsdktypes.GatewayProtocolConfiguration
		isInterfaceSet := false
		if r.ko.Spec.ProtocolConfiguration.Mcp != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Mcp"))
			}
			f9f0Parent := &svcsdktypes.GatewayProtocolConfigurationMemberMcp{}
			f9f0 := &svcsdktypes.MCPGatewayConfiguration{}
			if r.ko.Spec.ProtocolConfiguration.Mcp.Instructions != nil {
				f9f0.Instructions = r.ko.Spec.ProtocolConfiguration.Mcp.Instructions
			}
			if r.ko.Spec.ProtocolConfiguration.Mcp.SearchType != nil {
				f9f0.SearchType = svcsdktypes.SearchType(*r.ko.Spec.ProtocolConfiguration.Mcp.SearchType)
			}
			if r.ko.Spec.ProtocolConfiguration.Mcp.SupportedVersions != nil {
				f9f0.SupportedVersions = aws.ToStringSlice(r.ko.Spec.ProtocolConfiguration.Mcp.SupportedVersions)
			}
			f9f0Parent.Value = *f9f0
			f9 = f9f0Parent
			isInterfaceSet = true
		}
		res.ProtocolConfiguration = f9
	}
	if r.ko.Spec.ProtocolType != nil {
		res.ProtocolType = svcsdktypes.GatewayProtocolType(*r.ko.Spec.ProtocolType)
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if !gatewaySettled(r) {
		return nil, requeueNotReady
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteGatewayOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteGateway(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteGateway", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteGatewayInput, error) {
	res := &svcsdk.DeleteGatewayInput{}

	if r.ko.Status.GatewayID != nil {
		res.GatewayIdentifier = r.ko.Status.GatewayID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Gateway,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
