---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ack-bedrockagentcorecontrol-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apigateway.services.k8s.aws
  resources:
  - restapis
  - restapis/status
  verbs:
  - get
  - list
- apiGroups:
  - bedrockagentcorecontrol.services.k8s.aws
  resources:
  - agentruntimeendpoints
  - agentruntimes
  - apikeycredentialproviders
  - browserprofiles
  - browsers
  - codeinterpreters
  - gateways
  - gatewaytargets
  - harnesses
  - memories
  - policies
  - policyengines
  - workloadidentities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bedrockagentcorecontrol.services.k8s.aws
  resources:
  - agentruntimeendpoints/status
  - agentruntimes/status
  - apikeycredentialproviders/status
  - browserprofiles/status
  - browsers/status
  - codeinterpreters/status
  - gateways/status
  - gatewaytargets/status
  - harnesses/status
  - memories/status
  - policies/status
  - policyengines/status
  - workloadidentities/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - securitygroups
  - securitygroups/status
  - subnets
  - subnets/status
  verbs:
  - get
  - list
- apiGroups:
  - iam.services.k8s.aws
  resources:
  - roles
  - roles/status
  verbs:
  - get
  - list
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - keys
  - keys/status
  verbs:
  - get
  - list
- apiGroups:
  - secretsmanager.services.k8s.aws
  resources:
  - secrets
  - secrets/status
  verbs:
  - get
  - list
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  - iamroleselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  - iamroleselectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sns.services.k8s.aws
  resources:
  - topics
  - topics/status
  verbs:
  - get
  - list
