// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package agent_runtime

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/bedrockagentcorecontrol-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.AgentRuntime{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetAgentRuntimeOutput
	resp, err = rm.sdkapi.GetAgentRuntime(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetAgentRuntime", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AgentRuntimeArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AgentRuntimeArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.AgentRuntimeArtifact != nil {
		f1 := &svcapitypes.AgentRuntimeArtifact{}
		switch resp.AgentRuntimeArtifact.(type) {
		case *svcsdktypes.AgentRuntimeArtifactMemberCodeConfiguration:
			f1f0 := resp.AgentRuntimeArtifact.(*svcsdktypes.AgentRuntimeArtifactMemberCodeConfiguration)
			if f1f0 != nil {
				f1f0f0 := &svcapitypes.CodeConfiguration{}
				if f1f0.Value.Code != nil {
					f1f0f0f0 := &svcapitypes.Code{}
					switch f1f0.Value.Code.(type) {
					case *svcsdktypes.CodeMemberS3:
						f1f0f0f0f0 := f1f0.Value.Code.(*svcsdktypes.CodeMemberS3)
						if f1f0f0f0f0 != nil {
							f1f0f0f0f0f0 := &svcapitypes.S3Location{}
							if f1f0f0f0f0.Value.Bucket != nil {
								f1f0f0f0f0f0.Bucket = f1f0f0f0f0.Value.Bucket
							}
							if f1f0f0f0f0.Value.Prefix != nil {
								f1f0f0f0f0f0.Prefix = f1f0f0f0f0.Value.Prefix
							}
							if f1f0f0f0f0.Value.VersionId != nil {
								f1f0f0f0f0f0.VersionID = f1f0f0f0f0.Value.VersionId
							}
							f1f0f0f0.S3 = f1f0f0f0f0f0
						}
					}
					f1f0f0.Code = f1f0f0f0
				}
				if f1f0.Value.EntryPoint != nil {
					f1f0f0.EntryPoint = aws.StringSlice(f1f0.Value.EntryPoint)
				}
				if f1f0.Value.Runtime != "" {
					f1f0f0.Runtime = aws.String(string(f1f0.Value.Runtime))
				}
				f1.CodeConfiguration = f1f0f0
			}
		case *svcsdktypes.AgentRuntimeArtifactMemberContainerConfiguration:
			f1f1 := resp.AgentRuntimeArtifact.(*svcsdktypes.AgentRuntimeArtifactMemberContainerConfiguration)
			if f1f1 != nil {
				f1f1f1 := &svcapitypes.ContainerConfiguration{}
				if f1f1.Value.ContainerUri != nil {
					f1f1f1.ContainerURI = f1f1.Value.ContainerUri
				}
				f1.ContainerConfiguration = f1f1f1
			}
		}
		ko.Spec.AgentRuntimeArtifact = f1
	} else {
		ko.Spec.AgentRuntimeArtifact = nil
	}
	if resp.AgentRuntimeId != nil {
		ko.Status.AgentRuntimeID = resp.AgentRuntimeId
	} else {
		ko.Status.AgentRuntimeID = nil
	}
	if resp.AgentRuntimeName != nil {
		ko.Spec.AgentRuntimeName = resp.AgentRuntimeName
	} else {
		ko.Spec.AgentRuntimeName = nil
	}
	if resp.AgentRuntimeVersion != nil {
		ko.Status.AgentRuntimeVersion = resp.AgentRuntimeVersion
	} else {
		ko.Status.AgentRuntimeVersion = nil
	}
	if resp.AuthorizerConfiguration != nil {
		f5 := &svcapitypes.AuthorizerConfiguration{}
		switch resp.AuthorizerConfiguration.(type) {
		case *svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer:
			f5f0 := resp.AuthorizerConfiguration.(*svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer)
			if f5f0 != nil {
				f5f0f0 := &svcapitypes.CustomJWTAuthorizerConfiguration{}
				if f5f0.Value.AllowedAudience != nil {
					f5f0f0.AllowedAudience = aws.StringSlice(f5f0.Value.AllowedAudience)
				}
				if f5f0.Value.AllowedClients != nil {
					f5f0f0.AllowedClients = aws.StringSlice(f5f0.Value.AllowedClients)
				}
				if f5f0.Value.AllowedScopes != nil {
					f5f0f0.AllowedScopes = aws.StringSlice(f5f0.Value.AllowedScopes)
				}
				if f5f0.Value.CustomClaims != nil {
					f5f0f0f3 := []*svcapitypes.CustomClaimValidationType{}
					for _, f5f0f0f3iter := range f5f0.Value.CustomClaims {
						f5f0f0f3elem := &svcapitypes.CustomClaimValidationType{}
						if f5f0f0f3iter.AuthorizingClaimMatchValue != nil {
							f5f0f0f3elemf0 := &svcapitypes.AuthorizingClaimMatchValueType{}
							if f5f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator != "" {
								f5f0f0f3elemf0.ClaimMatchOperator = aws.String(string(f5f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator))
							}
							if f5f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue != nil {
								f5f0f0f3elemf0f1 := &svcapitypes.ClaimMatchValueType{}
								switch f5f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(type) {
								case *svcsdktypes.ClaimMatchValueTypeMemberMatchValueString:
									f5f0f0f3elemf0f1f0 := f5f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(*svcsdktypes.ClaimMatchValueTypeMemberMatchValueString)
									if f5f0f0f3elemf0f1f0 != nil {
										f5f0f0f3elemf0f1.MatchValueString = &f5f0f0f3elemf0f1f0.Value
									}
								case *svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList:
									f5f0f0f3elemf0f1f1 := f5f0f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.(*svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList)
									if f5f0f0f3elemf0f1f1 != nil {
										f5f0f0f3elemf0f1.MatchValueStringList = aws.StringSlice(f5f0f0f3elemf0f1f1.Value)
									}
								}
								f5f0f0f3elemf0.ClaimMatchValue = f5f0f0f3elemf0f1
							}
							f5f0f0f3elem.AuthorizingClaimMatchValue = f5f0f0f3elemf0
						}
						if f5f0f0f3iter.InboundTokenClaimName != nil {
							f5f0f0f3elem.InboundTokenClaimName = f5f0f0f3iter.InboundTokenClaimName
						}
						if f5f0f0f3iter.InboundTokenClaimValueType != "" {
							f5f0f0f3elem.InboundTokenClaimValueType = aws.String(string(f5f0f0f3iter.InboundTokenClaimValueType))
						}
						f5f0f0f3 = append(f5f0f0f3, f5f0f0f3elem)
					}
					f5f0f0.CustomClaims = f5f0f0f3
				}
				if f5f0.Value.DiscoveryUrl != nil {
					f5f0f0.DiscoveryURL = f5f0.Value.DiscoveryUrl
				}
				f5.CustomJWTAuthorizer = f5f0f0
			}
		}
		ko.Spec.AuthorizerConfiguration = f5
	} else {
		ko.Spec.AuthorizerConfiguration = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.EnvironmentVariables != nil {
		ko.Spec.EnvironmentVariables = aws.StringMap(resp.EnvironmentVariables)
	} else {
		ko.Spec.EnvironmentVariables = nil
	}
	if resp.LifecycleConfiguration != nil {
		f11 := &svcapitypes.LifecycleConfiguration{}
		if resp.LifecycleConfiguration.IdleRuntimeSessionTimeout != nil {
			idleRuntimeSessionTimeoutCopy := int64(*resp.LifecycleConfiguration.IdleRuntimeSessionTimeout)
			f11.IdleRuntimeSessionTimeout = &idleRuntimeSessionTimeoutCopy
		}
		if resp.LifecycleConfiguration.MaxLifetime != nil {
			maxLifetimeCopy := int64(*resp.LifecycleConfiguration.MaxLifetime)
			f11.MaxLifetime = &maxLifetimeCopy
		}
		ko.Spec.LifecycleConfiguration = f11
	} else {
		ko.Spec.LifecycleConfiguration = nil
	}
	if resp.NetworkConfiguration != nil {
		f12 := &svcapitypes.NetworkConfiguration{}
		if resp.NetworkConfiguration.NetworkMode != "" {
			f12.NetworkMode = aws.String(string(resp.NetworkConfiguration.NetworkMode))
		}
		if resp.NetworkConfiguration.NetworkModeConfig != nil {
			f12f1 := &svcapitypes.VPCConfig{}
			if resp.NetworkConfiguration.NetworkModeConfig.SecurityGroups != nil {
				f12f1.SecurityGroups = aws.StringSlice(resp.NetworkConfiguration.NetworkModeConfig.SecurityGroups)
			}
			if resp.NetworkConfiguration.NetworkModeConfig.Subnets != nil {
				f12f1.Subnets = aws.StringSlice(resp.NetworkConfiguration.NetworkModeConfig.Subnets)
			}
			f12.NetworkModeConfig = f12f1
		}
		ko.Spec.NetworkConfiguration = f12
	} else {
		ko.Spec.NetworkConfiguration = nil
	}
	if resp.ProtocolConfiguration != nil {
		f13 := &svcapitypes.ProtocolConfiguration{}
		if resp.ProtocolConfiguration.ServerProtocol != "" {
			f13.ServerProtocol = aws.String(string(resp.ProtocolConfiguration.ServerProtocol))
		}
		ko.Spec.ProtocolConfiguration = f13
	} else {
		ko.Spec.ProtocolConfiguration = nil
	}
	if resp.RequestHeaderConfiguration != nil {
		f14 := &svcapitypes.RequestHeaderConfiguration{}
		switch resp.RequestHeaderConfiguration.(type) {
		case *svcsdktypes.RequestHeaderConfigurationMemberRequestHeaderAllowlist:
			f14f0 := resp.RequestHeaderConfiguration.(*svcsdktypes.RequestHeaderConfigurationMemberRequestHeaderAllowlist)
			if f14f0 != nil {
				f14.RequestHeaderAllowlist = aws.StringSlice(f14f0.Value)
			}
		}
		ko.Spec.RequestHeaderConfiguration = f14
	} else {
		ko.Spec.RequestHeaderConfiguration = nil
	}
	if resp.RoleArn != nil {
		ko.Spec.RoleARN = resp.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.WorkloadIdentityDetails != nil {
		f17 := &svcapitypes.WorkloadIdentityDetails{}
		if resp.WorkloadIdentityDetails.WorkloadIdentityArn != nil {
			f17.WorkloadIdentityARN = resp.WorkloadIdentityDetails.WorkloadIdentityArn
		}
		ko.Status.WorkloadIdentityDetails = f17
	} else {
		ko.Status.WorkloadIdentityDetails = nil
	}

	rm.setStatusDefaults(ko)
	if !agentRuntimeReady(&resource{ko}) {
		return nil, requeueNotReady
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.AgentRuntimeID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetAgentRuntimeInput, error) {
	res := &svcsdk.GetAgentRuntimeInput{}

	if r.ko.Status.AgentRuntimeID != nil {
		res.AgentRuntimeId = r.ko.Status.AgentRuntimeID
	}
	if r.ko.Status.AgentRuntimeVersion != nil {
		res.AgentRuntimeVersion = r.ko.Status.AgentRuntimeVersion
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateAgentRuntimeOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAgentRuntime(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAgentRuntime", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AgentRuntimeArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AgentRuntimeArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.AgentRuntimeId != nil {
		ko.Status.AgentRuntimeID = resp.AgentRuntimeId
	} else {
		ko.Status.AgentRuntimeID = nil
	}
	if resp.AgentRuntimeVersion != nil {
		ko.Status.AgentRuntimeVersion = resp.AgentRuntimeVersion
	} else {
		ko.Status.AgentRuntimeVersion = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.WorkloadIdentityDetails != nil {
		f5 := &svcapitypes.WorkloadIdentityDetails{}
		if resp.WorkloadIdentityDetails.WorkloadIdentityArn != nil {
			f5.WorkloadIdentityARN = resp.WorkloadIdentityDetails.WorkloadIdentityArn
		}
		ko.Status.WorkloadIdentityDetails = f5
	} else {
		ko.Status.WorkloadIdentityDetails = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAgentRuntimeInput, error) {
	res := &svcsdk.CreateAgentRuntimeInput{}

	if r.ko.Spec.AgentRuntimeArtifact != nil {
		var f0 svcsdktypes.AgentRuntimeArtifact
		isInterfaceSet := false
		if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CodeConfiguration"))
			}
			f0f0Parent := &svcsdktypes.AgentRuntimeArtifactMemberCodeConfiguration{}
			f0f0 := &svcsdktypes.CodeConfiguration{}
			if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code != nil {
				var f0f0f0 svcsdktypes.Code
				isInterfaceSet := false
				if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3 != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
					}
					f0f0f0f0Parent := &svcsdktypes.CodeMemberS3{}
					f0f0f0f0 := &svcsdktypes.S3Location{}
					if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.Bucket != nil {
						f0f0f0f0.Bucket = r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.Bucket
					}
					if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.Prefix != nil {
						f0f0f0f0.Prefix = r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.Prefix
					}
					if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.VersionID != nil {
						f0f0f0f0.VersionId = r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.VersionID
					}
					f0f0f0f0Parent.Value = *f0f0f0f0
					f0f0f0 = f0f0f0f0Parent
					isInterfaceSet = true
				}
				f0f0.Code = f0f0f0
			}
			if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.EntryPoint != nil {
				f0f0.EntryPoint = aws.ToStringSlice(r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.EntryPoint)
			}
			if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Runtime != nil {
				f0f0.Runtime = svcsdktypes.AgentManagedRuntimeType(*r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Runtime)
			}
			f0f0Parent.Value = *f0f0
			f0 = f0f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.AgentRuntimeArtifact.ContainerConfiguration != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ContainerConfiguration"))
			}
			f0f1Parent := &svcsdktypes.AgentRuntimeArtifactMemberContainerConfiguration{}
			f0f1 := &svcsdktypes.ContainerConfiguration{}
			if r.ko.Spec.AgentRuntimeArtifact.ContainerConfiguration.ContainerURI != nil {
				f0f1.ContainerUri = r.ko.Spec.AgentRuntimeArtifact.ContainerConfiguration.ContainerURI
			}
			f0f1Parent.Value = *f0f1
			f0 = f0f1Parent
			isInterfaceSet = true
		}
		res.AgentRuntimeArtifact = f0
	}
	if r.ko.Spec.AgentRuntimeName != nil {
		res.AgentRuntimeName = r.ko.Spec.AgentRuntimeName
	}
	if r.ko.Spec.AuthorizerConfiguration != nil {
		var f2 svcsdktypes.AuthorizerConfiguration
		isInterfaceSet := false
		if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CustomJWTAuthorizer"))
			}
			f2f0Parent := &svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer{}
			f2f0 := &svcsdktypes.CustomJWTAuthorizerConfiguration{}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedAudience != nil {
				f2f0.AllowedAudience = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedAudience)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedClients != nil {
				f2f0.AllowedClients = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedClients)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedScopes != nil {
				f2f0.AllowedScopes = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedScopes)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.CustomClaims != nil {
				f2f0f3 := []svcsdktypes.CustomClaimValidationType{}
				for _, f2f0f3iter := range r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.CustomClaims {
					f2f0f3elem := &svcsdktypes.CustomClaimValidationType{}
					if f2f0f3iter.AuthorizingClaimMatchValue != nil {
						f2f0f3elemf0 := &svcsdktypes.AuthorizingClaimMatchValueType{}
						if f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator != nil {
							f2f0f3elemf0.ClaimMatchOperator = svcsdktypes.ClaimMatchOperatorType(*f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator)
						}
						if f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue != nil {
							var f2f0f3elemf0f1 svcsdktypes.ClaimMatchValueType
							isInterfaceSet := false
							if f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueString != nil {
								if isInterfaceSet {
									return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MatchValueString"))
								}
								f2f0f3elemf0f1f0Parent := &svcsdktypes.ClaimMatchValueTypeMemberMatchValueString{}
								f2f0f3elemf0f1f0Parent.Value = *f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueString
								f2f0f3elemf0f1 = f2f0f3elemf0f1f0Parent
								isInterfaceSet = true
							}
							if f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueStringList != nil {
								if isInterfaceSet {
									return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MatchValueStringList"))
								}
								f2f0f3elemf0f1f1Parent := &svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList{}
								f2f0f3elemf0f1f1 := []string{}
								f2f0f3elemf0f1f1 = aws.ToStringSlice(f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueStringList)
								f2f0f3elemf0f1f1Parent.Value = f2f0f3elemf0f1f1
								f2f0f3elemf0f1 = f2f0f3elemf0f1f1Parent
								isInterfaceSet = true
							}
							f2f0f3elemf0.ClaimMatchValue = f2f0f3elemf0f1
						}
						f2f0f3elem.AuthorizingClaimMatchValue = f2f0f3elemf0
					}
					if f2f0f3iter.InboundTokenClaimName != nil {
						f2f0f3elem.InboundTokenClaimName = f2f0f3iter.InboundTokenClaimName
					}
					if f2f0f3iter.InboundTokenClaimValueType != nil {
						f2f0f3elem.InboundTokenClaimValueType = svcsdktypes.InboundTokenClaimValueType(*f2f0f3iter.InboundTokenClaimValueType)
					}
					f2f0f3 = append(f2f0f3, *f2f0f3elem)
				}
				f2f0.CustomClaims = f2f0f3
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.DiscoveryURL != nil {
				f2f0.DiscoveryUrl = r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.DiscoveryURL
			}
			f2f0Parent.Value = *f2f0
			f2 = f2f0Parent
			isInterfaceSet = true
		}
		res.AuthorizerConfiguration = f2
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EnvironmentVariables != nil {
		res.EnvironmentVariables = aws.ToStringMap(r.ko.Spec.EnvironmentVariables)
	}
	if r.ko.Spec.LifecycleConfiguration != nil {
		f5 := &svcsdktypes.LifecycleConfiguration{}
		if r.ko.Spec.LifecycleConfiguration.IdleRuntimeSessionTimeout != nil {
			idleRuntimeSessionTimeoutCopy0 := *r.ko.Spec.LifecycleConfiguration.IdleRuntimeSessionTimeout
			if idleRuntimeSessionTimeoutCopy0 > math.MaxInt32 || idleRuntimeSessionTimeoutCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field idleRuntimeSessionTimeout is of type int32")
			}
			idleRuntimeSessionTimeoutCopy := int32(idleRuntimeSessionTimeoutCopy0)
			f5.IdleRuntimeSessionTimeout = &idleRuntimeSessionTimeoutCopy
		}
		if r.ko.Spec.LifecycleConfiguration.MaxLifetime != nil {
			maxLifetimeCopy0 := *r.ko.Spec.LifecycleConfiguration.MaxLifetime
			if maxLifetimeCopy0 > math.MaxInt32 || maxLifetimeCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field maxLifetime is of type int32")
			}
			maxLifetimeCopy := int32(maxLifetimeCopy0)
			f5.MaxLifetime = &maxLifetimeCopy
		}
		res.LifecycleConfiguration = f5
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f6 := &svcsdktypes.NetworkConfiguration{}
		if r.ko.Spec.NetworkConfiguration.NetworkMode != nil {
			f6.NetworkMode = svcsdktypes.NetworkMode(*r.ko.Spec.NetworkConfiguration.NetworkMode)
		}
		if r.ko.Spec.NetworkConfiguration.NetworkModeConfig != nil {
			f6f1 := &svcsdktypes.VpcConfig{}
			if r.ko.Spec.NetworkConfiguration.NetworkModeConfig.SecurityGroups != nil {
				f6f1.SecurityGroups = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.NetworkModeConfig.SecurityGroups)
			}
			if r.ko.Spec.NetworkConfiguration.NetworkModeConfig.Subnets != nil {
				f6f1.Subnets = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.NetworkModeConfig.Subnets)
			}
			f6.NetworkModeConfig = f6f1
		}
		res.NetworkConfiguration = f6
	}
	if r.ko.Spec.ProtocolConfiguration != nil {
		f7 := &svcsdktypes.ProtocolConfiguration{}
		if r.ko.Spec.ProtocolConfiguration.ServerProtocol != nil {
			f7.ServerProtocol = svcsdktypes.ServerProtocol(*r.ko.Spec.ProtocolConfiguration.ServerProtocol)
		}
		res.ProtocolConfiguration = f7
	}
	if r.ko.Spec.RequestHeaderConfiguration != nil {
		var f8 svcsdktypes.RequestHeaderConfiguration
		isInterfaceSet := false
		if r.ko.Spec.RequestHeaderConfiguration.RequestHeaderAllowlist != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for RequestHeaderAllowlist"))
			}
			f8f0Parent := &svcsdktypes.RequestHeaderConfigurationMemberRequestHeaderAllowlist{}
			f8f0 := []string{}
			f8f0 = aws.ToStringSlice(r.ko.Spec.RequestHeaderConfiguration.RequestHeaderAllowlist)
			f8f0Parent.Value = f8f0
			f8 = f8f0Parent
			isInterfaceSet = true
		}
		res.RequestHeaderConfiguration = f8
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		err := syncTags(
			ctx, rm.sdkapi, rm.metrics,
			string(*latest.ko.Status.ACKResourceMetadata.ARN),
			aws.ToStringMap(desired.ko.Spec.Tags), aws.ToStringMap(latest.ko.Spec.Tags),
		)
		if err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}
	if !agentRuntimeReady(latest) {
		return latest, requeueNotReady
	}
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateAgentRuntimeOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateAgentRuntime(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateAgentRuntime", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AgentRuntimeArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AgentRuntimeArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.AgentRuntimeId != nil {
		ko.Status.AgentRuntimeID = resp.AgentRuntimeId
	} else {
		ko.Status.AgentRuntimeID = nil
	}
	if resp.AgentRuntimeVersion != nil {
		ko.Status.AgentRuntimeVersion = resp.AgentRuntimeVersion
	} else {
		ko.Status.AgentRuntimeVersion = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.WorkloadIdentityDetails != nil {
		f6 := &svcapitypes.WorkloadIdentityDetails{}
		if resp.WorkloadIdentityDetails.WorkloadIdentityArn != nil {
			f6.WorkloadIdentityARN = resp.WorkloadIdentityDetails.WorkloadIdentityArn
		}
		ko.Status.WorkloadIdentityDetails = f6
	} else {
		ko.Status.WorkloadIdentityDetails = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateAgentRuntimeInput, error) {
	res := &svcsdk.UpdateAgentRuntimeInput{}

	if r.ko.Spec.AgentRuntimeArtifact != nil {
		var f0 svcsdktypes.AgentRuntimeArtifact
		isInterfaceSet := false
		if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CodeConfiguration"))
			}
			f0f0Parent := &svcsdktypes.AgentRuntimeArtifactMemberCodeConfiguration{}
			f0f0 := &svcsdktypes.CodeConfiguration{}
			if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code != nil {
				var f0f0f0 svcsdktypes.Code
				isInterfaceSet := false
				if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3 != nil {
					if isInterfaceSet {
						return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for S3"))
					}
					f0f0f0f0Parent := &svcsdktypes.CodeMemberS3{}
					f0f0f0f0 := &svcsdktypes.S3Location{}
					if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.Bucket != nil {
						f0f0f0f0.Bucket = r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.Bucket
					}
					if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.Prefix != nil {
						f0f0f0f0.Prefix = r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.Prefix
					}
					if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.VersionID != nil {
						f0f0f0f0.VersionId = r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Code.S3.VersionID
					}
					f0f0f0f0Parent.Value = *f0f0f0f0
					f0f0f0 = f0f0f0f0Parent
					isInterfaceSet = true
				}
				f0f0.Code = f0f0f0
			}
			if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.EntryPoint != nil {
				f0f0.EntryPoint = aws.ToStringSlice(r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.EntryPoint)
			}
			if r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Runtime != nil {
				f0f0.Runtime = svcsdktypes.AgentManagedRuntimeType(*r.ko.Spec.AgentRuntimeArtifact.CodeConfiguration.Runtime)
			}
			f0f0Parent.Value = *f0f0
			f0 = f0f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.AgentRuntimeArtifact.ContainerConfiguration != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ContainerConfiguration"))
			}
			f0f1Parent := &svcsdktypes.AgentRuntimeArtifactMemberContainerConfiguration{}
			f0f1 := &svcsdktypes.ContainerConfiguration{}
			if r.ko.Spec.AgentRuntimeArtifact.ContainerConfiguration.ContainerURI != nil {
				f0f1.ContainerUri = r.ko.Spec.AgentRuntimeArtifact.ContainerConfiguration.ContainerURI
			}
			f0f1Parent.Value = *f0f1
			f0 = f0f1Parent
			isInterfaceSet = true
		}
		res.AgentRuntimeArtifact = f0
	}
	if r.ko.Status.AgentRuntimeID != nil {
		res.AgentRuntimeId = r.ko.Status.AgentRuntimeID
	}
	if r.ko.Spec.AuthorizerConfiguration != nil {
		var f2 svcsdktypes.AuthorizerConfiguration
		isInterfaceSet := false
		if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CustomJWTAuthorizer"))
			}
			f2f0Parent := &svcsdktypes.AuthorizerConfigurationMemberCustomJWTAuthorizer{}
			f2f0 := &svcsdktypes.CustomJWTAuthorizerConfiguration{}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedAudience != nil {
				f2f0.AllowedAudience = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedAudience)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedClients != nil {
				f2f0.AllowedClients = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedClients)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedScopes != nil {
				f2f0.AllowedScopes = aws.ToStringSlice(r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.AllowedScopes)
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.CustomClaims != nil {
				f2f0f3 := []svcsdktypes.CustomClaimValidationType{}
				for _, f2f0f3iter := range r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.CustomClaims {
					f2f0f3elem := &svcsdktypes.CustomClaimValidationType{}
					if f2f0f3iter.AuthorizingClaimMatchValue != nil {
						f2f0f3elemf0 := &svcsdktypes.AuthorizingClaimMatchValueType{}
						if f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator != nil {
							f2f0f3elemf0.ClaimMatchOperator = svcsdktypes.ClaimMatchOperatorType(*f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchOperator)
						}
						if f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue != nil {
							var f2f0f3elemf0f1 svcsdktypes.ClaimMatchValueType
							isInterfaceSet := false
							if f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueString != nil {
								if isInterfaceSet {
									return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MatchValueString"))
								}
								f2f0f3elemf0f1f0Parent := &svcsdktypes.ClaimMatchValueTypeMemberMatchValueString{}
								f2f0f3elemf0f1f0Parent.Value = *f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueString
								f2f0f3elemf0f1 = f2f0f3elemf0f1f0Parent
								isInterfaceSet = true
							}
							if f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueStringList != nil {
								if isInterfaceSet {
									return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for MatchValueStringList"))
								}
								f2f0f3elemf0f1f1Parent := &svcsdktypes.ClaimMatchValueTypeMemberMatchValueStringList{}
								f2f0f3elemf0f1f1 := []string{}
								f2f0f3elemf0f1f1 = aws.ToStringSlice(f2f0f3iter.AuthorizingClaimMatchValue.ClaimMatchValue.MatchValueStringList)
								f2f0f3elemf0f1f1Parent.Value = f2f0f3elemf0f1f1
								f2f0f3elemf0f1 = f2f0f3elemf0f1f1Parent
								isInterfaceSet = true
							}
							f2f0f3elemf0.ClaimMatchValue = f2f0f3elemf0f1
						}
						f2f0f3elem.AuthorizingClaimMatchValue = f2f0f3elemf0
					}
					if f2f0f3iter.InboundTokenClaimName != nil {
						f2f0f3elem.InboundTokenClaimName = f2f0f3iter.InboundTokenClaimName
					}
					if f2f0f3iter.InboundTokenClaimValueType != nil {
						f2f0f3elem.InboundTokenClaimValueType = svcsdktypes.InboundTokenClaimValueType(*f2f0f3iter.InboundTokenClaimValueType)
					}
					f2f0f3 = append(f2f0f3, *f2f0f3elem)
				}
				f2f0.CustomClaims = f2f0f3
			}
			if r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.DiscoveryURL != nil {
				f2f0.DiscoveryUrl = r.ko.Spec.AuthorizerConfiguration.CustomJWTAuthorizer.DiscoveryURL
			}
			f2f0Parent.Value = *f2f0
			f2 = f2f0Parent
			isInterfaceSet = true
		}
		res.AuthorizerConfiguration = f2
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EnvironmentVariables != nil {
		res.EnvironmentVariables = aws.ToStringMap(r.ko.Spec.EnvironmentVariables)
	}
	if r.ko.Spec.LifecycleConfiguration != nil {
		f6 := &svcsdktypes.LifecycleConfiguration{}
		if r.ko.Spec.LifecycleConfiguration.IdleRuntimeSessionTimeout != nil {
			idleRuntimeSessionTimeoutCopy0 := *r.ko.Spec.LifecycleConfiguration.IdleRuntimeSessionTimeout
			if idleRuntimeSessionTimeoutCopy0 > math.MaxInt32 || idleRuntimeSessionTimeoutCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field idleRuntimeSessionTimeout is of type int32")
			}
			idleRuntimeSessionTimeoutCopy := int32(idleRuntimeSessionTimeoutCopy0)
			f6.IdleRuntimeSessionTimeout = &idleRuntimeSessionTimeoutCopy
		}
		if r.ko.Spec.LifecycleConfiguration.MaxLifetime != nil {
			maxLifetimeCopy0 := *r.ko.Spec.LifecycleConfiguration.MaxLifetime
			if maxLifetimeCopy0 > math.MaxInt32 || maxLifetimeCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field maxLifetime is of type int32")
			}
			maxLifetimeCopy := int32(maxLifetimeCopy0)
			f6.MaxLifetime = &maxLifetimeCopy
		}
		res.LifecycleConfiguration = f6
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f7 := &svcsdktypes.NetworkConfiguration{}
		if r.ko.Spec.NetworkConfiguration.NetworkMode != nil {
			f7.NetworkMode = svcsdktypes.NetworkMode(*r.ko.Spec.NetworkConfiguration.NetworkMode)
		}
		if r.ko.Spec.NetworkConfiguration.NetworkModeConfig != nil {
			f7f1 := &svcsdktypes.VpcConfig{}
			if r.ko.Spec.NetworkConfiguration.NetworkModeConfig.SecurityGroups != nil {
				f7f1.SecurityGroups = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.NetworkModeConfig.SecurityGroups)
			}
			if r.ko.Spec.NetworkConfiguration.NetworkModeConfig.Subnets != nil {
				f7f1.Subnets = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.NetworkModeConfig.Subnets)
			}
			f7.NetworkModeConfig = f7f1
		}
		res.NetworkConfiguration = f7
	}
	if r.ko.Spec.ProtocolConfiguration != nil {
		f8 := &svcsdktypes.ProtocolConfiguration{}
		if r.ko.Spec.ProtocolConfiguration.ServerProtocol != nil {
			f8.ServerProtocol = svcsdktypes.ServerProtocol(*r.ko.Spec.ProtocolConfiguration.ServerProtocol)
		}
		res.ProtocolConfiguration = f8
	}
	if r.ko.Spec.RequestHeaderConfiguration != nil {
		var f9 svcsdktypes.RequestHeaderConfiguration
		isInterfaceSet := false
		if r.ko.Spec.RequestHeaderConfiguration.RequestHeaderAllowlist != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for RequestHeaderAllowlist"))
			}
			f9f0Parent := &svcsdktypes.RequestHeaderConfigurationMemberRequestHeaderAllowlist{}
			f9f0 := []string{}
			f9f0 = aws.ToStringSlice(r.ko.Spec.RequestHeaderConfiguration.RequestHeaderAllowlist)
			f9f0Parent.Value = f9f0
			f9 = f9f0Parent
			isInterfaceSet = true
		}
		res.RequestHeaderConfiguration = f9
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAgentRuntimeOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAgentRuntime(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAgentRuntime", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAgentRuntimeInput, error) {
	res := &svcsdk.DeleteAgentRuntimeInput{}

	if r.ko.Status.AgentRuntimeID != nil {
		res.AgentRuntimeId = r.ko.Status.AgentRuntimeID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.AgentRuntime,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
