apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/bedrockagentcorecontrol.services.k8s.aws_apikeycredentialproviders.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_agentruntimes.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_agentruntimeendpoints.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_browsers.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_browserprofiles.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_codeinterpreters.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_gateways.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_gatewaytargets.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_harnesses.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_memories.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_policies.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_policyengines.yaml
  - bases/bedrockagentcorecontrol.services.k8s.aws_workloadidentities.yaml
