// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type APIKeyCredentialLocation string

const (
	APIKeyCredentialLocation_HEADER          APIKeyCredentialLocation = "HEADER"
	APIKeyCredentialLocation_QUERY_PARAMETER APIKeyCredentialLocation = "QUERY_PARAMETER"
)

type ActorTokenContentType string

const (
	ActorTokenContentType_AWS_IAM_ID_TOKEN_JWT ActorTokenContentType = "AWS_IAM_ID_TOKEN_JWT"
	ActorTokenContentType_M2M                  ActorTokenContentType = "M2M"
	ActorTokenContentType_NONE                 ActorTokenContentType = "NONE"
)

type AgentManagedRuntimeType string

const (
	AgentManagedRuntimeType_NODE_22     AgentManagedRuntimeType = "NODE_22"
	AgentManagedRuntimeType_PYTHON_3_10 AgentManagedRuntimeType = "PYTHON_3_10"
	AgentManagedRuntimeType_PYTHON_3_11 AgentManagedRuntimeType = "PYTHON_3_11"
	AgentManagedRuntimeType_PYTHON_3_12 AgentManagedRuntimeType = "PYTHON_3_12"
	AgentManagedRuntimeType_PYTHON_3_13 AgentManagedRuntimeType = "PYTHON_3_13"
	AgentManagedRuntimeType_PYTHON_3_14 AgentManagedRuntimeType = "PYTHON_3_14"
)

type AgentRuntimeEndpointStatus_SDK string

const (
	AgentRuntimeEndpointStatus_SDK_CREATE_FAILED AgentRuntimeEndpointStatus_SDK = "CREATE_FAILED"
	AgentRuntimeEndpointStatus_SDK_CREATING      AgentRuntimeEndpointStatus_SDK = "CREATING"
	AgentRuntimeEndpointStatus_SDK_DELETING      AgentRuntimeEndpointStatus_SDK = "DELETING"
	AgentRuntimeEndpointStatus_SDK_READY         AgentRuntimeEndpointStatus_SDK = "READY"
	AgentRuntimeEndpointStatus_SDK_UPDATE_FAILED AgentRuntimeEndpointStatus_SDK = "UPDATE_FAILED"
	AgentRuntimeEndpointStatus_SDK_UPDATING      AgentRuntimeEndpointStatus_SDK = "UPDATING"
)

type AgentRuntimeStatus_SDK string

const (
	AgentRuntimeStatus_SDK_CREATE_FAILED AgentRuntimeStatus_SDK = "CREATE_FAILED"
	AgentRuntimeStatus_SDK_CREATING      AgentRuntimeStatus_SDK = "CREATING"
	AgentRuntimeStatus_SDK_DELETING      AgentRuntimeStatus_SDK = "DELETING"
	AgentRuntimeStatus_SDK_READY         AgentRuntimeStatus_SDK = "READY"
	AgentRuntimeStatus_SDK_UPDATE_FAILED AgentRuntimeStatus_SDK = "UPDATE_FAILED"
	AgentRuntimeStatus_SDK_UPDATING      AgentRuntimeStatus_SDK = "UPDATING"
)

type AuthorizerType string

const (
	AuthorizerType_AUTHENTICATE_ONLY AuthorizerType = "AUTHENTICATE_ONLY"
	AuthorizerType_AWS_IAM           AuthorizerType = "AWS_IAM"
	AuthorizerType_CUSTOM_JWT        AuthorizerType = "CUSTOM_JWT"
	AuthorizerType_NONE              AuthorizerType = "NONE"
)

type BrowserEnterprisePolicyType string

const (
	BrowserEnterprisePolicyType_MANAGED     BrowserEnterprisePolicyType = "MANAGED"
	BrowserEnterprisePolicyType_RECOMMENDED BrowserEnterprisePolicyType = "RECOMMENDED"
)

type BrowserNetworkMode string

const (
	BrowserNetworkMode_PUBLIC BrowserNetworkMode = "PUBLIC"
	BrowserNetworkMode_VPC    BrowserNetworkMode = "VPC"
)

type BrowserProfileStatus_SDK string

const (
	BrowserProfileStatus_SDK_DELETED  BrowserProfileStatus_SDK = "DELETED"
	BrowserProfileStatus_SDK_DELETING BrowserProfileStatus_SDK = "DELETING"
	BrowserProfileStatus_SDK_READY    BrowserProfileStatus_SDK = "READY"
	BrowserProfileStatus_SDK_SAVING   BrowserProfileStatus_SDK = "SAVING"
)

type BrowserStatus_SDK string

const (
	BrowserStatus_SDK_CREATE_FAILED BrowserStatus_SDK = "CREATE_FAILED"
	BrowserStatus_SDK_CREATING      BrowserStatus_SDK = "CREATING"
	BrowserStatus_SDK_DELETED       BrowserStatus_SDK = "DELETED"
	BrowserStatus_SDK_DELETE_FAILED BrowserStatus_SDK = "DELETE_FAILED"
	BrowserStatus_SDK_DELETING      BrowserStatus_SDK = "DELETING"
	BrowserStatus_SDK_READY         BrowserStatus_SDK = "READY"
)

type ClaimMatchOperatorType string

const (
	ClaimMatchOperatorType_CONTAINS     ClaimMatchOperatorType = "CONTAINS"
	ClaimMatchOperatorType_CONTAINS_ANY ClaimMatchOperatorType = "CONTAINS_ANY"
	ClaimMatchOperatorType_EQUALS       ClaimMatchOperatorType = "EQUALS"
)

type ClientAuthenticationMethodType string

const (
	ClientAuthenticationMethodType_AWS_IAM_ID_TOKEN_JWT ClientAuthenticationMethodType = "AWS_IAM_ID_TOKEN_JWT"
	ClientAuthenticationMethodType_CLIENT_SECRET_BASIC  ClientAuthenticationMethodType = "CLIENT_SECRET_BASIC"
	ClientAuthenticationMethodType_CLIENT_SECRET_POST   ClientAuthenticationMethodType = "CLIENT_SECRET_POST"
)

type ClusteringFrequency string

const (
	ClusteringFrequency_DAILY   ClusteringFrequency = "DAILY"
	ClusteringFrequency_MONTHLY ClusteringFrequency = "MONTHLY"
	ClusteringFrequency_WEEKLY  ClusteringFrequency = "WEEKLY"
)

type CodeInterpreterNetworkMode string

const (
	CodeInterpreterNetworkMode_PUBLIC  CodeInterpreterNetworkMode = "PUBLIC"
	CodeInterpreterNetworkMode_SANDBOX CodeInterpreterNetworkMode = "SANDBOX"
	CodeInterpreterNetworkMode_VPC     CodeInterpreterNetworkMode = "VPC"
)

type CodeInterpreterStatus_SDK string

const (
	CodeInterpreterStatus_SDK_CREATE_FAILED CodeInterpreterStatus_SDK = "CREATE_FAILED"
	CodeInterpreterStatus_SDK_CREATING      CodeInterpreterStatus_SDK = "CREATING"
	CodeInterpreterStatus_SDK_DELETED       CodeInterpreterStatus_SDK = "DELETED"
	CodeInterpreterStatus_SDK_DELETE_FAILED CodeInterpreterStatus_SDK = "DELETE_FAILED"
	CodeInterpreterStatus_SDK_DELETING      CodeInterpreterStatus_SDK = "DELETING"
	CodeInterpreterStatus_SDK_READY         CodeInterpreterStatus_SDK = "READY"
)

type ConfigurationBundleStatus string

const (
	ConfigurationBundleStatus_ACTIVE        ConfigurationBundleStatus = "ACTIVE"
	ConfigurationBundleStatus_CREATE_FAILED ConfigurationBundleStatus = "CREATE_FAILED"
	ConfigurationBundleStatus_CREATING      ConfigurationBundleStatus = "CREATING"
	ConfigurationBundleStatus_DELETE_FAILED ConfigurationBundleStatus = "DELETE_FAILED"
	ConfigurationBundleStatus_DELETING      ConfigurationBundleStatus = "DELETING"
	ConfigurationBundleStatus_UPDATE_FAILED ConfigurationBundleStatus = "UPDATE_FAILED"
	ConfigurationBundleStatus_UPDATING      ConfigurationBundleStatus = "UPDATING"
)

type ContentLevel string

const (
	ContentLevel_FULL_CONTENT  ContentLevel = "FULL_CONTENT"
	ContentLevel_METADATA_ONLY ContentLevel = "METADATA_ONLY"
)

type ContentType string

const (
	ContentType_MEMORY_RECORDS ContentType = "MEMORY_RECORDS"
)

type CredentialProviderType string

const (
	CredentialProviderType_API_KEY                CredentialProviderType = "API_KEY"
	CredentialProviderType_CALLER_IAM_CREDENTIALS CredentialProviderType = "CALLER_IAM_CREDENTIALS"
	CredentialProviderType_GATEWAY_IAM_ROLE       CredentialProviderType = "GATEWAY_IAM_ROLE"
	CredentialProviderType_JWT_PASSTHROUGH        CredentialProviderType = "JWT_PASSTHROUGH"
	CredentialProviderType_OAUTH                  CredentialProviderType = "OAUTH"
)

type CredentialProviderVendorType string

const (
	CredentialProviderVendorType_AtlassianOauth2  CredentialProviderVendorType = "AtlassianOauth2"
	CredentialProviderVendorType_Auth0Oauth2      CredentialProviderVendorType = "Auth0Oauth2"
	CredentialProviderVendorType_CognitoOauth2    CredentialProviderVendorType = "CognitoOauth2"
	CredentialProviderVendorType_CustomOauth2     CredentialProviderVendorType = "CustomOauth2"
	CredentialProviderVendorType_CyberArkOauth2   CredentialProviderVendorType = "CyberArkOauth2"
	CredentialProviderVendorType_DropboxOauth2    CredentialProviderVendorType = "DropboxOauth2"
	CredentialProviderVendorType_FacebookOauth2   CredentialProviderVendorType = "FacebookOauth2"
	CredentialProviderVendorType_FusionAuthOauth2 CredentialProviderVendorType = "FusionAuthOauth2"
	CredentialProviderVendorType_GithubOauth2     CredentialProviderVendorType = "GithubOauth2"
	CredentialProviderVendorType_GoogleOauth2     CredentialProviderVendorType = "GoogleOauth2"
	CredentialProviderVendorType_HubspotOauth2    CredentialProviderVendorType = "HubspotOauth2"
	CredentialProviderVendorType_LinkedinOauth2   CredentialProviderVendorType = "LinkedinOauth2"
	CredentialProviderVendorType_MicrosoftOauth2  CredentialProviderVendorType = "MicrosoftOauth2"
	CredentialProviderVendorType_NotionOauth2     CredentialProviderVendorType = "NotionOauth2"
	CredentialProviderVendorType_OktaOauth2       CredentialProviderVendorType = "OktaOauth2"
	CredentialProviderVendorType_OneLoginOauth2   CredentialProviderVendorType = "OneLoginOauth2"
	CredentialProviderVendorType_PingOneOauth2    CredentialProviderVendorType = "PingOneOauth2"
	CredentialProviderVendorType_RedditOauth2     CredentialProviderVendorType = "RedditOauth2"
	CredentialProviderVendorType_SalesforceOauth2 CredentialProviderVendorType = "SalesforceOauth2"
	CredentialProviderVendorType_SlackOauth2      CredentialProviderVendorType = "SlackOauth2"
	CredentialProviderVendorType_SpotifyOauth2    CredentialProviderVendorType = "SpotifyOauth2"
	CredentialProviderVendorType_TwitchOauth2     CredentialProviderVendorType = "TwitchOauth2"
	CredentialProviderVendorType_XOauth2          CredentialProviderVendorType = "XOauth2"
	CredentialProviderVendorType_YandexOauth2     CredentialProviderVendorType = "YandexOauth2"
	CredentialProviderVendorType_ZoomOauth2       CredentialProviderVendorType = "ZoomOauth2"
)

type DatasetSchemaType string

const (
	DatasetSchemaType_AGENTCORE_EVALUATION_PREDEFINED_V1 DatasetSchemaType = "AGENTCORE_EVALUATION_PREDEFINED_V1"
	DatasetSchemaType_AGENTCORE_EVALUATION_SIMULATED_V1  DatasetSchemaType = "AGENTCORE_EVALUATION_SIMULATED_V1"
)

type DatasetStatus string

const (
	DatasetStatus_ACTIVE        DatasetStatus = "ACTIVE"
	DatasetStatus_CREATE_FAILED DatasetStatus = "CREATE_FAILED"
	DatasetStatus_CREATING      DatasetStatus = "CREATING"
	DatasetStatus_DELETE_FAILED DatasetStatus = "DELETE_FAILED"
	DatasetStatus_DELETING      DatasetStatus = "DELETING"
	DatasetStatus_UPDATE_FAILED DatasetStatus = "UPDATE_FAILED"
	DatasetStatus_UPDATING      DatasetStatus = "UPDATING"
)

type DescriptorType string

const (
	DescriptorType_A2A          DescriptorType = "A2A"
	DescriptorType_AGENT_SKILLS DescriptorType = "AGENT_SKILLS"
	DescriptorType_CUSTOM       DescriptorType = "CUSTOM"
	DescriptorType_MCP          DescriptorType = "MCP"
)

type DraftStatus string

const (
	DraftStatus_MODIFIED   DraftStatus = "MODIFIED"
	DraftStatus_UNMODIFIED DraftStatus = "UNMODIFIED"
)

type EndpointIPAddressType string

const (
	EndpointIPAddressType_IPV4 EndpointIPAddressType = "IPV4"
	EndpointIPAddressType_IPV6 EndpointIPAddressType = "IPV6"
)

type EnforcementMode string

const (
	EnforcementMode_ACTIVE   EnforcementMode = "ACTIVE"
	EnforcementMode_LOG_ONLY EnforcementMode = "LOG_ONLY"
)

type EvaluatorLevel string

const (
	EvaluatorLevel_SESSION   EvaluatorLevel = "SESSION"
	EvaluatorLevel_TOOL_CALL EvaluatorLevel = "TOOL_CALL"
	EvaluatorLevel_TRACE     EvaluatorLevel = "TRACE"
)

type EvaluatorStatus string

const (
	EvaluatorStatus_ACTIVE        EvaluatorStatus = "ACTIVE"
	EvaluatorStatus_CREATE_FAILED EvaluatorStatus = "CREATE_FAILED"
	EvaluatorStatus_CREATING      EvaluatorStatus = "CREATING"
	EvaluatorStatus_DELETING      EvaluatorStatus = "DELETING"
	EvaluatorStatus_UPDATE_FAILED EvaluatorStatus = "UPDATE_FAILED"
	EvaluatorStatus_UPDATING      EvaluatorStatus = "UPDATING"
)

type EvaluatorType string

const (
	EvaluatorType_Builtin    EvaluatorType = "Builtin"
	EvaluatorType_Custom     EvaluatorType = "Custom"
	EvaluatorType_CustomCode EvaluatorType = "CustomCode"
)

type ExceptionLevel string

const (
	ExceptionLevel_DEBUG ExceptionLevel = "DEBUG"
)

type ExtractionType string

const (
	ExtractionType_LLM_INFERRED        ExtractionType = "LLM_INFERRED"
	ExtractionType_STRICTLY_CONSISTENT ExtractionType = "STRICTLY_CONSISTENT"
)

type FilterOperator string

const (
	FilterOperator_Contains           FilterOperator = "Contains"
	FilterOperator_Equals             FilterOperator = "Equals"
	FilterOperator_GreaterThan        FilterOperator = "GreaterThan"
	FilterOperator_GreaterThanOrEqual FilterOperator = "GreaterThanOrEqual"
	FilterOperator_LessThan           FilterOperator = "LessThan"
	FilterOperator_LessThanOrEqual    FilterOperator = "LessThanOrEqual"
	FilterOperator_NotContains        FilterOperator = "NotContains"
	FilterOperator_NotEquals          FilterOperator = "NotEquals"
)

type FindingType string

const (
	FindingType_ALLOW_ALL        FindingType = "ALLOW_ALL"
	FindingType_ALLOW_NONE       FindingType = "ALLOW_NONE"
	FindingType_DENY_ALL         FindingType = "DENY_ALL"
	FindingType_DENY_NONE        FindingType = "DENY_NONE"
	FindingType_INVALID          FindingType = "INVALID"
	FindingType_NOT_TRANSLATABLE FindingType = "NOT_TRANSLATABLE"
	FindingType_VALID            FindingType = "VALID"
)

type GatewayInterceptionPoint string

const (
	GatewayInterceptionPoint_REQUEST  GatewayInterceptionPoint = "REQUEST"
	GatewayInterceptionPoint_RESPONSE GatewayInterceptionPoint = "RESPONSE"
)

type GatewayPolicyEngineMode string

const (
	GatewayPolicyEngineMode_ENFORCE  GatewayPolicyEngineMode = "ENFORCE"
	GatewayPolicyEngineMode_LOG_ONLY GatewayPolicyEngineMode = "LOG_ONLY"
)

type GatewayProtocolType string

const (
	GatewayProtocolType_MCP GatewayProtocolType = "MCP"
)

type GatewayRuleStatus string

const (
	GatewayRuleStatus_ACTIVE   GatewayRuleStatus = "ACTIVE"
	GatewayRuleStatus_CREATING GatewayRuleStatus = "CREATING"
	GatewayRuleStatus_DELETING GatewayRuleStatus = "DELETING"
	GatewayRuleStatus_UPDATING GatewayRuleStatus = "UPDATING"
)

type GatewayStatus_SDK string

const (
	GatewayStatus_SDK_CREATING            GatewayStatus_SDK = "CREATING"
	GatewayStatus_SDK_DELETING            GatewayStatus_SDK = "DELETING"
	GatewayStatus_SDK_FAILED              GatewayStatus_SDK = "FAILED"
	GatewayStatus_SDK_READY               GatewayStatus_SDK = "READY"
	GatewayStatus_SDK_UPDATE_UNSUCCESSFUL GatewayStatus_SDK = "UPDATE_UNSUCCESSFUL"
	GatewayStatus_SDK_UPDATING            GatewayStatus_SDK = "UPDATING"
)

type HarnessBedrockAPIFormat string

const (
	HarnessBedrockAPIFormat_chat_completions HarnessBedrockAPIFormat = "chat_completions"
	HarnessBedrockAPIFormat_converse_stream  HarnessBedrockAPIFormat = "converse_stream"
	HarnessBedrockAPIFormat_responses        HarnessBedrockAPIFormat = "responses"
)

type HarnessEndpointStatus string

const (
	HarnessEndpointStatus_CREATE_FAILED HarnessEndpointStatus = "CREATE_FAILED"
	HarnessEndpointStatus_CREATING      HarnessEndpointStatus = "CREATING"
	HarnessEndpointStatus_DELETE_FAILED HarnessEndpointStatus = "DELETE_FAILED"
	HarnessEndpointStatus_DELETING      HarnessEndpointStatus = "DELETING"
	HarnessEndpointStatus_READY         HarnessEndpointStatus = "READY"
	HarnessEndpointStatus_UPDATE_FAILED HarnessEndpointStatus = "UPDATE_FAILED"
	HarnessEndpointStatus_UPDATING      HarnessEndpointStatus = "UPDATING"
)

type HarnessManagedMemoryStrategyType string

const (
	HarnessManagedMemoryStrategyType_EPISODIC        HarnessManagedMemoryStrategyType = "EPISODIC"
	HarnessManagedMemoryStrategyType_SEMANTIC        HarnessManagedMemoryStrategyType = "SEMANTIC"
	HarnessManagedMemoryStrategyType_SUMMARIZATION   HarnessManagedMemoryStrategyType = "SUMMARIZATION"
	HarnessManagedMemoryStrategyType_USER_PREFERENCE HarnessManagedMemoryStrategyType = "USER_PREFERENCE"
)

type HarnessOpenAiAPIFormat string

const (
	HarnessOpenAiAPIFormat_chat_completions HarnessOpenAiAPIFormat = "chat_completions"
	HarnessOpenAiAPIFormat_responses        HarnessOpenAiAPIFormat = "responses"
)

type HarnessStatus_SDK string

const (
	HarnessStatus_SDK_CREATE_FAILED HarnessStatus_SDK = "CREATE_FAILED"
	HarnessStatus_SDK_CREATING      HarnessStatus_SDK = "CREATING"
	HarnessStatus_SDK_DELETE_FAILED HarnessStatus_SDK = "DELETE_FAILED"
	HarnessStatus_SDK_DELETING      HarnessStatus_SDK = "DELETING"
	HarnessStatus_SDK_READY         HarnessStatus_SDK = "READY"
	HarnessStatus_SDK_UPDATE_FAILED HarnessStatus_SDK = "UPDATE_FAILED"
	HarnessStatus_SDK_UPDATING      HarnessStatus_SDK = "UPDATING"
)

type HarnessToolType string

const (
	HarnessToolType_agentcore_browser          HarnessToolType = "agentcore_browser"
	HarnessToolType_agentcore_code_interpreter HarnessToolType = "agentcore_code_interpreter"
	HarnessToolType_agentcore_gateway          HarnessToolType = "agentcore_gateway"
	HarnessToolType_inline_function            HarnessToolType = "inline_function"
	HarnessToolType_remote_mcp                 HarnessToolType = "remote_mcp"
)

type HarnessTruncationStrategy string

const (
	HarnessTruncationStrategy_none           HarnessTruncationStrategy = "none"
	HarnessTruncationStrategy_sliding_window HarnessTruncationStrategy = "sliding_window"
	HarnessTruncationStrategy_summarization  HarnessTruncationStrategy = "summarization"
)

type InboundTokenClaimValueType string

const (
	InboundTokenClaimValueType_STRING       InboundTokenClaimValueType = "STRING"
	InboundTokenClaimValueType_STRING_ARRAY InboundTokenClaimValueType = "STRING_ARRAY"
)

type IncludedData string

const (
	IncludedData_ALL_DATA      IncludedData = "ALL_DATA"
	IncludedData_METADATA_ONLY IncludedData = "METADATA_ONLY"
)

type InterceptorPayloadExclusion string

const (
	InterceptorPayloadExclusion_RESPONSE_BODY InterceptorPayloadExclusion = "RESPONSE_BODY"
)

type KeyType string

const (
	KeyType_CustomerManagedKey KeyType = "CustomerManagedKey"
	KeyType_ServiceManagedKey  KeyType = "ServiceManagedKey"
)

type ListingMode string

const (
	ListingMode_DEFAULT ListingMode = "DEFAULT"
	ListingMode_DYNAMIC ListingMode = "DYNAMIC"
)

type MemoryStatus_SDK string

const (
	MemoryStatus_SDK_ACTIVE   MemoryStatus_SDK = "ACTIVE"
	MemoryStatus_SDK_CREATING MemoryStatus_SDK = "CREATING"
	MemoryStatus_SDK_DELETING MemoryStatus_SDK = "DELETING"
	MemoryStatus_SDK_FAILED   MemoryStatus_SDK = "FAILED"
	MemoryStatus_SDK_UPDATING MemoryStatus_SDK = "UPDATING"
)

type MemoryStrategyStatus string

const (
	MemoryStrategyStatus_ACTIVE   MemoryStrategyStatus = "ACTIVE"
	MemoryStrategyStatus_CREATING MemoryStrategyStatus = "CREATING"
	MemoryStrategyStatus_DELETING MemoryStrategyStatus = "DELETING"
	MemoryStrategyStatus_FAILED   MemoryStrategyStatus = "FAILED"
)

type MemoryStrategyType string

const (
	MemoryStrategyType_CUSTOM          MemoryStrategyType = "CUSTOM"
	MemoryStrategyType_EPISODIC        MemoryStrategyType = "EPISODIC"
	MemoryStrategyType_SEMANTIC        MemoryStrategyType = "SEMANTIC"
	MemoryStrategyType_SUMMARIZATION   MemoryStrategyType = "SUMMARIZATION"
	MemoryStrategyType_USER_PREFERENCE MemoryStrategyType = "USER_PREFERENCE"
)

type MemoryView string

const (
	MemoryView_full               MemoryView = "full"
	MemoryView_without_decryption MemoryView = "without_decryption"
)

type MetadataValueType string

const (
	MetadataValueType_NUMBER     MetadataValueType = "NUMBER"
	MetadataValueType_STRING     MetadataValueType = "STRING"
	MetadataValueType_STRINGLIST MetadataValueType = "STRINGLIST"
)

type NetworkMode string

const (
	NetworkMode_PUBLIC NetworkMode = "PUBLIC"
	NetworkMode_VPC    NetworkMode = "VPC"
)

type OAuthGrantType string

const (
	OAuthGrantType_AUTHORIZATION_CODE OAuthGrantType = "AUTHORIZATION_CODE"
	OAuthGrantType_CLIENT_CREDENTIALS OAuthGrantType = "CLIENT_CREDENTIALS"
	OAuthGrantType_TOKEN_EXCHANGE     OAuthGrantType = "TOKEN_EXCHANGE"
)

type OnBehalfOfTokenExchangeGrantTypeType string

const (
	OnBehalfOfTokenExchangeGrantTypeType_JWT_AUTHORIZATION_GRANT OnBehalfOfTokenExchangeGrantTypeType = "JWT_AUTHORIZATION_GRANT"
	OnBehalfOfTokenExchangeGrantTypeType_TOKEN_EXCHANGE          OnBehalfOfTokenExchangeGrantTypeType = "TOKEN_EXCHANGE"
)

type OnlineEvaluationConfigStatus string

const (
	OnlineEvaluationConfigStatus_ACTIVE        OnlineEvaluationConfigStatus = "ACTIVE"
	OnlineEvaluationConfigStatus_CREATE_FAILED OnlineEvaluationConfigStatus = "CREATE_FAILED"
	OnlineEvaluationConfigStatus_CREATING      OnlineEvaluationConfigStatus = "CREATING"
	OnlineEvaluationConfigStatus_DELETING      OnlineEvaluationConfigStatus = "DELETING"
	OnlineEvaluationConfigStatus_ERROR         OnlineEvaluationConfigStatus = "ERROR"
	OnlineEvaluationConfigStatus_UPDATE_FAILED OnlineEvaluationConfigStatus = "UPDATE_FAILED"
	OnlineEvaluationConfigStatus_UPDATING      OnlineEvaluationConfigStatus = "UPDATING"
)

type OnlineEvaluationExecutionStatus string

const (
	OnlineEvaluationExecutionStatus_DISABLED OnlineEvaluationExecutionStatus = "DISABLED"
	OnlineEvaluationExecutionStatus_ENABLED  OnlineEvaluationExecutionStatus = "ENABLED"
)

type OverrideType string

const (
	OverrideType_EPISODIC_OVERRIDE        OverrideType = "EPISODIC_OVERRIDE"
	OverrideType_SELF_MANAGED             OverrideType = "SELF_MANAGED"
	OverrideType_SEMANTIC_OVERRIDE        OverrideType = "SEMANTIC_OVERRIDE"
	OverrideType_SUMMARY_OVERRIDE         OverrideType = "SUMMARY_OVERRIDE"
	OverrideType_USER_PREFERENCE_OVERRIDE OverrideType = "USER_PREFERENCE_OVERRIDE"
)

type PassthroughProtocolType string

const (
	PassthroughProtocolType_A2A       PassthroughProtocolType = "A2A"
	PassthroughProtocolType_CUSTOM    PassthroughProtocolType = "CUSTOM"
	PassthroughProtocolType_INFERENCE PassthroughProtocolType = "INFERENCE"
	PassthroughProtocolType_MCP       PassthroughProtocolType = "MCP"
)

type PaymentConnectorStatus string

const (
	PaymentConnectorStatus_CREATE_FAILED PaymentConnectorStatus = "CREATE_FAILED"
	PaymentConnectorStatus_CREATING      PaymentConnectorStatus = "CREATING"
	PaymentConnectorStatus_DELETE_FAILED PaymentConnectorStatus = "DELETE_FAILED"
	PaymentConnectorStatus_DELETING      PaymentConnectorStatus = "DELETING"
	PaymentConnectorStatus_READY         PaymentConnectorStatus = "READY"
	PaymentConnectorStatus_UPDATE_FAILED PaymentConnectorStatus = "UPDATE_FAILED"
	PaymentConnectorStatus_UPDATING      PaymentConnectorStatus = "UPDATING"
)

type PaymentConnectorType string

const (
	PaymentConnectorType_CoinbaseCDP PaymentConnectorType = "CoinbaseCDP"
	PaymentConnectorType_StripePrivy PaymentConnectorType = "StripePrivy"
)

type PaymentCredentialProviderVendorType string

const (
	PaymentCredentialProviderVendorType_CoinbaseCDP PaymentCredentialProviderVendorType = "CoinbaseCDP"
	PaymentCredentialProviderVendorType_StripePrivy PaymentCredentialProviderVendorType = "StripePrivy"
)

type PaymentManagerStatus string

const (
	PaymentManagerStatus_CREATE_FAILED PaymentManagerStatus = "CREATE_FAILED"
	PaymentManagerStatus_CREATING      PaymentManagerStatus = "CREATING"
	PaymentManagerStatus_DELETE_FAILED PaymentManagerStatus = "DELETE_FAILED"
	PaymentManagerStatus_DELETING      PaymentManagerStatus = "DELETING"
	PaymentManagerStatus_READY         PaymentManagerStatus = "READY"
	PaymentManagerStatus_UPDATE_FAILED PaymentManagerStatus = "UPDATE_FAILED"
	PaymentManagerStatus_UPDATING      PaymentManagerStatus = "UPDATING"
)

type PaymentsAuthorizerType string

const (
	PaymentsAuthorizerType_AWS_IAM    PaymentsAuthorizerType = "AWS_IAM"
	PaymentsAuthorizerType_CUSTOM_JWT PaymentsAuthorizerType = "CUSTOM_JWT"
)

type PolicyEngineStatus_SDK string

const (
	PolicyEngineStatus_SDK_ACTIVE        PolicyEngineStatus_SDK = "ACTIVE"
	PolicyEngineStatus_SDK_CREATE_FAILED PolicyEngineStatus_SDK = "CREATE_FAILED"
	PolicyEngineStatus_SDK_CREATING      PolicyEngineStatus_SDK = "CREATING"
	PolicyEngineStatus_SDK_DELETE_FAILED PolicyEngineStatus_SDK = "DELETE_FAILED"
	PolicyEngineStatus_SDK_DELETING      PolicyEngineStatus_SDK = "DELETING"
	PolicyEngineStatus_SDK_UPDATE_FAILED PolicyEngineStatus_SDK = "UPDATE_FAILED"
	PolicyEngineStatus_SDK_UPDATING      PolicyEngineStatus_SDK = "UPDATING"
)

type PolicyGenerationStatus string

const (
	PolicyGenerationStatus_DELETE_FAILED   PolicyGenerationStatus = "DELETE_FAILED"
	PolicyGenerationStatus_GENERATED       PolicyGenerationStatus = "GENERATED"
	PolicyGenerationStatus_GENERATE_FAILED PolicyGenerationStatus = "GENERATE_FAILED"
	PolicyGenerationStatus_GENERATING      PolicyGenerationStatus = "GENERATING"
)

type PolicyStatus_SDK string

const (
	PolicyStatus_SDK_ACTIVE        PolicyStatus_SDK = "ACTIVE"
	PolicyStatus_SDK_CREATE_FAILED PolicyStatus_SDK = "CREATE_FAILED"
	PolicyStatus_SDK_CREATING      PolicyStatus_SDK = "CREATING"
	PolicyStatus_SDK_DELETE_FAILED PolicyStatus_SDK = "DELETE_FAILED"
	PolicyStatus_SDK_DELETING      PolicyStatus_SDK = "DELETING"
	PolicyStatus_SDK_UPDATE_FAILED PolicyStatus_SDK = "UPDATE_FAILED"
	PolicyStatus_SDK_UPDATING      PolicyStatus_SDK = "UPDATING"
)

type PolicyValidationMode string

const (
	PolicyValidationMode_FAIL_ON_ANY_FINDINGS PolicyValidationMode = "FAIL_ON_ANY_FINDINGS"
	PolicyValidationMode_IGNORE_ALL_FINDINGS  PolicyValidationMode = "IGNORE_ALL_FINDINGS"
)

type PrincipalMatchOperator string

const (
	PrincipalMatchOperator_StringEquals PrincipalMatchOperator = "StringEquals"
	PrincipalMatchOperator_StringLike   PrincipalMatchOperator = "StringLike"
)

type RegistryAuthorizerType string

const (
	RegistryAuthorizerType_AWS_IAM    RegistryAuthorizerType = "AWS_IAM"
	RegistryAuthorizerType_CUSTOM_JWT RegistryAuthorizerType = "CUSTOM_JWT"
)

type RegistryRecordCredentialProviderType string

const (
	RegistryRecordCredentialProviderType_IAM   RegistryRecordCredentialProviderType = "IAM"
	RegistryRecordCredentialProviderType_OAUTH RegistryRecordCredentialProviderType = "OAUTH"
)

type RegistryRecordOAuthGrantType string

const (
	RegistryRecordOAuthGrantType_CLIENT_CREDENTIALS RegistryRecordOAuthGrantType = "CLIENT_CREDENTIALS"
)

type RegistryRecordStatus string

const (
	RegistryRecordStatus_APPROVED         RegistryRecordStatus = "APPROVED"
	RegistryRecordStatus_CREATE_FAILED    RegistryRecordStatus = "CREATE_FAILED"
	RegistryRecordStatus_CREATING         RegistryRecordStatus = "CREATING"
	RegistryRecordStatus_DEPRECATED       RegistryRecordStatus = "DEPRECATED"
	RegistryRecordStatus_DRAFT            RegistryRecordStatus = "DRAFT"
	RegistryRecordStatus_PENDING_APPROVAL RegistryRecordStatus = "PENDING_APPROVAL"
	RegistryRecordStatus_REJECTED         RegistryRecordStatus = "REJECTED"
	RegistryRecordStatus_UPDATE_FAILED    RegistryRecordStatus = "UPDATE_FAILED"
	RegistryRecordStatus_UPDATING         RegistryRecordStatus = "UPDATING"
)

type RegistryStatus string

const (
	RegistryStatus_CREATE_FAILED RegistryStatus = "CREATE_FAILED"
	RegistryStatus_CREATING      RegistryStatus = "CREATING"
	RegistryStatus_DELETE_FAILED RegistryStatus = "DELETE_FAILED"
	RegistryStatus_DELETING      RegistryStatus = "DELETING"
	RegistryStatus_READY         RegistryStatus = "READY"
	RegistryStatus_UPDATE_FAILED RegistryStatus = "UPDATE_FAILED"
	RegistryStatus_UPDATING      RegistryStatus = "UPDATING"
)

type ResourceType string

const (
	ResourceType_CUSTOM ResourceType = "CUSTOM"
	ResourceType_SYSTEM ResourceType = "SYSTEM"
)

type RestAPIMethod string

const (
	RestAPIMethod_DELETE  RestAPIMethod = "DELETE"
	RestAPIMethod_GET     RestAPIMethod = "GET"
	RestAPIMethod_HEAD    RestAPIMethod = "HEAD"
	RestAPIMethod_OPTIONS RestAPIMethod = "OPTIONS"
	RestAPIMethod_PATCH   RestAPIMethod = "PATCH"
	RestAPIMethod_POST    RestAPIMethod = "POST"
	RestAPIMethod_PUT     RestAPIMethod = "PUT"
)

type SchemaType string

const (
	SchemaType_array   SchemaType = "array"
	SchemaType_boolean SchemaType = "boolean"
	SchemaType_integer SchemaType = "integer"
	SchemaType_number  SchemaType = "number"
	SchemaType_object  SchemaType = "object"
	SchemaType_string  SchemaType = "string"
)

type SearchType string

const (
	SearchType_SEMANTIC SearchType = "SEMANTIC"
)

type SecretSourceType string

const (
	SecretSourceType_EXTERNAL SecretSourceType = "EXTERNAL"
	SecretSourceType_MANAGED  SecretSourceType = "MANAGED"
)

type ServerProtocol string

const (
	ServerProtocol_A2A  ServerProtocol = "A2A"
	ServerProtocol_AGUI ServerProtocol = "AGUI"
	ServerProtocol_HTTP ServerProtocol = "HTTP"
	ServerProtocol_MCP  ServerProtocol = "MCP"
)

type Status string

const (
	Status_CREATE_FAILED Status = "CREATE_FAILED"
	Status_CREATING      Status = "CREATING"
	Status_DELETE_FAILED Status = "DELETE_FAILED"
	Status_DELETING      Status = "DELETING"
	Status_READY         Status = "READY"
	Status_UPDATE_FAILED Status = "UPDATE_FAILED"
	Status_UPDATING      Status = "UPDATING"
)

type SynchronizationType string

const (
	SynchronizationType_URL SynchronizationType = "URL"
)

type TargetProtocolType string

const (
	TargetProtocolType_HTTP TargetProtocolType = "HTTP"
	TargetProtocolType_MCP  TargetProtocolType = "MCP"
)

type TargetStatus string

const (
	TargetStatus_CREATE_PENDING_AUTH      TargetStatus = "CREATE_PENDING_AUTH"
	TargetStatus_CREATING                 TargetStatus = "CREATING"
	TargetStatus_DELETING                 TargetStatus = "DELETING"
	TargetStatus_FAILED                   TargetStatus = "FAILED"
	TargetStatus_READY                    TargetStatus = "READY"
	TargetStatus_SYNCHRONIZE_PENDING_AUTH TargetStatus = "SYNCHRONIZE_PENDING_AUTH"
	TargetStatus_SYNCHRONIZE_UNSUCCESSFUL TargetStatus = "SYNCHRONIZE_UNSUCCESSFUL"
	TargetStatus_SYNCHRONIZING            TargetStatus = "SYNCHRONIZING"
	TargetStatus_UPDATE_PENDING_AUTH      TargetStatus = "UPDATE_PENDING_AUTH"
	TargetStatus_UPDATE_UNSUCCESSFUL      TargetStatus = "UPDATE_UNSUCCESSFUL"
	TargetStatus_UPDATING                 TargetStatus = "UPDATING"
)

type TargetType string

const (
	TargetType_AGENTCORE_RUNTIME TargetType = "AGENTCORE_RUNTIME"
	TargetType_API_GATEWAY       TargetType = "API_GATEWAY"
	TargetType_CONNECTOR         TargetType = "CONNECTOR"
	TargetType_LAMBDA            TargetType = "LAMBDA"
	TargetType_MCP_SERVER        TargetType = "MCP_SERVER"
	TargetType_OPEN_API_SCHEMA   TargetType = "OPEN_API_SCHEMA"
	TargetType_PASSTHROUGH       TargetType = "PASSTHROUGH"
	TargetType_PROVIDER          TargetType = "PROVIDER"
	TargetType_SMITHY_MODEL      TargetType = "SMITHY_MODEL"
)

type ValidationExceptionReason string

const (
	ValidationExceptionReason_CannotParse                          ValidationExceptionReason = "CannotParse"
	ValidationExceptionReason_EventInOtherSession                  ValidationExceptionReason = "EventInOtherSession"
	ValidationExceptionReason_FieldValidationFailed                ValidationExceptionReason = "FieldValidationFailed"
	ValidationExceptionReason_IdempotentParameterMismatchException ValidationExceptionReason = "IdempotentParameterMismatchException"
	ValidationExceptionReason_ResourceConflict                     ValidationExceptionReason = "ResourceConflict"
)

type WAFFailureMode string

const (
	WAFFailureMode_FAIL_CLOSE WAFFailureMode = "FAIL_CLOSE"
	WAFFailureMode_FAIL_OPEN  WAFFailureMode = "FAIL_OPEN"
)
