// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewaySpec defines the desired state of Gateway.
type GatewaySpec struct {

	// The authorizer configuration for the gateway.
	// +kubebuilder:validation:Required
	AuthorizerConfiguration *AuthorizerConfiguration `json:"authorizerConfiguration"`
	// The type of authorizer to use for the gateway.
	// +kubebuilder:validation:Required
	AuthorizerType *string `json:"authorizerType"`
	// The description of the gateway.
	Description *string `json:"description,omitempty"`
	// The level of detail in error messages returned when invoking the gateway.
	//
	//   - If the value is DEBUG, granular exception messages are returned to help
	//     a user debug the gateway.
	//
	//   - If the value is omitted, a generic error message is returned to the
	//     end user.
	ExceptionLevel *string `json:"exceptionLevel,omitempty"`
	// The Amazon Resource Name (ARN) of the KMS key used to encrypt data associated
	// with the gateway.
	//
	// Regex Pattern: `^arn:aws(|-cn|-us-gov):kms:[a-zA-Z0-9-]*:[0-9]{12}:key/[a-zA-Z0-9-]{36}$`
	KMSKeyARN *string                                  `json:"kmsKeyARN,omitempty"`
	KMSKeyRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"kmsKeyRef,omitempty"`
	// The name of the gateway. The name must be unique within your account.
	//
	// Regex Pattern: `^([0-9a-zA-Z][-]?){1,100}$`
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The configuration settings for the protocol specified in the protocolType
	// parameter.
	ProtocolConfiguration *GatewayProtocolConfiguration `json:"protocolConfiguration,omitempty"`
	// The protocol type for the gateway.
	// +kubebuilder:validation:Required
	ProtocolType *string `json:"protocolType"`
	// The Amazon Resource Name (ARN) of the IAM role that provides permissions
	// for the gateway to access Amazon Web Services services.
	//
	// Regex Pattern: `^arn:aws(-[^:]+)?:iam::([0-9]{12})?:role/.+$`
	RoleARN *string                                  `json:"roleARN,omitempty"`
	RoleRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"roleRef,omitempty"`
	Tags    map[string]*string                       `json:"tags,omitempty"`
}

// GatewayStatus defines the observed state of Gateway
type GatewayStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the gateway was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The unique identifier of the created gateway.
	//
	// Regex Pattern: `^([0-9a-z][-]?){1,100}-[0-9a-z]{10}$`
	// +kubebuilder:validation:Optional
	GatewayID *string `json:"gatewayID,omitempty"`
	// The URL endpoint for the created gateway.
	// +kubebuilder:validation:Optional
	GatewayURL *string `json:"gatewayURL,omitempty"`
	// The current status of the gateway.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// The reasons for the current status of the gateway.
	// +kubebuilder:validation:Optional
	StatusReasons []*string `json:"statusReasons,omitempty"`
	// The timestamp when the gateway was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
	// The workload identity details for the created gateway.
	// +kubebuilder:validation:Optional
	WorkloadIdentityDetails *WorkloadIdentityDetails `json:"workloadIdentityDetails,omitempty"`
}

// Gateway is the Schema for the Gateways API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Gateway struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewaySpec   `json:"spec,omitempty"`
	Status            GatewayStatus `json:"status,omitempty"`
}

// GatewayList contains a list of Gateway
// +kubebuilder:object:root=true
type GatewayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Gateway `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Gateway{}, &GatewayList{})
}
