// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayTargetSpec defines the desired state of GatewayTarget.
//
// The gateway target.
type GatewayTargetSpec struct {

	// The credential provider configurations for the target. These configurations
	// specify how the gateway authenticates with the target endpoint.
	CredentialProviderConfigurations []*CredentialProviderConfiguration `json:"credentialProviderConfigurations,omitempty"`
	// The description of the gateway target.
	Description *string `json:"description,omitempty"`
	// The identifier of the gateway to create a target for.
	//
	// Regex Pattern: `^([0-9a-z][-]?){1,100}-[0-9a-z]{10}$`
	GatewayIdentifier    *string                                  `json:"gatewayIdentifier,omitempty"`
	GatewayIdentifierRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"gatewayIdentifierRef,omitempty"`
	// Optional configuration for HTTP header and query parameter propagation to
	// and from the gateway target.
	MetadataConfiguration *MetadataConfiguration `json:"metadataConfiguration,omitempty"`
	// The name of the gateway target. The name must be unique within the gateway.
	//
	// Regex Pattern: `^([0-9a-zA-Z][-]?){1,100}$`
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The configuration settings for the target, including endpoint information
	// and schema definitions.
	// +kubebuilder:validation:Required
	TargetConfiguration *TargetConfiguration `json:"targetConfiguration"`
}

// GatewayTargetStatus defines the observed state of GatewayTarget
type GatewayTargetStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the target was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The Amazon Resource Name (ARN) of the gateway.
	//
	// Regex Pattern: `^arn:aws(|-cn|-us-gov):bedrock-agentcore:[a-z0-9-]{1,20}:[0-9]{12}:gateway/[0-9a-zA-Z]{10}$`
	// +kubebuilder:validation:Optional
	GatewayARN *string `json:"gatewayARN,omitempty"`
	// The last synchronization of the target.
	// +kubebuilder:validation:Optional
	LastSynchronizedAt *metav1.Time `json:"lastSynchronizedAt,omitempty"`
	// The current status of the target.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// The reasons for the current status of the target.
	// +kubebuilder:validation:Optional
	StatusReasons []*string `json:"statusReasons,omitempty"`
	// The unique identifier of the created target.
	//
	// Regex Pattern: `^[0-9a-zA-Z]{10}$`
	// +kubebuilder:validation:Optional
	TargetID *string `json:"targetID,omitempty"`
	// The timestamp when the gateway target was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// GatewayTarget is the Schema for the GatewayTargets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type GatewayTarget struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayTargetSpec   `json:"spec,omitempty"`
	Status            GatewayTargetStatus `json:"status,omitempty"`
}

// GatewayTargetList contains a list of GatewayTarget
// +kubebuilder:object:root=true
type GatewayTargetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayTarget `json:"items"`
}

func init() {
	SchemeBuilder.Register(&GatewayTarget{}, &GatewayTargetList{})
}
