// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// HarnessSpec defines the desired state of Harness.
//
// Representation of a harness.
type HarnessSpec struct {

	// The tools that the agent is allowed to use. Supports glob patterns such as
	// * for all tools, @builtin for all built-in tools, or @serverName/toolName
	// for specific MCP server tools.
	AllowedTools            []*string                `json:"allowedTools,omitempty"`
	AuthorizerConfiguration *AuthorizerConfiguration `json:"authorizerConfiguration,omitempty"`
	// The compute environment configuration for the harness, including network
	// and lifecycle settings.
	Environment *HarnessEnvironmentProviderRequest `json:"environment,omitempty"`
	// The environment artifact for the harness, such as a custom container image
	// containing additional dependencies.
	EnvironmentArtifact *HarnessEnvironmentArtifact `json:"environmentArtifact,omitempty"`
	// Environment variables to set in the harness runtime environment.
	EnvironmentVariables map[string]*string `json:"environmentVariables,omitempty"`
	// The ARN of the IAM role that the harness assumes when running. This role
	// must have permissions for the services the agent needs to access, such as
	// Amazon Bedrock for model invocation.
	//
	// Regex Pattern: `^arn:aws(-[^:]+)?:iam::([0-9]{12})?:role/.+$`
	ExecutionRoleARN *string                                  `json:"executionRoleARN,omitempty"`
	ExecutionRoleRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"executionRoleRef,omitempty"`
	// The maximum number of iterations the agent loop can execute per invocation.
	MaxIterations *int64 `json:"maxIterations,omitempty"`
	// The maximum total number of output tokens the agent can generate across all
	// model calls within a single invocation.
	MaxTokens *int64 `json:"maxTokens,omitempty"`
	// The AgentCore Memory configuration for persisting conversation context across
	// sessions.
	Memory *HarnessMemoryConfiguration `json:"memory,omitempty"`
	// The model configuration for the harness. Supports Amazon Bedrock, OpenAI,
	// and Google Gemini model providers.
	Model *HarnessModelConfiguration `json:"model,omitempty"`
	// The name of the harness. Must start with a letter and contain only alphanumeric
	// characters and underscores.
	//
	// Regex Pattern: `^[a-zA-Z][a-zA-Z0-9_]{0,39}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The skills available to the agent. Skills are bundles of files that the agent
	// can pull into its context on demand.
	Skills []*HarnessSkill `json:"skills,omitempty"`
	// The system prompt that defines the agent's behavior and instructions.
	SystemPrompt []*HarnessSystemContentBlock `json:"systemPrompt,omitempty"`
	// Tags to apply to the harness resource.
	Tags map[string]*string `json:"tags,omitempty"`
	// The maximum duration in seconds for the agent loop execution per invocation.
	TimeoutSeconds *int64 `json:"timeoutSeconds,omitempty"`
	// The tools available to the agent, such as remote MCP servers, AgentCore Gateway,
	// AgentCore Browser, Code Interpreter, or inline functions.
	Tools []*HarnessTool `json:"tools,omitempty"`
	// The truncation configuration for managing conversation context when it exceeds
	// model limits.
	Truncation *HarnessTruncationConfiguration `json:"truncation,omitempty"`
}

// HarnessStatus defines the observed state of Harness
type HarnessStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The createdAt time of the harness.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// Reason why create or update operations fail.
	// +kubebuilder:validation:Optional
	FailureReason *string `json:"failureReason,omitempty"`
	// The version of the harness. Incremented on every successful UpdateHarness.
	//
	// Regex Pattern: `^([1-9][0-9]{0,4})$`
	// +kubebuilder:validation:Optional
	HarnessVersion *string `json:"harnessVersion,omitempty"`
	// The ID of the harness.
	//
	// Regex Pattern: `^[a-zA-Z][a-zA-Z0-9_]{0,39}-[a-zA-Z0-9]{10}$`
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The status of the harness.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// The updatedAt time of the harness.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// Harness is the Schema for the Harnesses API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Harness struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              HarnessSpec   `json:"spec,omitempty"`
	Status            HarnessStatus `json:"status,omitempty"`
}

// HarnessList contains a list of Harness
// +kubebuilder:object:root=true
type HarnessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Harness `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Harness{}, &HarnessList{})
}
