// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// The configuration for an Amazon API Gateway target.
type APIGatewayTargetConfiguration struct {
	// The configuration for defining REST API tool filters and overrides for the
	// gateway target.
	APIGatewayToolConfiguration *APIGatewayToolConfiguration `json:"apiGatewayToolConfiguration,omitempty"`
	RestAPIID                   *string                      `json:"restAPIID,omitempty"`
	// Reference field for RestAPIID
	RestAPIRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"restAPIRef,omitempty"`
	Stage      *string                                  `json:"stage,omitempty"`
}

// The configuration for defining REST API tool filters and overrides for the
// gateway target.
type APIGatewayToolConfiguration struct {
	ToolFilters   []*APIGatewayToolFilter   `json:"toolFilters,omitempty"`
	ToolOverrides []*APIGatewayToolOverride `json:"toolOverrides,omitempty"`
}

// Specifies which operations from an API Gateway REST API are exposed as tools.
// Tool names and descriptions are derived from the operationId and description
// fields in the API's exported OpenAPI specification.
type APIGatewayToolFilter struct {
	FilterPath *string   `json:"filterPath,omitempty"`
	Methods    []*string `json:"methods,omitempty"`
}

// Settings to override configurations for a tool.
type APIGatewayToolOverride struct {
	Description *string `json:"description,omitempty"`
	Method      *string `json:"method,omitempty"`
	Name        *string `json:"name,omitempty"`
	Path        *string `json:"path,omitempty"`
}

// Contains information about an API key credential provider.
type APIKeyCredentialProviderItem struct {
	CreatedTime           *metav1.Time `json:"createdTime,omitempty"`
	CredentialProviderARN *string      `json:"credentialProviderARN,omitempty"`
	LastUpdatedTime       *metav1.Time `json:"lastUpdatedTime,omitempty"`
	Name                  *string      `json:"name,omitempty"`
}

// Configuration for API schema.
type APISchemaConfiguration struct {
	InlinePayload *string `json:"inlinePayload,omitempty"`
	// The Amazon S3 configuration for a gateway. This structure defines how the
	// gateway accesses files in Amazon S3.
	S3 *S3Configuration `json:"s3,omitempty"`
}

// The artifact of the agent.
type AgentRuntimeArtifact struct {
	// The configuration for the source code that defines how the agent runtime
	// code should be executed, including the code location, runtime environment,
	// and entry point.
	CodeConfiguration *CodeConfiguration `json:"codeConfiguration,omitempty"`
	// Representation of a container configuration.
	ContainerConfiguration *ContainerConfiguration `json:"containerConfiguration,omitempty"`
}

// Contains information about an agent runtime endpoint. An endpoint provides
// a way to connect to and interact with an agent runtime.
type AgentRuntimeEndpoint_SDK struct {
	AgentRuntimeARN         *string      `json:"agentRuntimeARN,omitempty"`
	AgentRuntimeEndpointARN *string      `json:"agentRuntimeEndpointARN,omitempty"`
	CreatedAt               *metav1.Time `json:"createdAt,omitempty"`
	Description             *string      `json:"description,omitempty"`
	ID                      *string      `json:"id,omitempty"`
	LastUpdatedAt           *metav1.Time `json:"lastUpdatedAt,omitempty"`
	LiveVersion             *string      `json:"liveVersion,omitempty"`
	Name                    *string      `json:"name,omitempty"`
	Status                  *string      `json:"status,omitempty"`
	TargetVersion           *string      `json:"targetVersion,omitempty"`
}

// Contains information about an agent runtime. An agent runtime is the execution
// environment for a Amazon Bedrock AgentCore Agent.
type AgentRuntime_SDK struct {
	AgentRuntimeARN     *string      `json:"agentRuntimeARN,omitempty"`
	AgentRuntimeID      *string      `json:"agentRuntimeID,omitempty"`
	AgentRuntimeName    *string      `json:"agentRuntimeName,omitempty"`
	AgentRuntimeVersion *string      `json:"agentRuntimeVersion,omitempty"`
	Description         *string      `json:"description,omitempty"`
	LastUpdatedAt       *metav1.Time `json:"lastUpdatedAt,omitempty"`
	Status              *string      `json:"status,omitempty"`
}

// Configuration for the registry record approval workflow. Controls whether
// records added to the registry require explicit approval before becoming active.
type ApprovalConfiguration struct {
	AutoApproval *bool `json:"autoApproval,omitempty"`
}

// Contains the authorization data that is returned when a gateway target is
// configured with a credential provider with authorization code grant type
// and requires user federation.
type AuthorizationData struct {
	// OAuth2-specific authorization data, including the authorization URL and user
	// identifier for the authorization session.
	Oauth2 *OAuth2AuthorizationData `json:"oauth2,omitempty"`
}

// Represents inbound authorization configuration options used to authenticate
// incoming requests.
type AuthorizerConfiguration struct {
	// Configuration for inbound JWT-based authorization, specifying how incoming
	// requests should be authenticated.
	CustomJWTAuthorizer *CustomJWTAuthorizerConfiguration `json:"customJWTAuthorizer,omitempty"`
}

// Defines the value or values to match for and the relationship of the match.
type AuthorizingClaimMatchValueType struct {
	ClaimMatchOperator *string `json:"claimMatchOperator,omitempty"`
	// The value or values to match for.
	//
	//    * Include a matchValueString with the EQUALS operator to specify a string
	//    that matches the claim field value.
	//
	//    * Include a matchValueArray to specify an array of string values. You
	//    can use the following operators: Use CONTAINS to yield a match if the
	//    claim field value is in the array. Use CONTAINS_ANY to yield a match if
	//    the claim field value contains any of the strings in the array.
	ClaimMatchValue *ClaimMatchValueType `json:"claimMatchValue,omitempty"`
}

// The configuration for using Amazon Bedrock models in evaluator assessments,
// including model selection and inference parameters.
type BedrockEvaluatorModelConfig struct {
	ModelID *string `json:"modelID,omitempty"`
}

// Browser enterprise policy configuration.
type BrowserEnterprisePolicy struct {
	// The location of a resource.
	Location *ResourceLocation `json:"location,omitempty"`
	Type     *string           `json:"type,omitempty"`
}

// The network configuration for a browser. This structure defines how the browser
// connects to the network.
type BrowserNetworkConfiguration struct {
	NetworkMode *string `json:"networkMode,omitempty"`
	// VpcConfig for the Agent.
	VPCConfig *VPCConfig `json:"vpcConfig,omitempty"`
}

// Contains summary information about a browser profile. A browser profile stores
// persistent browser data that can be reused across browser sessions.
type BrowserProfileSummary struct {
	CreatedAt                 *metav1.Time `json:"createdAt,omitempty"`
	Description               *string      `json:"description,omitempty"`
	LastSavedAt               *metav1.Time `json:"lastSavedAt,omitempty"`
	LastSavedBrowserID        *string      `json:"lastSavedBrowserID,omitempty"`
	LastSavedBrowserSessionID *string      `json:"lastSavedBrowserSessionID,omitempty"`
	LastUpdatedAt             *metav1.Time `json:"lastUpdatedAt,omitempty"`
	Name                      *string      `json:"name,omitempty"`
	ProfileARN                *string      `json:"profileARN,omitempty"`
	ProfileID                 *string      `json:"profileID,omitempty"`
	// The status of a browser profile.
	Status *string `json:"status,omitempty"`
}

// Configuration for enabling browser signing capabilities that allow agents
// to cryptographically identify themselves to websites using HTTP message signatures.
type BrowserSigningConfigInput struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// The current browser signing configuration that shows whether cryptographic
// agent identification is enabled for web bot authentication.
type BrowserSigningConfigOutput struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// Contains summary information about a browser. A browser enables Amazon Bedrock
// AgentCore Agent to interact with web content.
type BrowserSummary struct {
	BrowserARN    *string      `json:"browserARN,omitempty"`
	BrowserID     *string      `json:"browserID,omitempty"`
	CreatedAt     *metav1.Time `json:"createdAt,omitempty"`
	Description   *string      `json:"description,omitempty"`
	LastUpdatedAt *metav1.Time `json:"lastUpdatedAt,omitempty"`
	Name          *string      `json:"name,omitempty"`
	Status        *string      `json:"status,omitempty"`
}

// The definition of a categorical rating scale option that provides a named
// category with its description for evaluation scoring.
type CategoricalScaleDefinition struct {
	Definition *string `json:"definition,omitempty"`
	Label      *string `json:"label,omitempty"`
}

// Represents a Cedar policy statement within the AgentCore Policy system. Cedar
// is a policy language designed for authorization that provides human-readable,
// analyzable, and high-performance policy evaluation for controlling agent
// behavior and access decisions.
type CedarPolicy struct {
	Statement *string `json:"statement,omitempty"`
}

// A certificate to install in the browser or code interpreter.
type Certificate struct {
	// The location from which to retrieve a certificate.
	Location *CertificateLocation `json:"location,omitempty"`
}

// The location from which to retrieve a certificate.
type CertificateLocation struct {
	// The Amazon Web Services Secrets Manager location configuration.
	SecretsManager *SecretsManagerLocation `json:"secretsManager,omitempty"`
}

// The value or values to match for.
//
//   - Include a matchValueString with the EQUALS operator to specify a string
//     that matches the claim field value.
//
//   - Include a matchValueArray to specify an array of string values. You
//     can use the following operators: Use CONTAINS to yield a match if the
//     claim field value is in the array. Use CONTAINS_ANY to yield a match if
//     the claim field value contains any of the strings in the array.
type ClaimMatchValueType struct {
	MatchValueString     *string   `json:"matchValueString,omitempty"`
	MatchValueStringList []*string `json:"matchValueStringList,omitempty"`
}

// The source code configuration that specifies the location and details of
// the code to be executed.
type Code struct {
	// The Amazon S3 location for storing data. This structure defines where in
	// Amazon S3 data is stored.
	S3 *S3Location `json:"s3,omitempty"`
}

// The configuration for the source code that defines how the agent runtime
// code should be executed, including the code location, runtime environment,
// and entry point.
type CodeConfiguration struct {
	// The source code configuration that specifies the location and details of
	// the code to be executed.
	Code       *Code     `json:"code,omitempty"`
	EntryPoint []*string `json:"entryPoint,omitempty"`
	Runtime    *string   `json:"runtime,omitempty"`
}

// The network configuration for a code interpreter. This structure defines
// how the code interpreter connects to the network.
type CodeInterpreterNetworkConfiguration struct {
	NetworkMode *string `json:"networkMode,omitempty"`
	// VpcConfig for the Agent.
	VPCConfig *VPCConfig `json:"vpcConfig,omitempty"`
}

// Contains summary information about a code interpreter. A code interpreter
// enables Amazon Bedrock AgentCore Agent to execute code.
type CodeInterpreterSummary struct {
	CodeInterpreterARN *string      `json:"codeInterpreterARN,omitempty"`
	CodeInterpreterID  *string      `json:"codeInterpreterID,omitempty"`
	CreatedAt          *metav1.Time `json:"createdAt,omitempty"`
	Description        *string      `json:"description,omitempty"`
	LastUpdatedAt      *metav1.Time `json:"lastUpdatedAt,omitempty"`
	Name               *string      `json:"name,omitempty"`
	Status             *string      `json:"status,omitempty"`
}

// Coinbase CDP configuration output with secret ARNs.
type CoinbaseCdpConfigurationOutput struct {
	// Contains information about a secret in Amazon Web Services Secrets Manager.
	APIKeySecretARN *Secret `json:"apiKeySecretARN,omitempty"`
	// Contains information about a secret in Amazon Web Services Secrets Manager.
	WalletSecretARN *Secret `json:"walletSecretARN,omitempty"`
}

// A reference to a specific version of a configuration bundle.
type ConfigurationBundleReference struct {
	BundleVersion *string `json:"bundleVersion,omitempty"`
}

// Summary information about a configuration bundle.
type ConfigurationBundleSummary struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
}

// Summary information about a configuration bundle version.
type ConfigurationBundleVersionSummary struct {
	VersionCreatedAt *metav1.Time `json:"versionCreatedAt,omitempty"`
}

// Configuration for a single tool within a connector.
type ConnectorConfiguration struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Specifies a parameter override for a connector tool, allowing you to control
// parameter visibility and descriptions.
type ConnectorParameterOverride struct {
	Description *string `json:"description,omitempty"`
	Path        *string `json:"path,omitempty"`
	Visible     *bool   `json:"visible,omitempty"`
}

// Representation of a container configuration.
type ContainerConfiguration struct {
	ContainerURI *string `json:"containerURI,omitempty"`
}

// Defines what content to stream and at what level of detail.
type ContentConfiguration struct {
	Level *string `json:"level,omitempty"`
	Type  *string `json:"type_,omitempty"`
}

// A credential provider for gateway authentication. This structure contains
// the configuration for authenticating with the target endpoint.
type CredentialProvider struct {
	// An API key credential provider for gateway authentication. This structure
	// contains the configuration for authenticating with the target endpoint using
	// an API key.
	APIKeyCredentialProvider *GatewayAPIKeyCredentialProvider `json:"apiKeyCredentialProvider,omitempty"`
	// An OAuth credential provider for gateway authentication. This structure contains
	// the configuration for authenticating with the target endpoint using OAuth.
	OauthCredentialProvider *OAuthCredentialProvider `json:"oauthCredentialProvider,omitempty"`
}

// The configuration for a credential provider. This structure defines how the
// gateway authenticates with the target endpoint.
type CredentialProviderConfiguration struct {
	// A credential provider for gateway authentication. This structure contains
	// the configuration for authenticating with the target endpoint.
	CredentialProvider     *CredentialProvider `json:"credentialProvider,omitempty"`
	CredentialProviderType *string             `json:"credentialProviderType,omitempty"`
}

// Defines the name of a custom claim field and rules for finding matches to
// authenticate its value.
type CustomClaimValidationType struct {
	// Defines the value or values to match for and the relationship of the match.
	AuthorizingClaimMatchValue *AuthorizingClaimMatchValueType `json:"authorizingClaimMatchValue,omitempty"`
	InboundTokenClaimName      *string                         `json:"inboundTokenClaimName,omitempty"`
	InboundTokenClaimValueType *string                         `json:"inboundTokenClaimValueType,omitempty"`
}

// Input for custom configuration of a memory strategy.
type CustomConfigurationInput struct {
	// Input for the configuration to override the episodic memory strategy.
	EpisodicOverride *EpisodicOverrideConfigurationInput `json:"episodicOverride,omitempty"`
	// Input configuration for a self-managed memory strategy.
	SelfManagedConfiguration *SelfManagedConfigurationInput `json:"selfManagedConfiguration,omitempty"`
	// Input for semantic override configuration in a memory strategy.
	SemanticOverride *SemanticOverrideConfigurationInput `json:"semanticOverride,omitempty"`
	// Input for summary override configuration in a memory strategy.
	SummaryOverride *SummaryOverrideConfigurationInput `json:"summaryOverride,omitempty"`
	// Input for user preference override configuration in a memory strategy.
	UserPreferenceOverride *UserPreferenceOverrideConfigurationInput `json:"userPreferenceOverride,omitempty"`
}

// Input for a custom consolidation configuration.
type CustomConsolidationConfigurationInput struct {
	// Configurations for overriding the consolidation step of the episodic memory
	// strategy.
	EpisodicConsolidationOverride *EpisodicOverrideConsolidationConfigurationInput `json:"episodicConsolidationOverride,omitempty"`
	// Input for semantic override consolidation configuration in a memory strategy.
	SemanticConsolidationOverride *SemanticOverrideConsolidationConfigurationInput `json:"semanticConsolidationOverride,omitempty"`
	// Input for summary override consolidation configuration in a memory strategy.
	SummaryConsolidationOverride *SummaryOverrideConsolidationConfigurationInput `json:"summaryConsolidationOverride,omitempty"`
	// Input for user preference override consolidation configuration in a memory
	// strategy.
	UserPreferenceConsolidationOverride *UserPreferenceOverrideConsolidationConfigurationInput `json:"userPreferenceConsolidationOverride,omitempty"`
}

// Input for a custom extraction configuration.
type CustomExtractionConfigurationInput struct {
	// Configurations for overriding the extraction step of the episodic memory
	// strategy.
	EpisodicExtractionOverride *EpisodicOverrideExtractionConfigurationInput `json:"episodicExtractionOverride,omitempty"`
	// Input for semantic override extraction configuration in a memory strategy.
	SemanticExtractionOverride *SemanticOverrideExtractionConfigurationInput `json:"semanticExtractionOverride,omitempty"`
	// Input for user preference override extraction configuration in a memory strategy.
	UserPreferenceExtractionOverride *UserPreferenceOverrideExtractionConfigurationInput `json:"userPreferenceExtractionOverride,omitempty"`
}

// Configuration for inbound JWT-based authorization, specifying how incoming
// requests should be authenticated.
type CustomJWTAuthorizerConfiguration struct {
	AllowedAudience []*string                    `json:"allowedAudience,omitempty"`
	AllowedClients  []*string                    `json:"allowedClients,omitempty"`
	AllowedScopes   []*string                    `json:"allowedScopes,omitempty"`
	CustomClaims    []*CustomClaimValidationType `json:"customClaims,omitempty"`
	DiscoveryURL    *string                      `json:"discoveryURL,omitempty"`
}

// Input for creating a custom memory strategy.
type CustomMemoryStrategyInput struct {
	// Input for custom configuration of a memory strategy.
	Configuration      *CustomConfigurationInput `json:"configuration,omitempty"`
	Description        *string                   `json:"description,omitempty"`
	Name               *string                   `json:"name,omitempty"`
	NamespaceTemplates []*string                 `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string                 `json:"namespaces,omitempty"`
}

// Input for a custom reflection configuration.
type CustomReflectionConfigurationInput struct {
	// Configurations for overriding the reflection step of the episodic memory
	// strategy.
	EpisodicReflectionOverride *EpisodicOverrideReflectionConfigurationInput `json:"episodicReflectionOverride,omitempty"`
}

// Summary information about a dataset.
type DatasetSummary struct {
	CreatedAt   *metav1.Time `json:"createdAt,omitempty"`
	Description *string      `json:"description,omitempty"`
	UpdatedAt   *metav1.Time `json:"updatedAt,omitempty"`
}

// Summary information about a published dataset version.
type DatasetVersionSummary struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
}

// Input for deleting a memory strategy.
type DeleteMemoryStrategyInput struct {
	MemoryStrategyID *string `json:"memoryStrategyID,omitempty"`
}

// Configuration for an Amazon EFS access point filesystem mounted into the
// AgentCore Runtime. EFS access points provide shared file storage accessible
// from your AgentCore Runtime sessions.
type EFSAccessPointConfiguration struct {
	MountPath *string `json:"mountPath,omitempty"`
}

// Contains configurations to override the default consolidation step for the
// episodic memory strategy.
type EpisodicConsolidationOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Contains configurations to override the default extraction step for the episodic
// memory strategy.
type EpisodicExtractionOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for creating an episodic memory strategy.
type EpisodicMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	Name               *string   `json:"name,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
	// An episodic reflection configuration input.
	ReflectionConfiguration *EpisodicReflectionConfigurationInput `json:"reflectionConfiguration,omitempty"`
}

// Input for the configuration to override the episodic memory strategy.
type EpisodicOverrideConfigurationInput struct {
	// Configurations for overriding the consolidation step of the episodic memory
	// strategy.
	Consolidation *EpisodicOverrideConsolidationConfigurationInput `json:"consolidation,omitempty"`
	// Configurations for overriding the extraction step of the episodic memory
	// strategy.
	Extraction *EpisodicOverrideExtractionConfigurationInput `json:"extraction,omitempty"`
	// Configurations for overriding the reflection step of the episodic memory
	// strategy.
	Reflection *EpisodicOverrideReflectionConfigurationInput `json:"reflection,omitempty"`
}

// Configurations for overriding the consolidation step of the episodic memory
// strategy.
type EpisodicOverrideConsolidationConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Configurations for overriding the extraction step of the episodic memory
// strategy.
type EpisodicOverrideExtractionConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Configurations for overriding the reflection step of the episodic memory
// strategy.
type EpisodicOverrideReflectionConfigurationInput struct {
	AppendToPrompt     *string   `json:"appendToPrompt,omitempty"`
	ModelID            *string   `json:"modelID,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// The configuration for the reflections created with the episodic memory strategy.
type EpisodicReflectionConfiguration struct {
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// An episodic reflection configuration input.
type EpisodicReflectionConfigurationInput struct {
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Contains configurations to override the default reflection step for the episodic
// memory strategy.
type EpisodicReflectionOverride struct {
	AppendToPrompt     *string   `json:"appendToPrompt,omitempty"`
	ModelID            *string   `json:"modelID,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// The summary information about an evaluator, including basic metadata and
// status information.
type EvaluatorSummary struct {
	CreatedAt             *metav1.Time `json:"createdAt,omitempty"`
	KMSKeyARN             *string      `json:"kmsKeyARN,omitempty"`
	LockedForModification *bool        `json:"lockedForModification,omitempty"`
	UpdatedAt             *metav1.Time `json:"updatedAt,omitempty"`
}

// Configuration for a filesystem that can be mounted into the AgentCore Runtime.
type FilesystemConfiguration struct {
	// Configuration for a session storage filesystem mounted into the AgentCore
	// Runtime. Session storage provides persistent storage that is preserved across
	// AgentCore Runtime session invocations.
	SessionStorage *SessionStorageConfiguration `json:"sessionStorage,omitempty"`
}

// The filter that applies conditions to agent traces during online evaluation
// to determine which traces should be evaluated.
type Filter struct {
	Key *string `json:"key,omitempty"`
}

// The value used in filter comparisons, supporting different data types for
// flexible filtering criteria.
type FilterValue struct {
	BooleanValue *bool   `json:"booleanValue,omitempty"`
	StringValue  *string `json:"stringValue,omitempty"`
}

// Represents a finding or issue discovered during policy generation or validation.
// Findings provide insights about potential problems, recommendations, or validation
// results from policy analysis operations. Finding types include: VALID (policy
// is ready to use), INVALID (policy has validation errors that must be fixed),
// NOT_TRANSLATABLE (input couldn't be converted to policy), ALLOW_ALL (policy
// would allow all actions, potential security risk), ALLOW_NONE (policy would
// allow no actions, unusable), DENY_ALL (policy would deny all actions, may
// be too restrictive), and DENY_NONE (policy would deny no actions, ineffective).
// Review all findings before creating policies from generated assets to ensure
// they match your security requirements.
type Finding struct {
	Description *string `json:"description,omitempty"`
}

// An API key credential provider for gateway authentication. This structure
// contains the configuration for authenticating with the target endpoint using
// an API key.
type GatewayAPIKeyCredentialProvider struct {
	CredentialLocation      *string `json:"credentialLocation,omitempty"`
	CredentialParameterName *string `json:"credentialParameterName,omitempty"`
	CredentialPrefix        *string `json:"credentialPrefix,omitempty"`
	ProviderARN             *string `json:"providerARN,omitempty"`
}

// The configuration for an interceptor on a gateway. This structure defines
// settings for an interceptor that will be invoked during the invocation of
// the gateway.
type GatewayInterceptorConfiguration struct {
	// The input configuration of the interceptor.
	InputConfiguration *InterceptorInputConfiguration `json:"inputConfiguration,omitempty"`
	InterceptionPoints []*string                      `json:"interceptionPoints,omitempty"`
	// The interceptor configuration.
	Interceptor *InterceptorConfiguration `json:"interceptor,omitempty"`
}

// The configuration for a policy engine associated with a gateway. A policy
// engine is a collection of policies that evaluates and authorizes agent tool
// calls. When associated with a gateway, the policy engine intercepts all agent
// requests and determines whether to allow or deny each action based on the
// defined policies.
type GatewayPolicyEngineConfiguration struct {
	ARN  *string `json:"arn,omitempty"`
	Mode *string `json:"mode,omitempty"`
}

// The configuration for a gateway protocol. This structure defines how the
// gateway communicates with external services.
type GatewayProtocolConfiguration struct {
	// The configuration for a Model Context Protocol (MCP) gateway. This structure
	// defines how the gateway implements the MCP protocol.
	Mcp *MCPGatewayConfiguration `json:"mcp,omitempty"`
}

// Detailed information about a gateway rule.
type GatewayRuleDetail struct {
	CreatedAt  *metav1.Time `json:"createdAt,omitempty"`
	GatewayARN *string      `json:"gatewayARN,omitempty"`
	UpdatedAt  *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains summary information about a gateway.
type GatewaySummary struct {
	AuthorizerType *string      `json:"authorizerType,omitempty"`
	CreatedAt      *metav1.Time `json:"createdAt,omitempty"`
	Description    *string      `json:"description,omitempty"`
	GatewayID      *string      `json:"gatewayID,omitempty"`
	Name           *string      `json:"name,omitempty"`
	ProtocolType   *string      `json:"protocolType,omitempty"`
	Status         *string      `json:"status,omitempty"`
	UpdatedAt      *metav1.Time `json:"updatedAt,omitempty"`
}

// The gateway target.
type GatewayTarget_SDK struct {
	// Contains the authorization data that is returned when a gateway target is
	// configured with a credential provider with authorization code grant type
	// and requires user federation.
	AuthorizationData                *AuthorizationData                 `json:"authorizationData,omitempty"`
	CreatedAt                        *metav1.Time                       `json:"createdAt,omitempty"`
	CredentialProviderConfigurations []*CredentialProviderConfiguration `json:"credentialProviderConfigurations,omitempty"`
	Description                      *string                            `json:"description,omitempty"`
	GatewayARN                       *string                            `json:"gatewayARN,omitempty"`
	LastSynchronizedAt               *metav1.Time                       `json:"lastSynchronizedAt,omitempty"`
	// Configuration for HTTP header and query parameter propagation between the
	// gateway and target servers.
	MetadataConfiguration *MetadataConfiguration `json:"metadataConfiguration,omitempty"`
	Name                  *string                `json:"name,omitempty"`
	Status                *string                `json:"status,omitempty"`
	StatusReasons         []*string              `json:"statusReasons,omitempty"`
	// The configuration for a gateway target. This structure defines how the gateway
	// connects to and interacts with the target endpoint.
	TargetConfiguration *TargetConfiguration `json:"targetConfiguration,omitempty"`
	TargetID            *string              `json:"targetID,omitempty"`
	UpdatedAt           *metav1.Time         `json:"updatedAt,omitempty"`
}

// The API schema configuration for an HTTP target. This schema defines the
// API structure that the target exposes.
type HTTPAPISchemaConfiguration struct {
	// Configuration for API schema.
	Source *APISchemaConfiguration `json:"source,omitempty"`
}

// Configuration for AgentCore Browser.
type HarnessAgentCoreBrowserConfig struct {
	// Browser ARN for Harness tool configuration. Accepts both managed (aws.browser.v1)
	// and custom browser ARNs.
	BrowserARN *string `json:"browserARN,omitempty"`
}

// Configuration for AgentCore Code Interpreter.
type HarnessAgentCoreCodeInterpreterConfig struct {
	// Code Interpreter ARN for Harness tool configuration. Accepts both managed
	// (aws.codeinterpreter.v1) and custom code interpreter ARNs.
	CodeInterpreterARN *string `json:"codeInterpreterARN,omitempty"`
}

// Configuration for AgentCore Gateway.
type HarnessAgentCoreGatewayConfig struct {
	GatewayARN *string `json:"gatewayARN,omitempty"`
	// Authentication method for calling a Gateway.
	OutboundAuth *HarnessGatewayOutboundAuth `json:"outboundAuth,omitempty"`
}

// Configuration for AgentCore Memory integration.
type HarnessAgentCoreMemoryConfiguration struct {
	ActorID         *string                                           `json:"actorID,omitempty"`
	ARN             *string                                           `json:"arn,omitempty"`
	MessagesCount   *int64                                            `json:"messagesCount,omitempty"`
	RetrievalConfig map[string]*HarnessAgentCoreMemoryRetrievalConfig `json:"retrievalConfig,omitempty"`
}

// Configuration for memory retrieval within a namespace.
type HarnessAgentCoreMemoryRetrievalConfig struct {
	RelevanceScore *float64 `json:"relevanceScore,omitempty"`
	StrategyID     *string  `json:"strategyID,omitempty"`
	TopK           *int64   `json:"topK,omitempty"`
}

// The AgentCore Runtime environment for a harness.
type HarnessAgentCoreRuntimeEnvironment struct {
	AgentRuntimeARN          *string                    `json:"agentRuntimeARN,omitempty"`
	AgentRuntimeID           *string                    `json:"agentRuntimeID,omitempty"`
	AgentRuntimeName         *string                    `json:"agentRuntimeName,omitempty"`
	FilesystemConfigurations []*FilesystemConfiguration `json:"filesystemConfigurations,omitempty"`
	// LifecycleConfiguration lets you manage the lifecycle of runtime sessions
	// and resources in AgentCore Runtime. This configuration helps optimize resource
	// utilization by automatically cleaning up idle sessions and preventing long-running
	// instances from consuming resources indefinitely.
	LifecycleConfiguration *LifecycleConfiguration `json:"lifecycleConfiguration,omitempty"`
	// SecurityConfig for the Agent.
	NetworkConfiguration *NetworkConfiguration `json:"networkConfiguration,omitempty"`
}

// The AgentCore Runtime environment request configuration.
type HarnessAgentCoreRuntimeEnvironmentRequest struct {
	FilesystemConfigurations []*FilesystemConfiguration `json:"filesystemConfigurations,omitempty"`
	// LifecycleConfiguration lets you manage the lifecycle of runtime sessions
	// and resources in AgentCore Runtime. This configuration helps optimize resource
	// utilization by automatically cleaning up idle sessions and preventing long-running
	// instances from consuming resources indefinitely.
	LifecycleConfiguration *LifecycleConfiguration `json:"lifecycleConfiguration,omitempty"`
	// SecurityConfig for the Agent.
	NetworkConfiguration *NetworkConfiguration `json:"networkConfiguration,omitempty"`
}

// Configuration for an Amazon Bedrock model provider.
type HarnessBedrockModelConfig struct {
	APIFormat   *string  `json:"apiFormat,omitempty"`
	MaxTokens   *int64   `json:"maxTokens,omitempty"`
	ModelID     *string  `json:"modelID,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
	TopP        *float64 `json:"topP,omitempty"`
}

// Representation of a harness endpoint. An endpoint is a named, stable reference
// to a specific version of a harness that callers invoke, allowing the underlying
// version to be updated without changing how the agent is invoked.
type HarnessEndpoint struct {
	CreatedAt     *metav1.Time `json:"createdAt,omitempty"`
	FailureReason *string      `json:"failureReason,omitempty"`
	HarnessID     *string      `json:"harnessID,omitempty"`
	HarnessName   *string      `json:"harnessName,omitempty"`
	LiveVersion   *string      `json:"liveVersion,omitempty"`
	TargetVersion *string      `json:"targetVersion,omitempty"`
	UpdatedAt     *metav1.Time `json:"updatedAt,omitempty"`
}

// The environment artifact for a harness, such as a container image containing
// custom dependencies.
type HarnessEnvironmentArtifact struct {
	// Representation of a container configuration.
	ContainerConfiguration *ContainerConfiguration `json:"containerConfiguration,omitempty"`
}

// The environment provider for a harness.
type HarnessEnvironmentProvider struct {
	// The AgentCore Runtime environment for a harness.
	AgentCoreRuntimeEnvironment *HarnessAgentCoreRuntimeEnvironment `json:"agentCoreRuntimeEnvironment,omitempty"`
}

// The environment provider request configuration.
type HarnessEnvironmentProviderRequest struct {
	// The AgentCore Runtime environment request configuration.
	AgentCoreRuntimeEnvironment *HarnessAgentCoreRuntimeEnvironmentRequest `json:"agentCoreRuntimeEnvironment,omitempty"`
}

// Authentication method for calling a Gateway.
type HarnessGatewayOutboundAuth struct {
	AWSIAM map[string]*string `json:"awsIAM,omitempty"`
	None   map[string]*string `json:"none,omitempty"`
	// An OAuth credential provider for gateway authentication. This structure contains
	// the configuration for authenticating with the target endpoint using OAuth.
	Oauth *OAuthCredentialProvider `json:"oauth,omitempty"`
}

// Configuration for a Google Gemini model provider. Requires an API key stored
// in AgentCore Identity.
type HarnessGeminiModelConfig struct {
	APIKeyARN   *string  `json:"apiKeyARN,omitempty"`
	MaxTokens   *int64   `json:"maxTokens,omitempty"`
	ModelID     *string  `json:"modelID,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
	TopK        *int64   `json:"topK,omitempty"`
	TopP        *float64 `json:"topP,omitempty"`
}

// Configuration for an inline function tool. When the agent calls this tool,
// the tool call is returned to the caller for external execution.
type HarnessInlineFunctionConfig struct {
	Description *string `json:"description,omitempty"`
}

// Configuration for a LiteLLM model provider, enabling connection to third-party
// model providers.
type HarnessLiteLlmModelConfig struct {
	APIBase     *string  `json:"apiBase,omitempty"`
	APIKeyARN   *string  `json:"apiKeyARN,omitempty"`
	MaxTokens   *int64   `json:"maxTokens,omitempty"`
	ModelID     *string  `json:"modelID,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
	TopP        *float64 `json:"topP,omitempty"`
}

// Configuration for managed memory creation.
type HarnessManagedMemoryConfiguration struct {
	EncryptionKeyARN    *string   `json:"encryptionKeyARN,omitempty"`
	EventExpiryDuration *int64    `json:"eventExpiryDuration,omitempty"`
	Strategies          []*string `json:"strategies,omitempty"`
}

// The memory configuration for a harness.
type HarnessMemoryConfiguration struct {
	// Configuration for AgentCore Memory integration.
	AgentCoreMemoryConfiguration *HarnessAgentCoreMemoryConfiguration `json:"agentCoreMemoryConfiguration,omitempty"`
	// Explicitly opt out of memory.
	Disabled map[string]*string `json:"disabled,omitempty"`
	// Configuration for managed memory creation.
	ManagedMemoryConfiguration *HarnessManagedMemoryConfiguration `json:"managedMemoryConfiguration,omitempty"`
}

// Specification of which model to use.
type HarnessModelConfiguration struct {
	// Configuration for an Amazon Bedrock model provider.
	BedrockModelConfig *HarnessBedrockModelConfig `json:"bedrockModelConfig,omitempty"`
	// Configuration for a Google Gemini model provider. Requires an API key stored
	// in AgentCore Identity.
	GeminiModelConfig *HarnessGeminiModelConfig `json:"geminiModelConfig,omitempty"`
	// Configuration for a LiteLLM model provider, enabling connection to third-party
	// model providers.
	LiteLlmModelConfig *HarnessLiteLlmModelConfig `json:"liteLlmModelConfig,omitempty"`
	// Configuration for an OpenAI model provider. Requires an API key stored in
	// AgentCore Identity.
	OpenAiModelConfig *HarnessOpenAiModelConfig `json:"openAiModelConfig,omitempty"`
}

// Configuration for an OpenAI model provider. Requires an API key stored in
// AgentCore Identity.
type HarnessOpenAiModelConfig struct {
	APIFormat   *string  `json:"apiFormat,omitempty"`
	APIKeyARN   *string  `json:"apiKeyARN,omitempty"`
	MaxTokens   *int64   `json:"maxTokens,omitempty"`
	ModelID     *string  `json:"modelID,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
	TopP        *float64 `json:"topP,omitempty"`
}

// Configuration for connecting to a remote MCP server.
type HarnessRemoteMcpConfig struct {
	// Map of key/value pairs for HTTP headers.
	Headers map[string]*string `json:"headers,omitempty"`
	URL     *string            `json:"url,omitempty"`
}

// A skill available to the agent.
type HarnessSkill struct {
	// Passed to show that AWS Skills should be included.
	AWSSkills *HarnessSkillAWSSkillsSource `json:"awsSkills,omitempty"`
	// A git repository source for a skill.
	Git  *HarnessSkillGitSource `json:"git,omitempty"`
	Path *string                `json:"path,omitempty"`
	// An S3 source for a skill.
	S3 *HarnessSkillS3Source `json:"s3,omitempty"`
}

// Passed to show that AWS Skills should be included.
type HarnessSkillAWSSkillsSource struct {
	Paths []*string `json:"paths,omitempty"`
}

// Authentication configuration for accessing a private git repository.
type HarnessSkillGitAuth struct {
	CredentialARN *string `json:"credentialARN,omitempty"`
	Username      *string `json:"username,omitempty"`
}

// A git repository source for a skill.
type HarnessSkillGitSource struct {
	// Authentication configuration for accessing a private git repository.
	Auth *HarnessSkillGitAuth `json:"auth,omitempty"`
	Path *string              `json:"path,omitempty"`
	URL  *string              `json:"url,omitempty"`
}

// An S3 source for a skill.
type HarnessSkillS3Source struct {
	URI *string `json:"uri,omitempty"`
}

// Configuration for sliding window truncation strategy.
type HarnessSlidingWindowConfiguration struct {
	MessagesCount *int64 `json:"messagesCount,omitempty"`
}

// Configuration for summarization-based truncation strategy.
type HarnessSummarizationConfiguration struct {
	PreserveRecentMessages    *int64   `json:"preserveRecentMessages,omitempty"`
	SummarizationSystemPrompt *string  `json:"summarizationSystemPrompt,omitempty"`
	SummaryRatio              *float64 `json:"summaryRatio,omitempty"`
}

// Summary information about a harness.
type HarnessSummary struct {
	ARN            *string      `json:"arn,omitempty"`
	CreatedAt      *metav1.Time `json:"createdAt,omitempty"`
	HarnessID      *string      `json:"harnessID,omitempty"`
	HarnessName    *string      `json:"harnessName,omitempty"`
	HarnessVersion *string      `json:"harnessVersion,omitempty"`
	Status         *string      `json:"status,omitempty"`
	UpdatedAt      *metav1.Time `json:"updatedAt,omitempty"`
}

// A content block in the system prompt.
type HarnessSystemContentBlock struct {
	Text *string `json:"text,omitempty"`
}

// A tool available to the agent loop.
type HarnessTool struct {
	// Configuration union for different tool types.
	Config *HarnessToolConfiguration `json:"config,omitempty"`
	Name   *string                   `json:"name,omitempty"`
	Type   *string                   `json:"type_,omitempty"`
}

// Configuration union for different tool types.
type HarnessToolConfiguration struct {
	// Configuration for AgentCore Browser.
	AgentCoreBrowser *HarnessAgentCoreBrowserConfig `json:"agentCoreBrowser,omitempty"`
	// Configuration for AgentCore Code Interpreter.
	AgentCoreCodeInterpreter *HarnessAgentCoreCodeInterpreterConfig `json:"agentCoreCodeInterpreter,omitempty"`
	// Configuration for AgentCore Gateway.
	AgentCoreGateway *HarnessAgentCoreGatewayConfig `json:"agentCoreGateway,omitempty"`
	// Configuration for an inline function tool. When the agent calls this tool,
	// the tool call is returned to the caller for external execution.
	InlineFunction *HarnessInlineFunctionConfig `json:"inlineFunction,omitempty"`
	// Configuration for connecting to a remote MCP server.
	RemoteMcp *HarnessRemoteMcpConfig `json:"remoteMcp,omitempty"`
}

// Configuration for truncating conversation context when it exceeds model limits.
type HarnessTruncationConfiguration struct {
	// Strategy-specific truncation configuration.
	Config   *HarnessTruncationStrategyConfiguration `json:"config,omitempty"`
	Strategy *string                                 `json:"strategy,omitempty"`
}

// Strategy-specific truncation configuration.
type HarnessTruncationStrategyConfiguration struct {
	// Configuration for sliding window truncation strategy.
	SlidingWindow *HarnessSlidingWindowConfiguration `json:"slidingWindow,omitempty"`
	// Configuration for summarization-based truncation strategy.
	Summarization *HarnessSummarizationConfiguration `json:"summarization,omitempty"`
}

// Summary information about a single version of a harness.
type HarnessVersionSummary struct {
	ARN            *string      `json:"arn,omitempty"`
	CreatedAt      *metav1.Time `json:"createdAt,omitempty"`
	FailureReason  *string      `json:"failureReason,omitempty"`
	HarnessID      *string      `json:"harnessID,omitempty"`
	HarnessName    *string      `json:"harnessName,omitempty"`
	HarnessVersion *string      `json:"harnessVersion,omitempty"`
	Status         *string      `json:"status,omitempty"`
	UpdatedAt      *metav1.Time `json:"updatedAt,omitempty"`
}

// Representation of a harness.
type Harness_SDK struct {
	AllowedTools []*string `json:"allowedTools,omitempty"`
	ARN          *string   `json:"arn,omitempty"`
	// Represents inbound authorization configuration options used to authenticate
	// incoming requests.
	AuthorizerConfiguration *AuthorizerConfiguration `json:"authorizerConfiguration,omitempty"`
	CreatedAt               *metav1.Time             `json:"createdAt,omitempty"`
	// The environment provider for a harness.
	Environment *HarnessEnvironmentProvider `json:"environment,omitempty"`
	// The environment artifact for a harness, such as a container image containing
	// custom dependencies.
	EnvironmentArtifact  *HarnessEnvironmentArtifact `json:"environmentArtifact,omitempty"`
	EnvironmentVariables map[string]*string          `json:"environmentVariables,omitempty"`
	ExecutionRoleARN     *string                     `json:"executionRoleARN,omitempty"`
	FailureReason        *string                     `json:"failureReason,omitempty"`
	HarnessID            *string                     `json:"harnessID,omitempty"`
	HarnessName          *string                     `json:"harnessName,omitempty"`
	HarnessVersion       *string                     `json:"harnessVersion,omitempty"`
	MaxIterations        *int64                      `json:"maxIterations,omitempty"`
	MaxTokens            *int64                      `json:"maxTokens,omitempty"`
	// The memory configuration for a harness.
	Memory *HarnessMemoryConfiguration `json:"memory,omitempty"`
	// Specification of which model to use.
	Model          *HarnessModelConfiguration   `json:"model,omitempty"`
	Skills         []*HarnessSkill              `json:"skills,omitempty"`
	Status         *string                      `json:"status,omitempty"`
	SystemPrompt   []*HarnessSystemContentBlock `json:"systemPrompt,omitempty"`
	TimeoutSeconds *int64                       `json:"timeoutSeconds,omitempty"`
	Tools          []*HarnessTool               `json:"tools,omitempty"`
	// Configuration for truncating conversation context when it exceeds model limits.
	Truncation *HarnessTruncationConfiguration `json:"truncation,omitempty"`
	UpdatedAt  *metav1.Time                    `json:"updatedAt,omitempty"`
}

// A hosting environment whose workloads are allowed to invoke the target. At
// launch, the only supported hosting environment is AgentCore Gateway.
type HostingEnvironment struct {
	ARN *string `json:"arn,omitempty"`
}

// An IAM credential provider for gateway authentication. This structure contains
// the configuration for authenticating with the target endpoint using IAM credentials
// and SigV4 signing.
type IAMCredentialProvider struct {
	Region  *string `json:"region,omitempty"`
	Service *string `json:"service,omitempty"`
}

// The configuration parameters that control how the foundation model behaves
// during evaluation, including response generation settings.
type InferenceConfiguration struct {
	MaxTokens   *int64   `json:"maxTokens,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
	TopP        *float64 `json:"topP,omitempty"`
}

// The interceptor configuration.
type InterceptorConfiguration struct {
	// The lambda configuration for the interceptor
	Lambda *LambdaInterceptorConfiguration `json:"lambda,omitempty"`
}

// The input configuration of the interceptor.
type InterceptorInputConfiguration struct {
	PassRequestHeaders *bool `json:"passRequestHeaders,omitempty"`
}

// The configuration to invoke a self-managed memory processing pipeline with.
type InvocationConfiguration struct {
	PayloadDeliveryBucketName *string `json:"payloadDeliveryBucketName,omitempty"`
	TopicARN                  *string `json:"topicARN,omitempty"`
}

// The configuration to invoke a self-managed memory processing pipeline with.
type InvocationConfigurationInput struct {
	PayloadDeliveryBucketName *string `json:"payloadDeliveryBucketName,omitempty"`
	TopicARN                  *string `json:"topicARN,omitempty"`
	// Reference field for TopicARN
	TopicRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"topicRef,omitempty"`
}

// Contains the KMS configuration for a resource.
type KMSConfiguration struct {
	KMSKeyARN *string `json:"kmsKeyARN,omitempty"`
}

// Configuration for Kinesis Data Stream delivery.
type KinesisResource struct {
	ContentConfigurations []*ContentConfiguration `json:"contentConfigurations,omitempty"`
	DataStreamARN         *string                 `json:"dataStreamARN,omitempty"`
}

// Configuration for a Lambda function used as a code-based evaluator.
type LambdaEvaluatorConfig struct {
	LambdaTimeoutInSeconds *int64 `json:"lambdaTimeoutInSeconds,omitempty"`
}

// The lambda configuration for the interceptor
type LambdaInterceptorConfiguration struct {
	ARN *string `json:"arn,omitempty"`
}

// The Lambda configuration for custom transformations. This structure defines
// the Lambda function that the gateway invokes to transform data.
type LambdaTransformConfiguration struct {
	ARN *string `json:"arn,omitempty"`
}

// LifecycleConfiguration lets you manage the lifecycle of runtime sessions
// and resources in AgentCore Runtime. This configuration helps optimize resource
// utilization by automatically cleaning up idle sessions and preventing long-running
// instances from consuming resources indefinitely.
type LifecycleConfiguration struct {
	IdleRuntimeSessionTimeout *int64 `json:"idleRuntimeSessionTimeout,omitempty"`
	MaxLifetime               *int64 `json:"maxLifetime,omitempty"`
}

// The configuration for a Model Context Protocol (MCP) gateway. This structure
// defines how the gateway implements the MCP protocol.
type MCPGatewayConfiguration struct {
	Instructions      *string   `json:"instructions,omitempty"`
	SearchType        *string   `json:"searchType,omitempty"`
	SupportedVersions []*string `json:"supportedVersions,omitempty"`
}

// Configuration for a managed VPC Lattice resource. The gateway creates and
// manages the VPC Lattice resource gateway and resource configuration on your
// behalf using a service-linked role.
type ManagedVPCResource struct {
	Tags map[string]*string `json:"tags,omitempty"`
}

// The Lambda configuration for a Model Context Protocol target. This structure
// defines how the gateway uses a Lambda function to communicate with the target.
type McpLambdaTargetConfiguration struct {
	LambdaARN *string `json:"lambdaARN,omitempty"`
	// A tool schema for a gateway target. This structure defines the schema for
	// a tool that the target exposes through the Model Context Protocol.
	ToolSchema *ToolSchema `json:"toolSchema,omitempty"`
}

// The target configuration for the MCP server.
type McpServerTargetConfiguration struct {
	Endpoint *string `json:"endpoint,omitempty"`
}

// The Model Context Protocol (MCP) configuration for a target. This structure
// defines how the gateway uses MCP to communicate with the target.
type McpTargetConfiguration struct {
	// The configuration for an Amazon API Gateway target.
	APIGateway *APIGatewayTargetConfiguration `json:"apiGateway,omitempty"`
	// The Lambda configuration for a Model Context Protocol target. This structure
	// defines how the gateway uses a Lambda function to communicate with the target.
	Lambda *McpLambdaTargetConfiguration `json:"lambda,omitempty"`
	// The target configuration for the MCP server.
	McpServer *McpServerTargetConfiguration `json:"mcpServer,omitempty"`
	// Configuration for API schema.
	OpenAPISchema *APISchemaConfiguration `json:"openAPISchema,omitempty"`
	// Configuration for API schema.
	SmithyModel *APISchemaConfiguration `json:"smithyModel,omitempty"`
}

// The MCP tool schema configuration for an MCP server target. The tool schema
// must be aligned with the MCP specification.
type McpToolSchemaConfiguration struct {
	InlinePayload *string `json:"inlinePayload,omitempty"`
	// The Amazon S3 configuration for a gateway. This structure defines how the
	// gateway accesses files in Amazon S3.
	S3 *S3Configuration `json:"s3,omitempty"`
}

// Contains information about a memory strategy.
type MemoryStrategy struct {
	CreatedAt  *metav1.Time `json:"createdAt,omitempty"`
	Name       *string      `json:"name,omitempty"`
	Status     *string      `json:"status,omitempty"`
	StrategyID *string      `json:"strategyID,omitempty"`
	Type       *string      `json:"type_,omitempty"`
	UpdatedAt  *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains input information for creating a memory strategy.
type MemoryStrategyInput struct {
	// Input for creating a custom memory strategy.
	CustomMemoryStrategy *CustomMemoryStrategyInput `json:"customMemoryStrategy,omitempty"`
	// Input for creating an episodic memory strategy.
	EpisodicMemoryStrategy *EpisodicMemoryStrategyInput `json:"episodicMemoryStrategy,omitempty"`
	// Input for creating a semantic memory strategy.
	SemanticMemoryStrategy *SemanticMemoryStrategyInput `json:"semanticMemoryStrategy,omitempty"`
	// Input for creating a summary memory strategy.
	SummaryMemoryStrategy *SummaryMemoryStrategyInput `json:"summaryMemoryStrategy,omitempty"`
	// Input for creating a user preference memory strategy.
	UserPreferenceMemoryStrategy *UserPreferenceMemoryStrategyInput `json:"userPreferenceMemoryStrategy,omitempty"`
}

// Contains summary information about a memory resource.
type MemorySummary struct {
	ARN                  *string      `json:"arn,omitempty"`
	CreatedAt            *metav1.Time `json:"createdAt,omitempty"`
	ID                   *string      `json:"id,omitempty"`
	ManagedByResourceARN *string      `json:"managedByResourceARN,omitempty"`
	Status               *string      `json:"status,omitempty"`
	UpdatedAt            *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains information about a memory resource.
type Memory_SDK struct {
	ARN                    *string           `json:"arn,omitempty"`
	CreatedAt              *metav1.Time      `json:"createdAt,omitempty"`
	Description            *string           `json:"description,omitempty"`
	EncryptionKeyARN       *string           `json:"encryptionKeyARN,omitempty"`
	EventExpiryDuration    *int64            `json:"eventExpiryDuration,omitempty"`
	FailureReason          *string           `json:"failureReason,omitempty"`
	ID                     *string           `json:"id,omitempty"`
	MemoryExecutionRoleARN *string           `json:"memoryExecutionRoleARN,omitempty"`
	Name                   *string           `json:"name,omitempty"`
	Status                 *string           `json:"status,omitempty"`
	Strategies             []*MemoryStrategy `json:"strategies,omitempty"`
	// Configuration for streaming memory record data to external resources.
	StreamDeliveryResources *StreamDeliveryResources `json:"streamDeliveryResources,omitempty"`
	UpdatedAt               *metav1.Time             `json:"updatedAt,omitempty"`
}

// The trigger configuration based on a message.
type MessageBasedTrigger struct {
	MessageCount *int64 `json:"messageCount,omitempty"`
}

// The trigger configuration based on a message.
type MessageBasedTriggerInput struct {
	MessageCount *int64 `json:"messageCount,omitempty"`
}

// Configuration for HTTP header and query parameter propagation between the
// gateway and target servers.
type MetadataConfiguration struct {
	AllowedQueryParameters []*string `json:"allowedQueryParameters,omitempty"`
	AllowedRequestHeaders  []*string `json:"allowedRequestHeaders,omitempty"`
	AllowedResponseHeaders []*string `json:"allowedResponseHeaders,omitempty"`
}

// The configuration for updating invocation settings.
type ModifyInvocationConfigurationInput struct {
	PayloadDeliveryBucketName *string `json:"payloadDeliveryBucketName,omitempty"`
	TopicARN                  *string `json:"topicARN,omitempty"`
}

// Contains information for modifying memory strategies.
type ModifyMemoryStrategies struct {
	AddMemoryStrategies []*MemoryStrategyInput `json:"addMemoryStrategies,omitempty"`
}

// Input for modifying a memory strategy.
type ModifyMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	MemoryStrategyID   *string   `json:"memoryStrategyID,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Contains information for modifying a reflection configuration.
type ModifyReflectionConfiguration struct {
	// An episodic reflection configuration input.
	EpisodicReflectionConfiguration *EpisodicReflectionConfigurationInput `json:"episodicReflectionConfiguration,omitempty"`
}

// The configuration for updating the self-managed memory strategy.
type ModifySelfManagedConfiguration struct {
	HistoricalContextWindowSize *int64                   `json:"historicalContextWindowSize,omitempty"`
	TriggerConditions           []*TriggerConditionInput `json:"triggerConditions,omitempty"`
}

// SecurityConfig for the Agent.
type NetworkConfiguration struct {
	NetworkMode *string `json:"networkMode,omitempty"`
	// VpcConfig for the Agent.
	NetworkModeConfig *VPCConfig `json:"networkModeConfig,omitempty"`
}

// The definition of a numerical rating scale option that provides a numeric
// value with its description for evaluation scoring.
type NumericalScaleDefinition struct {
	Definition *string `json:"definition,omitempty"`
	Label      *string `json:"label,omitempty"`
}

// OAuth2-specific authorization data, including the authorization URL and user
// identifier for the authorization session.
type OAuth2AuthorizationData struct {
	AuthorizationURL *string `json:"authorizationURL,omitempty"`
	UserID           *string `json:"userID,omitempty"`
}

// An OAuth credential provider for gateway authentication. This structure contains
// the configuration for authenticating with the target endpoint using OAuth.
type OAuthCredentialProvider struct {
	CustomParameters map[string]*string `json:"customParameters,omitempty"`
	DefaultReturnURL *string            `json:"defaultReturnURL,omitempty"`
	GrantType        *string            `json:"grantType,omitempty"`
	ProviderARN      *string            `json:"providerARN,omitempty"`
	Scopes           []*string          `json:"scopes,omitempty"`
}

// Contains information about an OAuth2 credential provider.
type Oauth2CredentialProviderItem struct {
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	Name            *string      `json:"name,omitempty"`
}

// The summary information about an online evaluation configuration, including
// basic metadata and execution status.
type OnlineEvaluationConfigSummary struct {
	CreatedAt     *metav1.Time `json:"createdAt,omitempty"`
	FailureReason *string      `json:"failureReason,omitempty"`
	UpdatedAt     *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains summary information about a payment connector.
type PaymentConnectorSummary struct {
	LastUpdatedAt *metav1.Time `json:"lastUpdatedAt,omitempty"`
}

// Contains summary information about a payment credential provider.
type PaymentCredentialProviderItem struct {
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	Name            *string      `json:"name,omitempty"`
}

// Contains summary information about a payment manager.
type PaymentManagerSummary struct {
	CreatedAt     *metav1.Time `json:"createdAt,omitempty"`
	LastUpdatedAt *metav1.Time `json:"lastUpdatedAt,omitempty"`
	RoleARN       *string      `json:"roleARN,omitempty"`
}

// Represents the definition structure for policies within the AgentCore Policy
// system. This structure encapsulates different policy formats and languages
// that can be used to define access control rules.
type PolicyDefinition struct {
	// Represents a Cedar policy statement within the AgentCore Policy system. Cedar
	// is a policy language designed for authorization that provides human-readable,
	// analyzable, and high-performance policy evaluation for controlling agent
	// behavior and access decisions.
	Cedar *CedarPolicy `json:"cedar,omitempty"`
}

// Represents a metadata-only summary of a policy engine resource. This structure
// contains resource identifiers, status, and timestamps without customer-encrypted
// fields such as description or status reasons. Policy engine summaries are
// returned by operations that do not require access to the customer's KMS key.
type PolicyEngineSummary struct {
	CreatedAt        *metav1.Time `json:"createdAt,omitempty"`
	EncryptionKeyARN *string      `json:"encryptionKeyARN,omitempty"`
	Name             *string      `json:"name,omitempty"`
	PolicyEngineARN  *string      `json:"policyEngineARN,omitempty"`
	PolicyEngineID   *string      `json:"policyEngineID,omitempty"`
	Status           *string      `json:"status,omitempty"`
	UpdatedAt        *metav1.Time `json:"updatedAt,omitempty"`
}

// Represents a policy engine resource within the AgentCore Policy system. Policy
// engines serve as containers for grouping related policies and provide the
// execution context for policy evaluation and management. Each policy engine
// can be associated with one Gateway (one engine per Gateway), where it intercepts
// all agent tool calls and evaluates them against the contained policies before
// allowing tools to execute. The policy engine maintains the Cedar schema generated
// from the Gateway's tool manifest, ensuring that policies are validated against
// the actual tools and parameters available. Policy engines support two enforcement
// modes that can be configured when associating with a Gateway: log-only mode
// for testing (evaluates decisions without blocking) and enforce mode for production
// (actively allows or denies based on policy evaluation).
type PolicyEngine_SDK struct {
	CreatedAt        *metav1.Time `json:"createdAt,omitempty"`
	Description      *string      `json:"description,omitempty"`
	EncryptionKeyARN *string      `json:"encryptionKeyARN,omitempty"`
	Name             *string      `json:"name,omitempty"`
	PolicyEngineARN  *string      `json:"policyEngineARN,omitempty"`
	PolicyEngineID   *string      `json:"policyEngineID,omitempty"`
	Status           *string      `json:"status,omitempty"`
	StatusReasons    []*string    `json:"statusReasons,omitempty"`
	UpdatedAt        *metav1.Time `json:"updatedAt,omitempty"`
}

// Represents a policy generation request within the AgentCore Policy system.
// Tracks the AI-powered conversion of natural language descriptions into Cedar
// policy statements, enabling users to author policies by describing authorization
// requirements in plain English. The generation process analyzes the natural
// language input along with the Gateway's tool context and Cedar schema to
// produce one or more validated policy options. Each generation request tracks
// the status of the conversion process and maintains findings about the generated
// policies, including validation results and potential issues. Generated policy
// assets remain available for one week after successful generation, allowing
// time to review and create policies from the generated options.
type PolicyGeneration struct {
	CreatedAt          *metav1.Time `json:"createdAt,omitempty"`
	Findings           *string      `json:"findings,omitempty"`
	PolicyEngineID     *string      `json:"policyEngineID,omitempty"`
	PolicyGenerationID *string      `json:"policyGenerationID,omitempty"`
	StatusReasons      []*string    `json:"statusReasons,omitempty"`
	UpdatedAt          *metav1.Time `json:"updatedAt,omitempty"`
}

// Represents a generated policy asset from the AI-powered policy generation
// process within the AgentCore Policy system. Each asset contains a Cedar policy
// statement generated from natural language input, along with associated metadata
// and analysis findings to help users evaluate and select the most appropriate
// policy option.
type PolicyGenerationAsset struct {
	// Represents the definition structure for policies within the AgentCore Policy
	// system. This structure encapsulates different policy formats and languages
	// that can be used to define access control rules.
	Definition              *PolicyDefinition `json:"definition,omitempty"`
	PolicyGenerationAssetID *string           `json:"policyGenerationAssetID,omitempty"`
}

// Represents the information identifying a generated policy asset from the
// AI-powered policy generation process within the AgentCore Policy system.
// Each asset contains a Cedar policy statement generated from natural language
// input, along with associated metadata and analysis findings to help users
// evaluate and select the most appropriate policy option.
type PolicyGenerationDetails struct {
	PolicyGenerationAssetID *string `json:"policyGenerationAssetID,omitempty"`
	PolicyGenerationID      *string `json:"policyGenerationID,omitempty"`
}

// Represents a metadata-only summary of a policy generation resource. This
// structure contains resource identifiers, status, timestamps, and findings
// without customer-encrypted fields such as status reasons. Policy generation
// summaries are returned by operations that do not require access to the customer's
// KMS key.
type PolicyGenerationSummary struct {
	CreatedAt          *metav1.Time `json:"createdAt,omitempty"`
	Findings           *string      `json:"findings,omitempty"`
	PolicyEngineID     *string      `json:"policyEngineID,omitempty"`
	PolicyGenerationID *string      `json:"policyGenerationID,omitempty"`
	UpdatedAt          *metav1.Time `json:"updatedAt,omitempty"`
}

// An AgentCore policy statement, which supports plain Cedar policies as well
// as guardrails definitions.
type PolicyStatement struct {
	Statement *string `json:"statement,omitempty"`
}

// Represents a metadata-only summary of a policy resource. This structure contains
// resource identifiers, status, and timestamps without customer-encrypted fields
// such as definition, description, or status reasons. Policy summaries are
// returned by operations that do not require access to the customer's KMS key.
type PolicySummary struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The enforcement mode for a policy. Run this policy in LOG_ONLY mode to collect
	// data on how it affects your application. Once you are satisfied with the
	// data gathered, switch the policy to ACTIVE.
	EnforcementMode *string      `json:"enforcementMode,omitempty"`
	Name            *string      `json:"name,omitempty"`
	PolicyARN       *string      `json:"policyARN,omitempty"`
	PolicyEngineID  *string      `json:"policyEngineID,omitempty"`
	PolicyID        *string      `json:"policyID,omitempty"`
	Status          *string      `json:"status,omitempty"`
	UpdatedAt       *metav1.Time `json:"updatedAt,omitempty"`
}

// Represents a complete policy resource within the AgentCore Policy system.
// Policies are ARN-able resources that contain Cedar policy statements and
// associated metadata for controlling agent behavior and access decisions.
// Each policy belongs to a policy engine and defines fine-grained authorization
// rules that are evaluated in real-time as agents interact with tools through
// Gateway. Policies use the Cedar policy language to specify who (principals
// based on OAuth claims like username, role, or scope) can perform what actions
// (tool calls) on which resources (Gateways), with optional conditions for
// attribute-based access control. Multiple policies can apply to a single request,
// with Cedar's forbid-wins semantics ensuring that security restrictions are
// never accidentally overridden.
type Policy_SDK struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// Represents the definition structure for policies within the AgentCore Policy
	// system. This structure encapsulates different policy formats and languages
	// that can be used to define access control rules.
	Definition  *PolicyDefinition `json:"definition,omitempty"`
	Description *string           `json:"description,omitempty"`
	// The enforcement mode for a policy. Run this policy in LOG_ONLY mode to collect
	// data on how it affects your application. Once you are satisfied with the
	// data gathered, switch the policy to ACTIVE.
	EnforcementMode *string      `json:"enforcementMode,omitempty"`
	Name            *string      `json:"name,omitempty"`
	PolicyARN       *string      `json:"policyARN,omitempty"`
	PolicyEngineID  *string      `json:"policyEngineID,omitempty"`
	PolicyID        *string      `json:"policyID,omitempty"`
	Status          *string      `json:"status,omitempty"`
	StatusReasons   []*string    `json:"statusReasons,omitempty"`
	UpdatedAt       *metav1.Time `json:"updatedAt,omitempty"`
}

// The protocol configuration for an agent runtime. This structure defines how
// the agent runtime communicates with clients.
type ProtocolConfiguration struct {
	ServerProtocol *string `json:"serverProtocol,omitempty"`
}

// The configuration that controls how a provider prefix is applied to model
// IDs during translation.
type ProviderPrefix struct {
	Separator *string `json:"separator,omitempty"`
	Strip     *bool   `json:"strip,omitempty"`
}

// The recording configuration for a browser. This structure defines how browser
// sessions are recorded.
type RecordingConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
	// The Amazon S3 location for storing data. This structure defines where in
	// Amazon S3 data is stored.
	S3Location *S3Location `json:"s3Location,omitempty"`
}

// Contains summary information about a registry record.
type RegistryRecordSummary struct {
	CreatedAt   *metav1.Time `json:"createdAt,omitempty"`
	Description *string      `json:"description,omitempty"`
	UpdatedAt   *metav1.Time `json:"updatedAt,omitempty"`
}

// Contains summary information about a registry.
type RegistrySummary struct {
	CreatedAt    *metav1.Time `json:"createdAt,omitempty"`
	Description  *string      `json:"description,omitempty"`
	StatusReason *string      `json:"statusReason,omitempty"`
	UpdatedAt    *metav1.Time `json:"updatedAt,omitempty"`
}

// Configuration for HTTP request headers that will be passed through to the
// runtime.
type RequestHeaderConfiguration struct {
	RequestHeaderAllowlist []*string `json:"requestHeaderAllowlist,omitempty"`
}

// Represents a resource within the AgentCore Policy system. Resources are the
// targets of policy evaluation. Currently, only AgentCore Gateways are supported
// as resources for policy enforcement.
type Resource struct {
	ARN *string `json:"arn,omitempty"`
}

// The location of a resource.
type ResourceLocation struct {
	// The Amazon S3 location for storing data. This structure defines where in
	// Amazon S3 data is stored.
	S3 *S3Location `json:"s3,omitempty"`
}

// Configuration for microVM metadata service settings.
type RuntimeMetadataConfiguration struct {
	RequireMMDSV2 *bool `json:"requireMMDSV2,omitempty"`
}

// The Amazon S3 configuration for a gateway. This structure defines how the
// gateway accesses files in Amazon S3.
type S3Configuration struct {
	BucketOwnerAccountID *string `json:"bucketOwnerAccountID,omitempty"`
	URI                  *string `json:"uri,omitempty"`
}

// Configuration for an Amazon S3 Files access point filesystem mounted into
// the AgentCore Runtime. S3 Files access points provide shared file storage
// accessible from your AgentCore Runtime sessions.
type S3FilesAccessPointConfiguration struct {
	MountPath *string `json:"mountPath,omitempty"`
}

// The Amazon S3 location for storing data. This structure defines where in
// Amazon S3 data is stored.
type S3Location struct {
	Bucket    *string `json:"bucket,omitempty"`
	Prefix    *string `json:"prefix,omitempty"`
	VersionID *string `json:"versionID,omitempty"`
}

// A schema definition for a gateway target. This structure defines the structure
// of the API that the target exposes.
type SchemaDefinition struct {
	Description *string `json:"description,omitempty"`
}

// Contains information about a secret in Amazon Web Services Secrets Manager.
type Secret struct {
	SecretARN *string `json:"secretARN,omitempty"`
}

// The Amazon Web Services Secrets Manager location configuration.
type SecretsManagerLocation struct {
	SecretARN *string `json:"secretARN,omitempty"`
	// Reference field for SecretARN
	SecretRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"secretRef,omitempty"`
}

// A configuration for a self-managed memory strategy.
type SelfManagedConfiguration struct {
	HistoricalContextWindowSize *int64 `json:"historicalContextWindowSize,omitempty"`
}

// Input configuration for a self-managed memory strategy.
type SelfManagedConfigurationInput struct {
	HistoricalContextWindowSize *int64 `json:"historicalContextWindowSize,omitempty"`
	// The configuration to invoke a self-managed memory processing pipeline with.
	InvocationConfiguration *InvocationConfigurationInput `json:"invocationConfiguration,omitempty"`
	TriggerConditions       []*TriggerConditionInput      `json:"triggerConditions,omitempty"`
}

// Contains semantic consolidation override configuration.
type SemanticConsolidationOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Contains semantic extraction override configuration.
type SemanticExtractionOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for creating a semantic memory strategy.
type SemanticMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	Name               *string   `json:"name,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Input for semantic override configuration in a memory strategy.
type SemanticOverrideConfigurationInput struct {
	// Input for semantic override consolidation configuration in a memory strategy.
	Consolidation *SemanticOverrideConsolidationConfigurationInput `json:"consolidation,omitempty"`
	// Input for semantic override extraction configuration in a memory strategy.
	Extraction *SemanticOverrideExtractionConfigurationInput `json:"extraction,omitempty"`
}

// Input for semantic override consolidation configuration in a memory strategy.
type SemanticOverrideConsolidationConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for semantic override extraction configuration in a memory strategy.
type SemanticOverrideExtractionConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// The configuration that defines how agent sessions are detected and when they
// are considered complete for evaluation.
type SessionConfig struct {
	SessionTimeoutMinutes *int64 `json:"sessionTimeoutMinutes,omitempty"`
}

// The session configuration for an MCP gateway. This structure defines settings
// that control session behavior.
type SessionConfiguration struct {
	SessionTimeoutInSeconds *int64 `json:"sessionTimeoutInSeconds,omitempty"`
}

// Configuration for a session storage filesystem mounted into the AgentCore
// Runtime. Session storage provides persistent storage that is preserved across
// AgentCore Runtime session invocations.
type SessionStorageConfiguration struct {
	MountPath *string `json:"mountPath,omitempty"`
}

// A static configuration bundle override.
type StaticOverride struct {
	BundleVersion *string `json:"bundleVersion,omitempty"`
}

// A static route to a single gateway target.
type StaticRoute struct {
	TargetName *string `json:"targetName,omitempty"`
}

// The configuration for session-sticky routing to a target. Session stickiness
// routes requests that share a session identifier to the same target.
type StickinessConfiguration struct {
	Identifier *string `json:"identifier,omitempty"`
}

// Supported stream delivery resource types.
type StreamDeliveryResource struct {
	// Configuration for Kinesis Data Stream delivery.
	Kinesis *KinesisResource `json:"kinesis,omitempty"`
}

// Configuration for streaming memory record data to external resources.
type StreamDeliveryResources struct {
	Resources []*StreamDeliveryResource `json:"resources,omitempty"`
}

// The streaming configuration for an MCP gateway. This structure defines settings
// that control response streaming behavior.
type StreamingConfiguration struct {
	EnableResponseStreaming *bool `json:"enableResponseStreaming,omitempty"`
}

// Validation for STRINGLIST fields.
type StringListValidation struct {
	MaxItems *int64 `json:"maxItems,omitempty"`
}

// Stripe Privy configuration output with secret ARNs.
type StripePrivyConfigurationOutput struct {
	// Contains information about a secret in Amazon Web Services Secrets Manager.
	AppSecretARN *Secret `json:"appSecretARN,omitempty"`
	// Contains information about a secret in Amazon Web Services Secrets Manager.
	AuthorizationPrivateKeyARN *Secret `json:"authorizationPrivateKeyARN,omitempty"`
}

// Contains summary consolidation override configuration.
type SummaryConsolidationOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for creating a summary memory strategy.
type SummaryMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	Name               *string   `json:"name,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Input for summary override configuration in a memory strategy.
type SummaryOverrideConfigurationInput struct {
	// Input for summary override consolidation configuration in a memory strategy.
	Consolidation *SummaryOverrideConsolidationConfigurationInput `json:"consolidation,omitempty"`
}

// Input for summary override consolidation configuration in a memory strategy.
type SummaryOverrideConsolidationConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// System-managed metadata for rules created by automated processes such as
// A/B tests.
type SystemManagedBlock struct {
	ManagedBy *string `json:"managedBy,omitempty"`
}

// The configuration for a gateway target. This structure defines how the gateway
// connects to and interacts with the target endpoint.
type TargetConfiguration struct {
	// The Model Context Protocol (MCP) configuration for a target. This structure
	// defines how the gateway uses MCP to communicate with the target.
	Mcp *McpTargetConfiguration `json:"mcp,omitempty"`
}

// Contains summary information about a gateway target. A target represents
// an endpoint that the gateway can connect to.
type TargetSummary struct {
	// Contains the authorization data that is returned when a gateway target is
	// configured with a credential provider with authorization code grant type
	// and requires user federation.
	AuthorizationData  *AuthorizationData `json:"authorizationData,omitempty"`
	CreatedAt          *metav1.Time       `json:"createdAt,omitempty"`
	Description        *string            `json:"description,omitempty"`
	LastSynchronizedAt *metav1.Time       `json:"lastSynchronizedAt,omitempty"`
	ListingMode        *string            `json:"listingMode,omitempty"`
	Name               *string            `json:"name,omitempty"`
	ResourcePriority   *int64             `json:"resourcePriority,omitempty"`
	Status             *string            `json:"status,omitempty"`
	TargetID           *string            `json:"targetID,omitempty"`
	TargetType         *string            `json:"targetType,omitempty"`
	UpdatedAt          *metav1.Time       `json:"updatedAt,omitempty"`
}

// An entry in a target traffic split configuration.
type TargetTrafficSplitEntry struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	TargetName  *string `json:"targetName,omitempty"`
	Weight      *int64  `json:"weight,omitempty"`
}

// Trigger configuration based on time.
type TimeBasedTrigger struct {
	IdleSessionTimeout *int64 `json:"idleSessionTimeout,omitempty"`
}

// Trigger configuration based on time.
type TimeBasedTriggerInput struct {
	IdleSessionTimeout *int64 `json:"idleSessionTimeout,omitempty"`
}

// Trigger configuration based on tokens.
type TokenBasedTrigger struct {
	TokenCount *int64 `json:"tokenCount,omitempty"`
}

// Trigger configuration based on tokens.
type TokenBasedTriggerInput struct {
	TokenCount *int64 `json:"tokenCount,omitempty"`
}

// A tool definition for a gateway target. This structure defines a tool that
// the target exposes through the Model Context Protocol.
type ToolDefinition struct {
	Description  *string `json:"description,omitempty"`
	InputSchema  *string `json:"inputSchema,omitempty"`
	Name         *string `json:"name,omitempty"`
	OutputSchema *string `json:"outputSchema,omitempty"`
}

// A tool schema for a gateway target. This structure defines the schema for
// a tool that the target exposes through the Model Context Protocol.
type ToolSchema struct {
	InlinePayload []*ToolDefinition `json:"inlinePayload,omitempty"`
	// The Amazon S3 configuration for a gateway. This structure defines how the
	// gateway accesses files in Amazon S3.
	S3 *S3Configuration `json:"s3,omitempty"`
}

// An entry in a traffic split configuration, defining a named variant with
// a weight and configuration bundle reference.
type TrafficSplitEntry struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Weight      *int64  `json:"weight,omitempty"`
}

// Condition that triggers memory processing.
type TriggerConditionInput struct {
	// The trigger configuration based on a message.
	MessageBasedTrigger *MessageBasedTriggerInput `json:"messageBasedTrigger,omitempty"`
	// Trigger configuration based on time.
	TimeBasedTrigger *TimeBasedTriggerInput `json:"timeBasedTrigger,omitempty"`
	// Trigger configuration based on tokens.
	TokenBasedTrigger *TokenBasedTriggerInput `json:"tokenBasedTrigger,omitempty"`
}

// Wrapper for updating an optional AuthorizerConfiguration field with PATCH
// semantics. When present in an update request, the authorizer configuration
// is replaced with optionalValue. When absent, the authorizer configuration
// is left unchanged. To unset, include the wrapper with optionalValue not specified.
type UpdatedAuthorizerConfiguration struct {
	// Represents inbound authorization configuration options used to authenticate
	// incoming requests.
	OptionalValue *AuthorizerConfiguration `json:"optionalValue,omitempty"`
}

// Wrapper for updating an optional Description field with PATCH semantics.
// When present in an update request, the description is replaced with optionalValue.
// When absent, the description is left unchanged. To unset the description,
// include the wrapper with optionalValue not specified.
type UpdatedDescription struct {
	OptionalValue *string `json:"optionalValue,omitempty"`
}

// Wrapper for updating the environment artifact configuration.
type UpdatedHarnessEnvironmentArtifact struct {
	// The environment artifact for a harness, such as a container image containing
	// custom dependencies.
	OptionalValue *HarnessEnvironmentArtifact `json:"optionalValue,omitempty"`
}

// Wrapper for updating the memory configuration.
type UpdatedHarnessMemoryConfiguration struct {
	// The memory configuration for a harness.
	OptionalValue *HarnessMemoryConfiguration `json:"optionalValue,omitempty"`
}

// Contains user preference consolidation override configuration.
type UserPreferenceConsolidationOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Contains user preference extraction override configuration.
type UserPreferenceExtractionOverride struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for creating a user preference memory strategy.
type UserPreferenceMemoryStrategyInput struct {
	Description        *string   `json:"description,omitempty"`
	Name               *string   `json:"name,omitempty"`
	NamespaceTemplates []*string `json:"namespaceTemplates,omitempty"`
	Namespaces         []*string `json:"namespaces,omitempty"`
}

// Input for user preference override configuration in a memory strategy.
type UserPreferenceOverrideConfigurationInput struct {
	// Input for user preference override consolidation configuration in a memory
	// strategy.
	Consolidation *UserPreferenceOverrideConsolidationConfigurationInput `json:"consolidation,omitempty"`
	// Input for user preference override extraction configuration in a memory strategy.
	Extraction *UserPreferenceOverrideExtractionConfigurationInput `json:"extraction,omitempty"`
}

// Input for user preference override consolidation configuration in a memory
// strategy.
type UserPreferenceOverrideConsolidationConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// Input for user preference override extraction configuration in a memory strategy.
type UserPreferenceOverrideExtractionConfigurationInput struct {
	AppendToPrompt *string `json:"appendToPrompt,omitempty"`
	ModelID        *string `json:"modelID,omitempty"`
}

// VpcConfig for the Agent.
type VPCConfig struct {
	// Reference field for SecurityGroups
	SecurityGroupRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"securityGroupRefs,omitempty"`
	SecurityGroups    []*string                                  `json:"securityGroups,omitempty"`
	// Reference field for Subnets
	SubnetRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"subnetRefs,omitempty"`
	Subnets    []*string                                  `json:"subnets,omitempty"`
}

// Stores information about a field passed inside a request that resulted in
// an exception.
type ValidationExceptionField struct {
	Message *string `json:"message,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// The source that created a configuration bundle version.
type VersionCreatedBySource struct {
	ARN  *string `json:"arn,omitempty"`
	Name *string `json:"name,omitempty"`
}

// A filter for listing configuration bundle versions.
type VersionFilter struct {
	CreatedByName   *string `json:"createdByName,omitempty"`
	LatestPerBranch *bool   `json:"latestPerBranch,omitempty"`
}

// The version lineage metadata that tracks parent versions and creation source.
// Supports git-like two-parent merges for branch management.
type VersionLineageMetadata struct {
	CommitMessage *string `json:"commitMessage,omitempty"`
}

// The information about the workload identity.
type WorkloadIdentityDetails struct {
	WorkloadIdentityARN *string `json:"workloadIdentityARN,omitempty"`
}

// Contains information about a workload identity.
type WorkloadIdentityType struct {
	Name                *string `json:"name,omitempty"`
	WorkloadIdentityARN *string `json:"workloadIdentityARN,omitempty"`
}
