//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIGatewayTargetConfiguration) DeepCopyInto(out *APIGatewayTargetConfiguration) {
	*out = *in
	if in.RestAPIID != nil {
		in, out := &in.RestAPIID, &out.RestAPIID
		*out = new(string)
		**out = **in
	}
	if in.RestAPIRef != nil {
		in, out := &in.RestAPIRef, &out.RestAPIRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.Stage != nil {
		in, out := &in.Stage, &out.Stage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewayTargetConfiguration.
func (in *APIGatewayTargetConfiguration) DeepCopy() *APIGatewayTargetConfiguration {
	if in == nil {
		return nil
	}
	out := new(APIGatewayTargetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIGatewayToolFilter) DeepCopyInto(out *APIGatewayToolFilter) {
	*out = *in
	if in.FilterPath != nil {
		in, out := &in.FilterPath, &out.FilterPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewayToolFilter.
func (in *APIGatewayToolFilter) DeepCopy() *APIGatewayToolFilter {
	if in == nil {
		return nil
	}
	out := new(APIGatewayToolFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIGatewayToolOverride) DeepCopyInto(out *APIGatewayToolOverride) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewayToolOverride.
func (in *APIGatewayToolOverride) DeepCopy() *APIGatewayToolOverride {
	if in == nil {
		return nil
	}
	out := new(APIGatewayToolOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyCredentialProviderItem) DeepCopyInto(out *APIKeyCredentialProviderItem) {
	*out = *in
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyCredentialProviderItem.
func (in *APIKeyCredentialProviderItem) DeepCopy() *APIKeyCredentialProviderItem {
	if in == nil {
		return nil
	}
	out := new(APIKeyCredentialProviderItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntime) DeepCopyInto(out *AgentRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntime.
func (in *AgentRuntime) DeepCopy() *AgentRuntime {
	if in == nil {
		return nil
	}
	out := new(AgentRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeArtifact) DeepCopyInto(out *AgentRuntimeArtifact) {
	*out = *in
	if in.CodeConfiguration != nil {
		in, out := &in.CodeConfiguration, &out.CodeConfiguration
		*out = new(CodeConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerConfiguration != nil {
		in, out := &in.ContainerConfiguration, &out.ContainerConfiguration
		*out = new(ContainerConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeArtifact.
func (in *AgentRuntimeArtifact) DeepCopy() *AgentRuntimeArtifact {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeEndpoint) DeepCopyInto(out *AgentRuntimeEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeEndpoint.
func (in *AgentRuntimeEndpoint) DeepCopy() *AgentRuntimeEndpoint {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRuntimeEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeEndpointList) DeepCopyInto(out *AgentRuntimeEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRuntimeEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeEndpointList.
func (in *AgentRuntimeEndpointList) DeepCopy() *AgentRuntimeEndpointList {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRuntimeEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeEndpointSpec) DeepCopyInto(out *AgentRuntimeEndpointSpec) {
	*out = *in
	if in.AgentRuntimeID != nil {
		in, out := &in.AgentRuntimeID, &out.AgentRuntimeID
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeVersion != nil {
		in, out := &in.AgentRuntimeVersion, &out.AgentRuntimeVersion
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeEndpointSpec.
func (in *AgentRuntimeEndpointSpec) DeepCopy() *AgentRuntimeEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeEndpointStatus) DeepCopyInto(out *AgentRuntimeEndpointStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AgentRuntimeARN != nil {
		in, out := &in.AgentRuntimeARN, &out.AgentRuntimeARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.TargetVersion != nil {
		in, out := &in.TargetVersion, &out.TargetVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeEndpointStatus.
func (in *AgentRuntimeEndpointStatus) DeepCopy() *AgentRuntimeEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeEndpoint_SDK) DeepCopyInto(out *AgentRuntimeEndpoint_SDK) {
	*out = *in
	if in.AgentRuntimeARN != nil {
		in, out := &in.AgentRuntimeARN, &out.AgentRuntimeARN
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeEndpointARN != nil {
		in, out := &in.AgentRuntimeEndpointARN, &out.AgentRuntimeEndpointARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.LiveVersion != nil {
		in, out := &in.LiveVersion, &out.LiveVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.TargetVersion != nil {
		in, out := &in.TargetVersion, &out.TargetVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeEndpoint_SDK.
func (in *AgentRuntimeEndpoint_SDK) DeepCopy() *AgentRuntimeEndpoint_SDK {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeEndpoint_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeList) DeepCopyInto(out *AgentRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeList.
func (in *AgentRuntimeList) DeepCopy() *AgentRuntimeList {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeSpec) DeepCopyInto(out *AgentRuntimeSpec) {
	*out = *in
	if in.AgentRuntimeArtifact != nil {
		in, out := &in.AgentRuntimeArtifact, &out.AgentRuntimeArtifact
		*out = new(AgentRuntimeArtifact)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentRuntimeName != nil {
		in, out := &in.AgentRuntimeName, &out.AgentRuntimeName
		*out = new(string)
		**out = **in
	}
	if in.AuthorizerConfiguration != nil {
		in, out := &in.AuthorizerConfiguration, &out.AuthorizerConfiguration
		*out = new(AuthorizerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.LifecycleConfiguration != nil {
		in, out := &in.LifecycleConfiguration, &out.LifecycleConfiguration
		*out = new(LifecycleConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = new(NetworkConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolConfiguration != nil {
		in, out := &in.ProtocolConfiguration, &out.ProtocolConfiguration
		*out = new(ProtocolConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestHeaderConfiguration != nil {
		in, out := &in.RequestHeaderConfiguration, &out.RequestHeaderConfiguration
		*out = new(RequestHeaderConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeSpec.
func (in *AgentRuntimeSpec) DeepCopy() *AgentRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeStatus) DeepCopyInto(out *AgentRuntimeStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AgentRuntimeID != nil {
		in, out := &in.AgentRuntimeID, &out.AgentRuntimeID
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeVersion != nil {
		in, out := &in.AgentRuntimeVersion, &out.AgentRuntimeVersion
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.WorkloadIdentityDetails != nil {
		in, out := &in.WorkloadIdentityDetails, &out.WorkloadIdentityDetails
		*out = new(WorkloadIdentityDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeStatus.
func (in *AgentRuntimeStatus) DeepCopy() *AgentRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntime_SDK) DeepCopyInto(out *AgentRuntime_SDK) {
	*out = *in
	if in.AgentRuntimeARN != nil {
		in, out := &in.AgentRuntimeARN, &out.AgentRuntimeARN
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeID != nil {
		in, out := &in.AgentRuntimeID, &out.AgentRuntimeID
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeName != nil {
		in, out := &in.AgentRuntimeName, &out.AgentRuntimeName
		*out = new(string)
		**out = **in
	}
	if in.AgentRuntimeVersion != nil {
		in, out := &in.AgentRuntimeVersion, &out.AgentRuntimeVersion
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntime_SDK.
func (in *AgentRuntime_SDK) DeepCopy() *AgentRuntime_SDK {
	if in == nil {
		return nil
	}
	out := new(AgentRuntime_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizerConfiguration) DeepCopyInto(out *AuthorizerConfiguration) {
	*out = *in
	if in.CustomJWTAuthorizer != nil {
		in, out := &in.CustomJWTAuthorizer, &out.CustomJWTAuthorizer
		*out = new(CustomJWTAuthorizerConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizerConfiguration.
func (in *AuthorizerConfiguration) DeepCopy() *AuthorizerConfiguration {
	if in == nil {
		return nil
	}
	out := new(AuthorizerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizingClaimMatchValueType) DeepCopyInto(out *AuthorizingClaimMatchValueType) {
	*out = *in
	if in.ClaimMatchOperator != nil {
		in, out := &in.ClaimMatchOperator, &out.ClaimMatchOperator
		*out = new(string)
		**out = **in
	}
	if in.ClaimMatchValue != nil {
		in, out := &in.ClaimMatchValue, &out.ClaimMatchValue
		*out = new(ClaimMatchValueType)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizingClaimMatchValueType.
func (in *AuthorizingClaimMatchValueType) DeepCopy() *AuthorizingClaimMatchValueType {
	if in == nil {
		return nil
	}
	out := new(AuthorizingClaimMatchValueType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserNetworkConfiguration) DeepCopyInto(out *BrowserNetworkConfiguration) {
	*out = *in
	if in.VPCConfig != nil {
		in, out := &in.VPCConfig, &out.VPCConfig
		*out = new(VPCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserNetworkConfiguration.
func (in *BrowserNetworkConfiguration) DeepCopy() *BrowserNetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(BrowserNetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserProfileSummary) DeepCopyInto(out *BrowserProfileSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastSavedAt != nil {
		in, out := &in.LastSavedAt, &out.LastSavedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserProfileSummary.
func (in *BrowserProfileSummary) DeepCopy() *BrowserProfileSummary {
	if in == nil {
		return nil
	}
	out := new(BrowserProfileSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserSummary) DeepCopyInto(out *BrowserSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserSummary.
func (in *BrowserSummary) DeepCopy() *BrowserSummary {
	if in == nil {
		return nil
	}
	out := new(BrowserSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoricalScaleDefinition) DeepCopyInto(out *CategoricalScaleDefinition) {
	*out = *in
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoricalScaleDefinition.
func (in *CategoricalScaleDefinition) DeepCopy() *CategoricalScaleDefinition {
	if in == nil {
		return nil
	}
	out := new(CategoricalScaleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimMatchValueType) DeepCopyInto(out *ClaimMatchValueType) {
	*out = *in
	if in.MatchValueString != nil {
		in, out := &in.MatchValueString, &out.MatchValueString
		*out = new(string)
		**out = **in
	}
	if in.MatchValueStringList != nil {
		in, out := &in.MatchValueStringList, &out.MatchValueStringList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimMatchValueType.
func (in *ClaimMatchValueType) DeepCopy() *ClaimMatchValueType {
	if in == nil {
		return nil
	}
	out := new(ClaimMatchValueType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Code) DeepCopyInto(out *Code) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Location)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Code.
func (in *Code) DeepCopy() *Code {
	if in == nil {
		return nil
	}
	out := new(Code)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeConfiguration) DeepCopyInto(out *CodeConfiguration) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(Code)
		(*in).DeepCopyInto(*out)
	}
	if in.EntryPoint != nil {
		in, out := &in.EntryPoint, &out.EntryPoint
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeConfiguration.
func (in *CodeConfiguration) DeepCopy() *CodeConfiguration {
	if in == nil {
		return nil
	}
	out := new(CodeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeInterpreterNetworkConfiguration) DeepCopyInto(out *CodeInterpreterNetworkConfiguration) {
	*out = *in
	if in.VPCConfig != nil {
		in, out := &in.VPCConfig, &out.VPCConfig
		*out = new(VPCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeInterpreterNetworkConfiguration.
func (in *CodeInterpreterNetworkConfiguration) DeepCopy() *CodeInterpreterNetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(CodeInterpreterNetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeInterpreterSummary) DeepCopyInto(out *CodeInterpreterSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeInterpreterSummary.
func (in *CodeInterpreterSummary) DeepCopy() *CodeInterpreterSummary {
	if in == nil {
		return nil
	}
	out := new(CodeInterpreterSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerConfiguration) DeepCopyInto(out *ContainerConfiguration) {
	*out = *in
	if in.ContainerURI != nil {
		in, out := &in.ContainerURI, &out.ContainerURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerConfiguration.
func (in *ContainerConfiguration) DeepCopy() *ContainerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ContainerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomClaimValidationType) DeepCopyInto(out *CustomClaimValidationType) {
	*out = *in
	if in.AuthorizingClaimMatchValue != nil {
		in, out := &in.AuthorizingClaimMatchValue, &out.AuthorizingClaimMatchValue
		*out = new(AuthorizingClaimMatchValueType)
		(*in).DeepCopyInto(*out)
	}
	if in.InboundTokenClaimName != nil {
		in, out := &in.InboundTokenClaimName, &out.InboundTokenClaimName
		*out = new(string)
		**out = **in
	}
	if in.InboundTokenClaimValueType != nil {
		in, out := &in.InboundTokenClaimValueType, &out.InboundTokenClaimValueType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomClaimValidationType.
func (in *CustomClaimValidationType) DeepCopy() *CustomClaimValidationType {
	if in == nil {
		return nil
	}
	out := new(CustomClaimValidationType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomJWTAuthorizerConfiguration) DeepCopyInto(out *CustomJWTAuthorizerConfiguration) {
	*out = *in
	if in.AllowedAudience != nil {
		in, out := &in.AllowedAudience, &out.AllowedAudience
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedClients != nil {
		in, out := &in.AllowedClients, &out.AllowedClients
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedScopes != nil {
		in, out := &in.AllowedScopes, &out.AllowedScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CustomClaims != nil {
		in, out := &in.CustomClaims, &out.CustomClaims
		*out = make([]*CustomClaimValidationType, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CustomClaimValidationType)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DiscoveryURL != nil {
		in, out := &in.DiscoveryURL, &out.DiscoveryURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomJWTAuthorizerConfiguration.
func (in *CustomJWTAuthorizerConfiguration) DeepCopy() *CustomJWTAuthorizerConfiguration {
	if in == nil {
		return nil
	}
	out := new(CustomJWTAuthorizerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomMemoryStrategyInput) DeepCopyInto(out *CustomMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomMemoryStrategyInput.
func (in *CustomMemoryStrategyInput) DeepCopy() *CustomMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(CustomMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteMemoryStrategyInput) DeepCopyInto(out *DeleteMemoryStrategyInput) {
	*out = *in
	if in.MemoryStrategyID != nil {
		in, out := &in.MemoryStrategyID, &out.MemoryStrategyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteMemoryStrategyInput.
func (in *DeleteMemoryStrategyInput) DeepCopy() *DeleteMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(DeleteMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpisodicConsolidationOverride) DeepCopyInto(out *EpisodicConsolidationOverride) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpisodicConsolidationOverride.
func (in *EpisodicConsolidationOverride) DeepCopy() *EpisodicConsolidationOverride {
	if in == nil {
		return nil
	}
	out := new(EpisodicConsolidationOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpisodicExtractionOverride) DeepCopyInto(out *EpisodicExtractionOverride) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpisodicExtractionOverride.
func (in *EpisodicExtractionOverride) DeepCopy() *EpisodicExtractionOverride {
	if in == nil {
		return nil
	}
	out := new(EpisodicExtractionOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpisodicMemoryStrategyInput) DeepCopyInto(out *EpisodicMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpisodicMemoryStrategyInput.
func (in *EpisodicMemoryStrategyInput) DeepCopy() *EpisodicMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(EpisodicMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpisodicOverrideConsolidationConfigurationInput) DeepCopyInto(out *EpisodicOverrideConsolidationConfigurationInput) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpisodicOverrideConsolidationConfigurationInput.
func (in *EpisodicOverrideConsolidationConfigurationInput) DeepCopy() *EpisodicOverrideConsolidationConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(EpisodicOverrideConsolidationConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpisodicOverrideExtractionConfigurationInput) DeepCopyInto(out *EpisodicOverrideExtractionConfigurationInput) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpisodicOverrideExtractionConfigurationInput.
func (in *EpisodicOverrideExtractionConfigurationInput) DeepCopy() *EpisodicOverrideExtractionConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(EpisodicOverrideExtractionConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpisodicOverrideReflectionConfigurationInput) DeepCopyInto(out *EpisodicOverrideReflectionConfigurationInput) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpisodicOverrideReflectionConfigurationInput.
func (in *EpisodicOverrideReflectionConfigurationInput) DeepCopy() *EpisodicOverrideReflectionConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(EpisodicOverrideReflectionConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpisodicReflectionOverride) DeepCopyInto(out *EpisodicReflectionOverride) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpisodicReflectionOverride.
func (in *EpisodicReflectionOverride) DeepCopy() *EpisodicReflectionOverride {
	if in == nil {
		return nil
	}
	out := new(EpisodicReflectionOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluatorSummary) DeepCopyInto(out *EvaluatorSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluatorSummary.
func (in *EvaluatorSummary) DeepCopy() *EvaluatorSummary {
	if in == nil {
		return nil
	}
	out := new(EvaluatorSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterValue) DeepCopyInto(out *FilterValue) {
	*out = *in
	if in.StringValue != nil {
		in, out := &in.StringValue, &out.StringValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterValue.
func (in *FilterValue) DeepCopy() *FilterValue {
	if in == nil {
		return nil
	}
	out := new(FilterValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySummary) DeepCopyInto(out *GatewaySummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySummary.
func (in *GatewaySummary) DeepCopy() *GatewaySummary {
	if in == nil {
		return nil
	}
	out := new(GatewaySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayTarget) DeepCopyInto(out *GatewayTarget) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastSynchronizedAt != nil {
		in, out := &in.LastSynchronizedAt, &out.LastSynchronizedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayTarget.
func (in *GatewayTarget) DeepCopy() *GatewayTarget {
	if in == nil {
		return nil
	}
	out := new(GatewayTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceConfiguration) DeepCopyInto(out *InferenceConfiguration) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceConfiguration.
func (in *InferenceConfiguration) DeepCopy() *InferenceConfiguration {
	if in == nil {
		return nil
	}
	out := new(InferenceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvocationConfiguration) DeepCopyInto(out *InvocationConfiguration) {
	*out = *in
	if in.PayloadDeliveryBucketName != nil {
		in, out := &in.PayloadDeliveryBucketName, &out.PayloadDeliveryBucketName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvocationConfiguration.
func (in *InvocationConfiguration) DeepCopy() *InvocationConfiguration {
	if in == nil {
		return nil
	}
	out := new(InvocationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvocationConfigurationInput) DeepCopyInto(out *InvocationConfigurationInput) {
	*out = *in
	if in.PayloadDeliveryBucketName != nil {
		in, out := &in.PayloadDeliveryBucketName, &out.PayloadDeliveryBucketName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvocationConfigurationInput.
func (in *InvocationConfigurationInput) DeepCopy() *InvocationConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(InvocationConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleConfiguration) DeepCopyInto(out *LifecycleConfiguration) {
	*out = *in
	if in.IdleRuntimeSessionTimeout != nil {
		in, out := &in.IdleRuntimeSessionTimeout, &out.IdleRuntimeSessionTimeout
		*out = new(int64)
		**out = **in
	}
	if in.MaxLifetime != nil {
		in, out := &in.MaxLifetime, &out.MaxLifetime
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleConfiguration.
func (in *LifecycleConfiguration) DeepCopy() *LifecycleConfiguration {
	if in == nil {
		return nil
	}
	out := new(LifecycleConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpServerTargetConfiguration) DeepCopyInto(out *McpServerTargetConfiguration) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpServerTargetConfiguration.
func (in *McpServerTargetConfiguration) DeepCopy() *McpServerTargetConfiguration {
	if in == nil {
		return nil
	}
	out := new(McpServerTargetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Memory) DeepCopyInto(out *Memory) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EventExpiryDuration != nil {
		in, out := &in.EventExpiryDuration, &out.EventExpiryDuration
		*out = new(int64)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Memory.
func (in *Memory) DeepCopy() *Memory {
	if in == nil {
		return nil
	}
	out := new(Memory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStrategy) DeepCopyInto(out *MemoryStrategy) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStrategy.
func (in *MemoryStrategy) DeepCopy() *MemoryStrategy {
	if in == nil {
		return nil
	}
	out := new(MemoryStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySummary) DeepCopyInto(out *MemorySummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySummary.
func (in *MemorySummary) DeepCopy() *MemorySummary {
	if in == nil {
		return nil
	}
	out := new(MemorySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessageBasedTrigger) DeepCopyInto(out *MessageBasedTrigger) {
	*out = *in
	if in.MessageCount != nil {
		in, out := &in.MessageCount, &out.MessageCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessageBasedTrigger.
func (in *MessageBasedTrigger) DeepCopy() *MessageBasedTrigger {
	if in == nil {
		return nil
	}
	out := new(MessageBasedTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessageBasedTriggerInput) DeepCopyInto(out *MessageBasedTriggerInput) {
	*out = *in
	if in.MessageCount != nil {
		in, out := &in.MessageCount, &out.MessageCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessageBasedTriggerInput.
func (in *MessageBasedTriggerInput) DeepCopy() *MessageBasedTriggerInput {
	if in == nil {
		return nil
	}
	out := new(MessageBasedTriggerInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifyInvocationConfigurationInput) DeepCopyInto(out *ModifyInvocationConfigurationInput) {
	*out = *in
	if in.PayloadDeliveryBucketName != nil {
		in, out := &in.PayloadDeliveryBucketName, &out.PayloadDeliveryBucketName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifyInvocationConfigurationInput.
func (in *ModifyInvocationConfigurationInput) DeepCopy() *ModifyInvocationConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(ModifyInvocationConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifyMemoryStrategyInput) DeepCopyInto(out *ModifyMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MemoryStrategyID != nil {
		in, out := &in.MemoryStrategyID, &out.MemoryStrategyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifyMemoryStrategyInput.
func (in *ModifyMemoryStrategyInput) DeepCopy() *ModifyMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(ModifyMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifySelfManagedConfiguration) DeepCopyInto(out *ModifySelfManagedConfiguration) {
	*out = *in
	if in.HistoricalContextWindowSize != nil {
		in, out := &in.HistoricalContextWindowSize, &out.HistoricalContextWindowSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifySelfManagedConfiguration.
func (in *ModifySelfManagedConfiguration) DeepCopy() *ModifySelfManagedConfiguration {
	if in == nil {
		return nil
	}
	out := new(ModifySelfManagedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfiguration) DeepCopyInto(out *NetworkConfiguration) {
	*out = *in
	if in.NetworkMode != nil {
		in, out := &in.NetworkMode, &out.NetworkMode
		*out = new(string)
		**out = **in
	}
	if in.NetworkModeConfig != nil {
		in, out := &in.NetworkModeConfig, &out.NetworkModeConfig
		*out = new(VPCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfiguration.
func (in *NetworkConfiguration) DeepCopy() *NetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(NetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumericalScaleDefinition) DeepCopyInto(out *NumericalScaleDefinition) {
	*out = *in
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumericalScaleDefinition.
func (in *NumericalScaleDefinition) DeepCopy() *NumericalScaleDefinition {
	if in == nil {
		return nil
	}
	out := new(NumericalScaleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Oauth2CredentialProviderItem) DeepCopyInto(out *Oauth2CredentialProviderItem) {
	*out = *in
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Oauth2CredentialProviderItem.
func (in *Oauth2CredentialProviderItem) DeepCopy() *Oauth2CredentialProviderItem {
	if in == nil {
		return nil
	}
	out := new(Oauth2CredentialProviderItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnlineEvaluationConfigSummary) DeepCopyInto(out *OnlineEvaluationConfigSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnlineEvaluationConfigSummary.
func (in *OnlineEvaluationConfigSummary) DeepCopy() *OnlineEvaluationConfigSummary {
	if in == nil {
		return nil
	}
	out := new(OnlineEvaluationConfigSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEngine) DeepCopyInto(out *PolicyEngine) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEngine.
func (in *PolicyEngine) DeepCopy() *PolicyEngine {
	if in == nil {
		return nil
	}
	out := new(PolicyEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyGeneration) DeepCopyInto(out *PolicyGeneration) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyGeneration.
func (in *PolicyGeneration) DeepCopy() *PolicyGeneration {
	if in == nil {
		return nil
	}
	out := new(PolicyGeneration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolConfiguration) DeepCopyInto(out *ProtocolConfiguration) {
	*out = *in
	if in.ServerProtocol != nil {
		in, out := &in.ServerProtocol, &out.ServerProtocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolConfiguration.
func (in *ProtocolConfiguration) DeepCopy() *ProtocolConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProtocolConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordingConfig) DeepCopyInto(out *RecordingConfig) {
	*out = *in
	if in.S3Location != nil {
		in, out := &in.S3Location, &out.S3Location
		*out = new(S3Location)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordingConfig.
func (in *RecordingConfig) DeepCopy() *RecordingConfig {
	if in == nil {
		return nil
	}
	out := new(RecordingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestHeaderConfiguration) DeepCopyInto(out *RequestHeaderConfiguration) {
	*out = *in
	if in.RequestHeaderAllowlist != nil {
		in, out := &in.RequestHeaderAllowlist, &out.RequestHeaderAllowlist
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestHeaderConfiguration.
func (in *RequestHeaderConfiguration) DeepCopy() *RequestHeaderConfiguration {
	if in == nil {
		return nil
	}
	out := new(RequestHeaderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Location) DeepCopyInto(out *S3Location) {
	*out = *in
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.VersionID != nil {
		in, out := &in.VersionID, &out.VersionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Location.
func (in *S3Location) DeepCopy() *S3Location {
	if in == nil {
		return nil
	}
	out := new(S3Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaDefinition) DeepCopyInto(out *SchemaDefinition) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaDefinition.
func (in *SchemaDefinition) DeepCopy() *SchemaDefinition {
	if in == nil {
		return nil
	}
	out := new(SchemaDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfManagedConfiguration) DeepCopyInto(out *SelfManagedConfiguration) {
	*out = *in
	if in.HistoricalContextWindowSize != nil {
		in, out := &in.HistoricalContextWindowSize, &out.HistoricalContextWindowSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfManagedConfiguration.
func (in *SelfManagedConfiguration) DeepCopy() *SelfManagedConfiguration {
	if in == nil {
		return nil
	}
	out := new(SelfManagedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfManagedConfigurationInput) DeepCopyInto(out *SelfManagedConfigurationInput) {
	*out = *in
	if in.HistoricalContextWindowSize != nil {
		in, out := &in.HistoricalContextWindowSize, &out.HistoricalContextWindowSize
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfManagedConfigurationInput.
func (in *SelfManagedConfigurationInput) DeepCopy() *SelfManagedConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(SelfManagedConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticConsolidationOverride) DeepCopyInto(out *SemanticConsolidationOverride) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticConsolidationOverride.
func (in *SemanticConsolidationOverride) DeepCopy() *SemanticConsolidationOverride {
	if in == nil {
		return nil
	}
	out := new(SemanticConsolidationOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticExtractionOverride) DeepCopyInto(out *SemanticExtractionOverride) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticExtractionOverride.
func (in *SemanticExtractionOverride) DeepCopy() *SemanticExtractionOverride {
	if in == nil {
		return nil
	}
	out := new(SemanticExtractionOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticMemoryStrategyInput) DeepCopyInto(out *SemanticMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticMemoryStrategyInput.
func (in *SemanticMemoryStrategyInput) DeepCopy() *SemanticMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(SemanticMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticOverrideConsolidationConfigurationInput) DeepCopyInto(out *SemanticOverrideConsolidationConfigurationInput) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticOverrideConsolidationConfigurationInput.
func (in *SemanticOverrideConsolidationConfigurationInput) DeepCopy() *SemanticOverrideConsolidationConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(SemanticOverrideConsolidationConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticOverrideExtractionConfigurationInput) DeepCopyInto(out *SemanticOverrideExtractionConfigurationInput) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticOverrideExtractionConfigurationInput.
func (in *SemanticOverrideExtractionConfigurationInput) DeepCopy() *SemanticOverrideExtractionConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(SemanticOverrideExtractionConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionConfig) DeepCopyInto(out *SessionConfig) {
	*out = *in
	if in.SessionTimeoutMinutes != nil {
		in, out := &in.SessionTimeoutMinutes, &out.SessionTimeoutMinutes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionConfig.
func (in *SessionConfig) DeepCopy() *SessionConfig {
	if in == nil {
		return nil
	}
	out := new(SessionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SummaryConsolidationOverride) DeepCopyInto(out *SummaryConsolidationOverride) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SummaryConsolidationOverride.
func (in *SummaryConsolidationOverride) DeepCopy() *SummaryConsolidationOverride {
	if in == nil {
		return nil
	}
	out := new(SummaryConsolidationOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SummaryMemoryStrategyInput) DeepCopyInto(out *SummaryMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SummaryMemoryStrategyInput.
func (in *SummaryMemoryStrategyInput) DeepCopy() *SummaryMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(SummaryMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SummaryOverrideConsolidationConfigurationInput) DeepCopyInto(out *SummaryOverrideConsolidationConfigurationInput) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SummaryOverrideConsolidationConfigurationInput.
func (in *SummaryOverrideConsolidationConfigurationInput) DeepCopy() *SummaryOverrideConsolidationConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(SummaryOverrideConsolidationConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSummary) DeepCopyInto(out *TargetSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSummary.
func (in *TargetSummary) DeepCopy() *TargetSummary {
	if in == nil {
		return nil
	}
	out := new(TargetSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeBasedTrigger) DeepCopyInto(out *TimeBasedTrigger) {
	*out = *in
	if in.IdleSessionTimeout != nil {
		in, out := &in.IdleSessionTimeout, &out.IdleSessionTimeout
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeBasedTrigger.
func (in *TimeBasedTrigger) DeepCopy() *TimeBasedTrigger {
	if in == nil {
		return nil
	}
	out := new(TimeBasedTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeBasedTriggerInput) DeepCopyInto(out *TimeBasedTriggerInput) {
	*out = *in
	if in.IdleSessionTimeout != nil {
		in, out := &in.IdleSessionTimeout, &out.IdleSessionTimeout
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeBasedTriggerInput.
func (in *TimeBasedTriggerInput) DeepCopy() *TimeBasedTriggerInput {
	if in == nil {
		return nil
	}
	out := new(TimeBasedTriggerInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBasedTrigger) DeepCopyInto(out *TokenBasedTrigger) {
	*out = *in
	if in.TokenCount != nil {
		in, out := &in.TokenCount, &out.TokenCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBasedTrigger.
func (in *TokenBasedTrigger) DeepCopy() *TokenBasedTrigger {
	if in == nil {
		return nil
	}
	out := new(TokenBasedTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBasedTriggerInput) DeepCopyInto(out *TokenBasedTriggerInput) {
	*out = *in
	if in.TokenCount != nil {
		in, out := &in.TokenCount, &out.TokenCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBasedTriggerInput.
func (in *TokenBasedTriggerInput) DeepCopy() *TokenBasedTriggerInput {
	if in == nil {
		return nil
	}
	out := new(TokenBasedTriggerInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolDefinition) DeepCopyInto(out *ToolDefinition) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolDefinition.
func (in *ToolDefinition) DeepCopy() *ToolDefinition {
	if in == nil {
		return nil
	}
	out := new(ToolDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPreferenceConsolidationOverride) DeepCopyInto(out *UserPreferenceConsolidationOverride) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPreferenceConsolidationOverride.
func (in *UserPreferenceConsolidationOverride) DeepCopy() *UserPreferenceConsolidationOverride {
	if in == nil {
		return nil
	}
	out := new(UserPreferenceConsolidationOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPreferenceExtractionOverride) DeepCopyInto(out *UserPreferenceExtractionOverride) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPreferenceExtractionOverride.
func (in *UserPreferenceExtractionOverride) DeepCopy() *UserPreferenceExtractionOverride {
	if in == nil {
		return nil
	}
	out := new(UserPreferenceExtractionOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPreferenceMemoryStrategyInput) DeepCopyInto(out *UserPreferenceMemoryStrategyInput) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPreferenceMemoryStrategyInput.
func (in *UserPreferenceMemoryStrategyInput) DeepCopy() *UserPreferenceMemoryStrategyInput {
	if in == nil {
		return nil
	}
	out := new(UserPreferenceMemoryStrategyInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPreferenceOverrideConsolidationConfigurationInput) DeepCopyInto(out *UserPreferenceOverrideConsolidationConfigurationInput) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPreferenceOverrideConsolidationConfigurationInput.
func (in *UserPreferenceOverrideConsolidationConfigurationInput) DeepCopy() *UserPreferenceOverrideConsolidationConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(UserPreferenceOverrideConsolidationConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPreferenceOverrideExtractionConfigurationInput) DeepCopyInto(out *UserPreferenceOverrideExtractionConfigurationInput) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPreferenceOverrideExtractionConfigurationInput.
func (in *UserPreferenceOverrideExtractionConfigurationInput) DeepCopy() *UserPreferenceOverrideExtractionConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(UserPreferenceOverrideExtractionConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCConfig) DeepCopyInto(out *VPCConfig) {
	*out = *in
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCConfig.
func (in *VPCConfig) DeepCopy() *VPCConfig {
	if in == nil {
		return nil
	}
	out := new(VPCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationExceptionField) DeepCopyInto(out *ValidationExceptionField) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationExceptionField.
func (in *ValidationExceptionField) DeepCopy() *ValidationExceptionField {
	if in == nil {
		return nil
	}
	out := new(ValidationExceptionField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentity) DeepCopyInto(out *WorkloadIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentity.
func (in *WorkloadIdentity) DeepCopy() *WorkloadIdentity {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentityDetails) DeepCopyInto(out *WorkloadIdentityDetails) {
	*out = *in
	if in.WorkloadIdentityARN != nil {
		in, out := &in.WorkloadIdentityARN, &out.WorkloadIdentityARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentityDetails.
func (in *WorkloadIdentityDetails) DeepCopy() *WorkloadIdentityDetails {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentityDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentityList) DeepCopyInto(out *WorkloadIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentityList.
func (in *WorkloadIdentityList) DeepCopy() *WorkloadIdentityList {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentitySpec) DeepCopyInto(out *WorkloadIdentitySpec) {
	*out = *in
	if in.AllowedResourceOauth2ReturnURLs != nil {
		in, out := &in.AllowedResourceOauth2ReturnURLs, &out.AllowedResourceOauth2ReturnURLs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentitySpec.
func (in *WorkloadIdentitySpec) DeepCopy() *WorkloadIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentityStatus) DeepCopyInto(out *WorkloadIdentityStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentityStatus.
func (in *WorkloadIdentityStatus) DeepCopy() *WorkloadIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentityType) DeepCopyInto(out *WorkloadIdentityType) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.WorkloadIdentityARN != nil {
		in, out := &in.WorkloadIdentityARN, &out.WorkloadIdentityARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentityType.
func (in *WorkloadIdentityType) DeepCopy() *WorkloadIdentityType {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentityType)
	in.DeepCopyInto(out)
	return out
}
